### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by anonimo82** [ptitSeb/gl4es#108]
Hello everyone.
I'm facing issue with GL4ES, the rendered surface has wrong colors and is skewed.
I'm facing this in glxgears and blender, for now.
![Screenshot_2019-05-19-12-35-21](https://user-images.githubusercontent.com/38261009/57981056-1a058180-7a33-11e9-8343-066336ffd12d.jpg)

Thanks for help.

**Comment by ptitSeb** [comment]
Mmm, there seems to be an issue with the EGL context created. Can you copy/paste here the output of GL4ES on glxgears (all the `LIBGL: ` lines)?

**Comment by anonimo82** [comment]
LIBGL: Initialising gl4es
LIBGL: v1.1.1 built on May 19 2019 12:00:17
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so.2
LIBGL: loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: No alpha channel in PBuffer context, disabling EGL Alpha channel...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_stencil8 detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: Extension GL_OES_texture_half_float detected and used
LIBGL: Extension GL_EXT_color_buffer_float detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Hardware vendor is VMware, Inc.
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.0
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/home/android

**Comment by anonimo82** [comment]
Note I'm using a CHRoot Linux on Android, x86_64 architecture, and i didn't use any switch (because i don't know which is appropriate).

**Comment by ptitSeb** [comment]
Well, I see nothing unusual in the logs (exept VMWare vendor, so I guess this is a VM). The EGL context doesn't seems correct. Try with `LIBGL_FB=1` (if it works, it will be fullscreen only) and `LIBGL_FB=3` (this one should wok, but maybe slower).

**Comment by anonimo82** [comment]
Where should I put those options?
Compiling or running?

**Comment by ptitSeb** [comment]
Oh, it's runtime. It's env. variable. `export` them or just put them in front of your command line...

**Comment by anonimo82** [comment]
Yes, works perfectly.
What should I do to automatically set that variable at startup?

**Comment by ptitSeb** [comment]
Wich one worked ?
In `src/gl/init.c` line 79 insert `globals4es.usefb = 1;` (or `globals4es.usepbuffer = 1;` if it's `LIBGL_FB=3`).

**Comment by anonimo82** [comment]
The 2nd.
