### ISSUE TITLE
GL4ES support on iOS

### ISSUE THREAD

**Issue by terabyte25** [ptitSeb/gl4es#109]
Asking this since I'm interested in porting an OpenGL application on iOS.

Is there any support for iOS yet? I'm interested in getting this to work on that platform, but I haven't seen any project do it yet.

**Comment by ptitSeb** [comment]
I don't have any iOS suport yet. But why not.
Main question is: how to create the GL Context: using GLX, some Cocoa stuff, or maybe a "no GL Context creation" strategy, like with Android (iOS app alway havea GLES context created right)?
Any thought on that point?

**Comment by terabyte25** [comment]
https://developer.apple.com/documentation/opengles/eaglcontext (GLES context)

**Comment by eyvallah** [comment]
@ptitSeb iOS uses EAGLContext, by calling a [[EAGLContext alloc] initWithAPI:kEAGLRenderingAPIOpenGLES1], you create a gles1 context. it can be replaced with GLES2, GLES3. a gl view needed to be assigned a EAGLContext before it can present anything GL.  to switch between contexts, use [EAGLContext setCurrentContext:] with the context.
