### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by anonimo82** [ptitSeb/gl4es#110]
hello everyone.
build fails with: rc/gl/init.c:17:1: error: expected identifier or ‘(’ before numeric constant
help

**Comment by ptitSeb** [comment]
Are you using latest code? Because I have an empty line in line 17...
Also, on what system are you compiling?

**Comment by anonimo82** [comment]
Yes, just cloned the repo.
Linux Debian Stable (Linux deploy on Android chroot).
Please, note the build succeded some weeks ago on the sane system, but I can't access it anymore.

**Comment by anonimo82** [comment]
Maybe I'm missing dependencies?

**Comment by anonimo82** [comment]
Men, how dumb am I?
I didn't notice the number '21' was the 17th line of that file, don't know how it appeared there.
Just deleting the line now compiles it right.

Excuse me.

**Comment by ptitSeb** [comment]
Ah so there is no issue, good :)
