### ISSUE TITLE
broken support for OpenGL 2 in latest code/build

### ISSUE THREAD

**Issue by anonimo82** [ptitSeb/gl4es#111]
Hello everyone.
As in subject, I get an error when launching Blender, because it requires OpenGL 2.1 and I don't have it.
Here's the output of launching it from CLI:

snip

What should I do? glxgears works fine.

**Comment by ptitSeb** [comment]
You need to export `LIBGL_GL=21` to expose OpenGL 2.1 functionnalities. That should be enough.

**Comment by anonimo82** [comment]
I get other errors and segfault

Il sab 1 giu 2019 14:18 ptitSeb <notifications@github.com> ha scritto:

**Comment by ptitSeb** [comment]
What error, and using which Blender version?

**Comment by anonimo82** [comment]
LIBGL: Initialising gl4es
LIBGL: v1.1.1 built on Jun  1 2019 12:17:11
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so.2
LIBGL: loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
LIBGL: Error while gathering supported extension (eglInitialize: EGL_NOT_INITIALIZED), default to none
LIBGL: Targeting OpenGL 2.1
LIBGL: Current folder is:/home/idm
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
LIBGL: ERROR: EGL Error detected: EGL_NOT_INITIALIZED
LIBGL: Unable to initialize EGL display.
LIBGL: Unable to initialize EGL.
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:${ORIGIN}/dri:/usr/lib/dri)
LIBGL: ERROR: EGL Error detected: EGL_NOT_INITIALIZED
LIBGL: Unable to initialize EGL display.
LIBGL: Unable to initialize EGL.
Writing: /tmp/blender.crash.txt
Errore di segmentazione

**Comment by anonimo82** [comment]
After some experiment, I made it working (partially).
I get a blank (transparent) window and this is the console log:

LIBGL: Initialising gl4es
LIBGL: v1.1.1 built on Jun  1 2019 16:45:37
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so.2
LIBGL: loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: No alpha channel in PBuffer context, disabling EGL Alpha channel...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_stencil8 detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: Extension GL_OES_texture_half_float detected and used
LIBGL: Extension GL_EXT_color_buffer_float detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Hardware vendor is VMware, Inc.
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.1
LIBGL: Current folder is:/home/idm
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented

**Comment by ptitSeb** [comment]
I think the only think that may work fine at this stage for you is `LIBGL_FB=3` That oe should get you usable windows, but it may be a bit slow...

**Comment by anonimo82** [comment]
I've already did that in the code, as suggested here: https://github.com/ptitSeb/gl4es/issues/108#issuecomment-493749322

By the way, a couple weeks ago it was working.

**Comment by ptitSeb** [comment]
It was ? Mmmm, can you try to `git bisect` to find the commit that broke it?

**Comment by anonimo82** [comment]
How?

**Comment by ptitSeb** [comment]
Find a working version manually (checkout a version from 2 weeks ago), the use the git bisect command to help you find the offending commit (look here: https://git-scm.com/docs/git-bisect ) it can be a bit long but it's very usefull.

**Comment by anonimo82** [comment]
I made it. I downloaded and installed version 1.0.8, installed packages for libgles and libegl and now Blender (at least) opens.
Note I also exported 2 variables, LIBGL_GL=21 and LIBGL_FB=3.
Side note: how can I automatically export variables on login?
I'm still having issues with hardware acceleration.

I'm attaching the log
[blender.log](https://github.com/ptitSeb/gl4es/files/3244543/blender.log)

**Comment by anonimo82** [comment]
P.S.: Is it there any environment variables reference, to guess what could be set and for what reason?

**Comment by ptitSeb** [comment]
I'll check on my side on the Pandora.

As for the documentation, yes there is, look in the README from github, there is a link to `USAGE.md` with all env. var. and their effect.

**Comment by ptitSeb** [comment]
I just tried latest gl4es with blender 2.68 and it was working fine on the Pandora (using `LIBGL_FB=3 LIBGL_ES=2 LIBGL_GL=21`).
What version of blender are you trying?

**Comment by anonimo82** [comment]
2.79 and using those values I can only see black squares

**Comment by ptitSeb** [comment]
I will have to build 2.79 on the Pandora to test. That will take some time (days, plus I'm not only doing that).
Shader handling may have changed since 2.68...
I'll check on the Pandora...

**Comment by anonimo82** [comment]
See above

**Comment by ptitSeb** [comment]
yes, the `LIBGL_ES=2` is default everywhere exept on Pandora.
Now, to default on 2.1 instead of 2.0, change that line https://github.com/ptitSeb/gl4es/blob/master/src/gl/init.c#L142 and replace the `20` by `21`

**Comment by anonimo82** [comment]
Can't I declare the variable in an init script each boot?
I wrote LIBGL_GL, not LIBGL_ES

**Comment by anonimo82** [comment]
And look at VLC's output:

**Comment by ptitSeb** [comment]
Yes, that line is about `LIBGL_GL`.
Yes, you can simply add `export LIBGL_GL=21` in you `~/.bashrc` for example to always have this variable initialized.

(no output log for now in the message above)

**Comment by anonimo82** [comment]
I'm having troubles uploading the screenshot

Thanks

**Comment by anonimo82** [comment]
Here it is:

Il dom 2 giu 2019 18:30 ptitSeb <notifications@github.com> ha scritto:

**Comment by anonimo82** [comment]
![Screenshot_2019-06-02-18-18-37](https://user-images.githubusercontent.com/38261009/58764435-380ccf00-8567-11e9-8f94-6de8873cd977.jpg)

**Comment by ptitSeb** [comment]
Mmm ok.
Is there some error message in the console?
Also, try running with `LIBGL_LOGSHADERERROR=1` to see if some shaders fail to compile.

**Comment by anonimo82** [comment]
VLC media player 3.0.6 Vetinari (revision 3.0.6-0-g5803e85f73)
shared memfd open() failed: Funzione non implementata
[00007f6fe984d1a0] main libvlc: Esecuzione di vlc con l'interfaccia predefinita. Usa 'cvlc' per utilizzare vlc senza interfaccia.
LIBGL: Initialising gl4es
LIBGL: v1.0.8 built on Jun  2 2019 09:30:05
LIBGL: Using GLES 1.1 backend
LIBGL:loaded: libGLESv1_CM.so.1
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 1.1 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.1
LIBGL: Current folder is:/home/idm
[00007f6fe98ea2e0] main playlist: playlist is empty
QXcbConnection: XCB error: 151 (Unknown), sequence: 172, resource id: 0, major code: 144 (Unknown), minor code: 20
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by ptitSeb** [comment]
Oh, wait, your are still using v1.0.8 ?! That means you are still using GLES1.1 and not GLES2.0 with shaders. That's why Blender (and probably Vlc) will not work!
You need to use `LIBGL_ES=2` with 1.0.8 to have Shaders enabled.

**Comment by anonimo82** [comment]
Same output

**Comment by ptitSeb** [comment]
I don't see anything in this log. Just the fact it doesn't succeed in gathering extension (meaning it probably fail at creating an offscreen context). Can you use `master` instead of 1.0.8?

**Comment by anonimo82** [comment]
Ok, I'll try now

**Comment by anonimo82** [comment]
This is the result (all variables exported)
![Screenshot_2019-06-02-23-37-03](https://user-images.githubusercontent.com/38261009/58767716-d90f8000-858f-11e9-85a3-e99746d0481c.jpg)

**Comment by anonimo82** [comment]
Same result with:
LIBGL_GL=21 + LIBGL_FB=3
LIBGL_GL=21 + LIBGL_ES=2
All of them
LIBGL_GL=21 only

**Comment by ptitSeb** [comment]
Just a small question: are you sure your blender is correctly installed? Because I had this kind of behavour with an incorrectly setup of Blender on my side.

**Comment by anonimo82** [comment]
Yes, it was working with older gl4es

**Comment by ptitSeb** [comment]
And glxgears works fine?

**Comment by anonimo82** [comment]
Yes, but with LIBGL_FB=3
(LIBGL_GL=21 exported at login with .bashrc)

**Comment by ptitSeb** [comment]
and with `LIBGL_FB=3` on blender you have that same empty window?

**Comment by anonimo82** [comment]
Yep

**Comment by ptitSeb** [comment]
Can you encomment this line https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L40 and do a try again. You'll need to copy/paste the console output here.

**Comment by anonimo82** [comment]
idm@localhost:~$ blender
LIBGL: Initialising gl4es
LIBGL: v1.1.1 built on Jun  3 2019 17:55:05
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so.2
LIBGL: loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: No alpha channel in PBuffer context, disabling EGL Alpha channel...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_stencil8 detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: Extension GL_OES_texture_half_float detected and used
LIBGL: Extension GL_EXT_color_buffer_float detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Hardware vendor is VMware, Inc.
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.1
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/home/idm
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
glXQueryVersion(0x7fcdef991000, 0x7ffcb3936e90, 0x7ffcb3936eb0)
glXChooseVisual(0x7fcdef991000, 0, 0x7ffcb3936f20)
glXChooseFBConfig(0x7fcdef991000, 0, 0x7ffcb3936d40, 0x7ffcb3936d3c)
FBConfig doubleBufferMode=1
FBConfig redBits=1
FBConfig blueBits=1
FBConfig greenBits=1
FBConfig depthBits=1
glXChooseFBConfig found 8 config
glXQueryExtension(0x7fcdef991000, (nil), (nil))
glXGetClientString(0x7fcdef991000, 3)
glXQueryExtensionString(0x7fcdef991000, 0)
glXChooseFBConfig(0x7fcdef991000, 0, 0x7ffcb3936ca0, 0x7ffcb3936c6c)
FBConfig doubleBufferMode=1
FBConfig redBits=1
FBConfig blueBits=1
FBConfig greenBits=1
FBConfig depthBits=1
glXChooseFBConfig found 8 config
glXCreateContextAttribsARB(0x7fcdef991000, 0x7fce0e402500, (nil), 1) config is RGBA:8880, depth=16, stencil=0, drawable=7
 => return 0x7fcdef8fc800 (context->shared=(nil))
glXMakeCurrent(0x7fcdef991000, 0x1c00002, 0x7fcdef8fc800), isPBuffer(drawable)=0, context->drawable=(nil), context->eglSurface=(nil)((nil)), context->doublebuff=1
LIBGL: eglMakeCurrent(0x7fcdef8dd400, 0x7fcde6c4f080, 0x7fcde6c4f080, 0x7fcdef89b6d0)
LIBGL: EGLSurface for drawable 0x1c00002 Added
 => True (glstate=0x7fcde6d04000)
glXGetCurrentDisplay()
glXQueryVersion(0x7fcde6f78000, 0x7ffcb3936ad8, 0x7ffcb3936adc)
glXGetCurrentDisplay()
glXGetClientString(0x7fcde6f80000, 3)
glXQueryExtensionString(0x7fcde6f80000, 0)
glXSwapBuffers(0x7fcdef991000, 0x1c00002) glXGetCurrentDisplay()
glXQueryVersion(0x7fcde6f8a000, 0x7ffcb3936ad8, 0x7ffcb3936adc)
glXGetCurrentDisplay()
glXGetClientString(0x7fcde6f96000, 3)
glXQueryExtensionString(0x7fcde6f96000, 0)
Ucciso
idm@localhost:~$

**Comment by ptitSeb** [comment]
Everything looks good in that log. It's strange that the windows doesn't show, because there is no error, all context seems to be created properly.
Maybe it need to be forced to RGBA 8888 instead of 8880 it choose? I need to look in glx.c what would be the best way to do that.

**Comment by anonimo82** [comment]
Again, 1.0.8 was working

**Comment by ptitSeb** [comment]
Yes, but a lot of things changed since v1.0.8. Can you do a `git bisect` between `1.0.8` and `master` to find the commit that broke things for you. That will be a bit long (may be try the 1.1.0 also, if it works, use it as a "good" one, if it doesn't, use it as a "bad" one instead of master), but that will help a lot in finding what's wrong!

**Comment by anonimo82** [comment]
I really don't know anything aout git, and either bisect.
For downloading 1.0.8 I set the tag and downloaded as zip

**Comment by ptitSeb** [comment]
Here another web site with some git bisect example: https://flaviocopes.com/git-bisect/

Basically, git bisect just help find the commit that "broke" things. So you clone a repo, set a commit that is "good", a commit that is "bad", and git bisect will do some dichotomy to find the commit that changed frm "good" to "bad" in a minimum step. You will need to compile and test each step, to tell git if the tested commit if good or bad. Pretty efficient, but between 1.0.8 and master, it will take a lot of step.

**Comment by anonimo82** [comment]
Excuse me, it's too much. Is it there any other way?
By the way, update: I downloaded libgl1-mesa-swx11 and replaced the libGL.so.1 with gl4es one, exported LIBGL_GL=21 and LIBGL_FB=3, still same result.
GLXGears works very well, VLC doesn't work (same problem as above).

Blender still have the same problem, but please, do note I have to kill its task when launching, because the window also is unresponsive. (I use sudo kill -KILL pid).

Thanks for now.

**Comment by anonimo82** [comment]
P.S.: I saw a line in the blender output which says RGBA is set to 8880.
Is this useful?

**Comment by ptitSeb** [comment]
Yeah, I already saw that RGBA 8880 line.

You can try to comment this line https://github.com/ptitSeb/gl4es/blob/master/src/glx/hardext.c#L143 (in latest version of the code) and see if it helps.

Also, when you say "it's too much", do you mean too much work or too complicated?

**Comment by anonimo82** [comment]
I'm gonna try this now.
I mean both.

**Comment by anonimo82** [comment]
No, same results

**Comment by anonimo82** [comment]
And this is the console output when using gl4es clean, all variables set (those you told me to set)

https://pastebin.com/WBLrFzaX

Still the blank window

**Comment by anonimo82** [comment]
I'm opening a new one
