### ISSUE TITLE
Fake some server strings

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/gl4es#12]
glXQueryServerString will return some empty strings.

This will cause some programs to fail.

For example, libepoxy, which used by clutter and gtk, uses server's version string to parse GL version, and will fail on GL4ES.

**Comment by ptitSeb** [comment]
Ok, I'll make glXQueryServerString and glXQueryClientString respond something not empty.

**Comment by ptitSeb** [comment]
Done with 716efa2ef690177462119cf708b73ffecbebd5f5

**Comment by Icenowy** [comment]
Tested on gtk3-demo :-)

**Comment by ptitSeb** [comment]
With gtk3, nice!

I'm closing the ticket. as it works now.
