### ISSUE TITLE
Back faces flash in ManiaDrive

### ISSUE THREAD

**Issue by icecream95** [ptitSeb/gl4es#128]
In ManiaDrive, the back faces of polygons have brightly coloured flashing textures, like in this screenshot.

![Image](https://user-images.githubusercontent.com/29191311/64918491-03a9df80-d7f3-11e9-94f1-ffadfbf0ac29.png)

**Comment by ptitSeb** [comment]
I don't reproduce the issue on my Pandora. Do you have any special settings?
I assume it's GLES2 backend? Are the shadows in ManiaDrive enabled?

**Comment by icecream95** [comment]
Turning off shadows don't make any difference.

GLES1 works fine, though.

**Comment by ptitSeb** [comment]
But I can reproduce something similar (the back face polygon are absent) on a Linux VM, so I have something to debug.

**Comment by ptitSeb** [comment]
I think this is fixed now, with commit 52ca7f584885bbbd7583d7126f255658e591c874
