### ISSUE TITLE
Any plans for gl4vk?

### ISSUE THREAD

**Issue by AndreVallestero** [ptitSeb/gl4es#133]
Vulkan support without Open GL 2+ support is relatively common among ARM based devices so it would be nice to see a gl4vk effort which could lead to more software compatibility and higher performance.

**Comment by ptitSeb** [comment]
Yes, I agree, it would be nice (and a superb opportunity to really dig into Vulkan). Bt for now, with box86, I think my plate is full and could not start a project of this size.
Myabe a bit later?

In the mean time, GLOVE can probably help (even if that makes a lot of layers). I haven't tried it, but that seem to fill the gap here.

**Comment by redchenjs** [comment]
Mesa Gallium3D Zink: [https://www.phoronix.com/scan.php?page=news_item&px=Zink-Merged-Mesa-19.3](https://www.phoronix.com/scan.php?page=news_item&px=Zink-Merged-Mesa-19.3) 
VKGL: [https://github.com/kbiElude/VKGL](https://github.com/kbiElude/VKGL)

**Comment by AndreVallestero** [comment]
Thanks for the links @redchenjs , I'll check those projects out. Closing issue.
