### ISSUE TITLE
Cant build on pocketCHIP

### ISSUE THREAD

**Issue by SteigerHSV** [ptitSeb/gl4es#135]
so i was trying to build gl4es but cant

```
git clone https://github.com/ptitSeb/gl4es
cd gl4es
mkdir build; cd build; cmake .. -DCHIP=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make
```
it jump to gl4es/build and:
> *** no targets specified and no makefile found. Stop.

i also try:
```
cd gl4es
cmake .. -DCHIP=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make
```
but cmake 

> "command not found"

**Comment by ptitSeb** [comment]
I think you are missing the `cmake` program.
Try `sudo apt install cmake` first.

**Comment by SteigerHSV** [comment]
super thanks!

**Comment by ptitSeb** [comment]
Can I close this ticket?
