### ISSUE TITLE
Maybe glBlendFuncSeparate has bug

### ISSUE THREAD

**Issue by CosineMath** [ptitSeb/gl4es#141]
Hello! I'm now studying Boardwalk, an Android App which allows we play Minecraft Java Edition on Android. Boardwalk uses gl4es to provide OpenGL APIs for Minecraft. I found rendering is incorrect (Texture becoming dark) if I used the function gl4es provided. When using default function of libGLESv2.so of Android it works well (at least visually).

**Comment by ptitSeb** [comment]
I'm not sure I understand, especially the libGLESv2.so part. Are you abble to run Minecraft just with libGLESv2?

Can you provide screenshots of the differences

(what I remember of Minecraft rendering, the lightmap is in a different  texture unit, and only 1 texel per "cube" is set, I mean 1 `glMultiTexCoord4f(...)` par whole cube... Maybe that got broken somehow latelly).
What version of gl4es is used in Boardwalk by the way?

**Comment by CosineMath** [comment]
I don't know much about rendering of Mineraft... The libGLESv2.so provides OpenGL ES 2.0 APIs (I think ). I think we cannot run Minecraft just with it. I changed the code of lwjgl, used dlfcns to open libGLESv2.so and provided glBlendFuncSeparate in this lib to Minecraft. (I checked if the function called was named glBlendFuncSeparate and if not returned the one in gl4es)
![Screenshot_2020-01-15-23-17-51](https://user-images.githubusercontent.com/25523815/72445977-a4ce9400-37ed-11ea-88fb-8853ad1f4027.jpeg)
Icons in GUI are bad, also the sky. 

I "git clone" a copy of gl4es on 2020.1.2 rather than using a release.

**Comment by ptitSeb** [comment]
Ok. I see.

Be sure to build gl4es for GLES2 backend then. (uncomment line 85 of Android.mk). be sure to create a GLES2 context also, not an GLES1.1.

**Comment by CosineMath** [comment]
Thank you! I will try GLES2 backend tomorrow again. (I have tried it, but lwjgl crashed reporting some OpenGL functions are missing.)

**Comment by ptitSeb** [comment]
I used GLES2 backend on ARM linux with minecraft and had no issue, even with lwjgl 3. Si it whould be ok. Be sure to rebuild all gl4es once you change the parameter, just in case...

**Comment by CosineMath** [comment]
Sorry to report that I failed to use gl4es compiled with GLES2 backend. It crashed with some problems and I had tried to fix some errors caused by lwjgl (Maybe, I am not sure). Then I met a problem I don't know how to solve. Unwinder said that SegmentFault occured when steped to 

libGL.so.1 (The gl4es lib) : gl/uniform.c : GoUniformfv(...) : line 182~183....

I disabled the hardware extensions detection of gl4es because it detected GL_OES_framebuffer_object which caused crashes. Instead, I replaced the result of gles_glGetString(GL_EXTENSIONS) with a string manually. The string is the result of glGetString(GL_EXTENSIONS) on my device but without GL_OES_framebuffer_object.

**Comment by ptitSeb** [comment]
The DLES2 Backend should work. I assume the issue is because current used context is GLES1.1 and not GLES2.0
On Android side, you need to set the application as using GLES2.0, not GLES1.1. Isn't there a setting somewhere in android studio for that?

**Comment by CosineMath** [comment]
Maybe I get what is wong... The macro LOAD_GLES2_OR_OES (in NOEGL mode) used by gl4es_glBlendFuncSeparate in  gl/blend.c:line 33  might be incorrect and fail to load the function glBlendFuncSeparateOES in libGLESv1_CM.so (the GLES1.1 backend being used). The fallback functions provided by gl4es_glBlendFuncSeparate caused bad rendering. 

Yeah, I don't notice much about GLContext. It may be the cause. I would work on it then.

**Comment by ptitSeb** [comment]
The `LOAD_GLES2_OR_OES` macro works fine. If it doesn't find it it's because that function is not available in your GLES 1.1 driver. It is part of core on GLES 2.0, so using this backen will work.

You should have a look at the OpenMW project for Android. They use gl4es for OpenGL rendering, and they even have an option in their launcher to choose between GLES 1.1 or GLES 2.0 backend.

**Comment by CosineMath** [comment]
I have checked the libGLESv1_CM.so in my device. It has a symbol named glBlendFuncSeparateOES. The macro LOAD_GLES2_OR_OES defined in gl/loader.h will not append "OES" to the name (NOEGL mode) (gl/loader.h:line200~204):
`#define LOAD_GLES2_OR_OES(name) \
    DEFINE_RAW(gles, name); \
    { \
        LOAD_RAW_SILENT(gles, name, proc_address(gles, #name)); \
    }`

Then I change it just as the one in !NOEGL block below:
`#define LOAD_GLES2_OR_OES(name) \
    DEFINE_RAW(gles, name); \
    { \
        LOAD_RAW_SILENT(gles, name, ( (hardext.esversion==1)?((void*)proc_address(gles, #name"OES")):((void*)proc_address(gles, #name)) ) ); \
    }`

then the funtion is located successfully. 

I would go to have a look at the OpenMW project for Android and try to use GLES2 backend. 
Thanks a lot for your help ! :)

**Comment by ptitSeb** [comment]
Ah, I see. Maybe I should have an ANDROID version of the `LOAD_GLES2_OR_OES` macro, similar to the regular version, instead of the NOEGL one. Let me check that.

**Comment by ptitSeb** [comment]
Oh wait, why are you on `NOEGL` ? You are on Android right? So you should have `NOX11` and `NO_GBM` but that it.

In `loader.h`, you should not be in the part of `#if defined(AMIGAOS4) || defined(NOEGL) || defined(__EMSCRIPTEN__)` but in the `#else` part on Android!

**Comment by CosineMath** [comment]
I have tried to compile without -DNOEGL flag. It reported errors : isPBuffer and delPBuffer not defined (glx/glx.c:line235~237). These functions seem to be defined only when without -DNOX11 flag (glx/glx.c:line85~128)

**Comment by CosineMath** [comment]
I have tried to compile without -DNOEGL flag. It reported errors : isPBuffer and delPBuffer not defined (glx/glx.c:line 235~237). These functions seem to be defined only when without -DNOX11 flag (glx/glx.c:line 85~128).

**Comment by CosineMath** [comment]
I have tried to compile without -DNOEGL flag. It reported errors : isPBuffer and delPBuffer not defined (glx/glx.c:line235 237). These functions seem to be defined only when without -DNOX11 flag (glx/glx.c:line85 128) .

**Comment by CosineMath** [comment]
I tried to comment these code (glx/glx.c:RecycleDelSurface(...)). Compilation succeeded. GLES2 backend worked successfully (But sorry to report still with some rendering errors.) . Thanks! :)

**Comment by ptitSeb** [comment]
I have pushed a fix for the compilation issue.

You have rendering errors with both GLES1.1 and GLES2.0 ? The same kind of rendering error or is it something else?

**Comment by CosineMath** [comment]
(Testing GLES2.0 backend):
(Testing Minecraft 1.8.9)If we set the Mipmap level to 4 (in Video Settings of Minecraft), some strange dark shadow will appear far away. Sometimes, the rendering of Mob is incorrect(They become dark).(If we set Mipmap level to "off", no such error). 

(Testing Minecraft 1.7.10) If we set the Mipmap level to 4 (in Video Settings of Minecraft), the decoration on the ground in a flat world (Such as cactus in desert) looks like floating . (If we set Mipmap level to "off", no such error).


If use GLES1.1 backend, the error is similar ,for Minecraft 1.7.10. For Minecraft 1.8.9, the GLES1.1 backend is pretty bad . (The whole world turn dark after some mobs are hurt.)

**Comment by ptitSeb** [comment]
Ah yes, I have issues with Minecraft's mipmap. I'm not how they are handling this, but it's not will supported on gl4es. That's why I use `LIBGL_MIPMAP=3` to ignore mipmap on my side.

**Comment by CosineMath** [comment]
OK. I might change the default option.txt for Minecraft provided by Boardwalk to work around this issue. GLES2.0 backend works fine .(Some details are correct now, for instance, the rendering of enchanted items. It seems that FPS also increases.)

Thanks for your help! I will close this issue then. \﻿ (•◡•) /

**Comment by Malaska678** [comment]
Then the first working launcher that support 1.12 and forge borned.

**Comment by ptitSeb** [comment]
What do you mean @Malaska678 ?

**Comment by AyHa1810** [comment]
Lol, my reply is very late. Btw, @ptitSeb, he means that this conversation led to the born of MCinaBox which can launch any version of Minecraft Java Edition on Android device.

**Comment by Malaska678** [comment]
> What do you mean @Malaska678 ?

I mean boat launcher. Cosine Math's own minecraft java on android
