### ISSUE TITLE
[regression] crash in hasBuiltinAttrib

### ISSUE THREAD

**Issue by mittorn** [ptitSeb/gl4es#147]
regression in https://github.com/ptitSeb/gl4es/commit/761dfe66aff0a636a0e75b9a23b563d156c3aca6
crash because vertexShader is NULL when loading map in Xash3D

**Comment by ptitSeb** [comment]
do you have a back trace of the crash?

**Comment by ptitSeb** [comment]
I have pushed a fix.
I don't think this was a regression, as I fixed the crash when using GLES2 shaders.

Please test if it's fixed for you (I'm build latest Xash3d on my side to try reproduce also the L8A8 and other textures issues)

**Comment by mittorn** [comment]
I used same fix, it helped

**Comment by ptitSeb** [comment]
Ok, I guess we can close this one .
