### ISSUE TITLE
Build instructions don't mention which toolchains are known to successfully build this

### ISSUE THREAD

**Issue by ssokolow** [ptitSeb/gl4es#15]
I'm trying to build a copy of this to experiment with pairing it with `qemu-i386` on my Pandora but I've been having trouble with the build instructions.

Normally, I use a copy of sebt3's Yactfeau toolchain for cross-compiling, but this is as far as I can get with it in this case.

```
export CC=/home/ssokolow/opt/pandora-dev/arm-2011.09/bin/pandora-gcc CXX=/home/ssokolow/opt/pandora-dev/arm-2011.09/bin/pandora-g++
ssokolow@monolith gl4es [master] % cmake . -DPANDORA=1; make GL                                                                                                                      
-- The C compiler identification is GNU 4.6.1
-- The CXX compiler identification is GNU 4.6.1
-- Check for working C compiler: /home/ssokolow/opt/pandora-dev/arm-2011.09/bin/arm-none-linux-gnueabi-gcc
-- Check for working C compiler: /home/ssokolow/opt/pandora-dev/arm-2011.09/bin/arm-none-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/ssokolow/opt/pandora-dev/arm-2011.09/bin/pandora-g++
-- Check for working CXX compiler: /home/ssokolow/opt/pandora-dev/arm-2011.09/bin/pandora-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ssokolow/src/read-only/gl4es
Scanning dependencies of target GL
[  2%] Building C object src/CMakeFiles/GL.dir/gl/array.c.o
In file included from /home/ssokolow/src/read-only/gl4es/include/EGL/egl.h:36:0,
                 from /home/ssokolow/src/read-only/gl4es/src/gl/gl.h:4,
                 from /home/ssokolow/src/read-only/gl4es/src/gl/array.h:1,
                 from /home/ssokolow/src/read-only/gl4es/src/gl/array.c:1:
/home/ssokolow/src/read-only/gl4es/include/EGL/eglplatform.h:89:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
make[3]: *** [src/CMakeFiles/GL.dir/gl/array.c.o] Error 1
make[2]: *** [src/CMakeFiles/GL.dir/all] Error 2
make[1]: *** [src/CMakeFiles/GL.dir/rule] Error 2
make: *** [GL] Error 2
```

I'm assuming that, since you didn't mention installing additional dependencies, you develop against a different toolchain which already includes the requisite headers... but which one?

**Comment by ptitSeb** [comment]
X11 header are required. That should be the only requirement.
I compile on the Pandora itself using codeblocks command line, on my custom-built cross-compilation env, on ODroid and on a Mint VM. I haven't tried on Yactfeau VM.

**Comment by ssokolow** [comment]
Yactfeau isn't a VM... just a cross-compiling GCC with some extras like the `pnd_make` script.

I don't have time to try anything further right now (I'm overdue to start working on some less leisure-oriented personal projects) but, if/when I get back to it, I'll let you know.

**Comment by ptitSeb** [comment]
Ah ok, I only used pre-built VM from sebt3's a long time ago.
Still, you need to add X11 headers (there are probably somewhere but need some specifics "-I" flags as this is pretty standard requirements).

**Comment by ptitSeb** [comment]
I'll close this issue soon, I think the different readme are addecate now.
