### ISSUE TITLE
Glxinfo symbol lookup Error

### ISSUE THREAD

**Issue by AllPlatform** [ptitSeb/gl4es#159]
Hello, I have some The problem (sorry for losing your time) Please take a look at it
I installed it as follows /gl4es/COMPILE.md
`cmake .. -DBCMHOST=1 -DNOEGL=1 -DNOX11=1 -DDEFAULT_ES=2 -DUSE_CLOCK=ON -DCMAKE_C_FLAGS="-marm -mcpu=cortex-a9 -mfpu=neon -mfloat-abi=hard" -DCMAKE_BUILD_TYPE=RelWithDebInfo; make `

and I copied the library to my place
> /home/akirayuki/lib
>
I ran it with the command line
Output 

> akirayuki@localhost:"$ LD_LIBRARY_PATH=/home/akira yuki/lib LIBGL FB=2 glxinfo 
LIBGL: Initialising gl4es 
LIBGL: v1.1.3 built on Mar 26 2020 02:45:35 
LIBGL: using framebuffer + fbo 
LIBGL: Using GLES 2.0 backend 
LIBGL: loaded: libGLESV2.so.2 
LIBGL: Hardware test disabled, nothing activated...
LIBGL: Targeting OpenGL 2.1 
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Not trying to batch small subsequent glDrawXXXX 
LIBGL: try to use VBO LIBGL: 91XMakeCurrent FBO workaround enabled 
LIBGL: Current folder is:/home/akirayuki
name of display: localhost:51
glxinfo: symbol lookup error: glxinfo: undefined symbol: glXChooseVisual 
akirayuki@localhost:"$
>
Here is information you may need to check out
![IMG_20200326_150848](https://user-images.githubusercontent.com/44525248/77627969-499de800-6f7a-11ea-8c3c-943b052ef21d.JPG)
![IMG_20200326_150733](https://user-images.githubusercontent.com/44525248/77628254-6803e380-6f7a-11ea-94a0-94a438033950.JPG)

I ran it on Debian 10 (buster) Armhf 
Thank

**Comment by ptitSeb** [comment]
Why are you building with `-DBCMHOST=1` (are you using a RPi with legacy EGL drivers?) and with `-DNOEGL=1` (you seems to have EGL running).
Also, with `-DNOX11=1` you will not have `glX...` X11 functions, so `glxinfo`, that needs them, will not run.

What is your hardware/OS here?

**Comment by AllPlatform** [comment]
i'm newbie
I use the device VIVO Y55 
>Qualcomm MSM8917 Snapdragon 425
Quad-core 1.4 GHz Cortex-A53
GPU Adreno 306

I'm running UserLAnd (https://github.com/CypherpunkArmory/UserLAnd/) which is like a chroot and inside is Debian 10 buster (armhf) filesystem where I installed gl4es

**Comment by ptitSeb** [comment]
Ok, so maybe try with the most regular way first (ODROID profile will do fine):
`cmake .. -DODROID=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo`
and see if it works.

**Comment by AllPlatform** [comment]
> in file included from /home/akirayuki/gl4es/include/EGL/egl.h:36,
                 from /home/akirayuki/gl4es/src/gl/loader.h:11,
                 from /home/akirayuki/gl4es/src/gl/blit.c:10:
/home/akirayuki/gl4es/include/EGL/eglplatform.h:89:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/GL.dir/build.make:76: src/CMakeFiles/GL.dir/gl/blit.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/GL.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

![Screenshot_20200326_184200](https://user-images.githubusercontent.com/44525248/77643438-f172e000-6f91-11ea-9a97-2404091c6b5d.png)

It not work ,please take a look

**Comment by ptitSeb** [comment]
you need x11 headers. Something like `sudo apt install libx11-dev` maybe?

**Comment by AllPlatform** [comment]
Thank you it work for me 
I get 50~60FPS
but I feel that it cannot use my GPU but only render with CPU

**Comment by ptitSeb** [comment]
your `eglinfo` earlier shows "llvm pipe", so yeah, that's software. I don't know UserLAnd, so I cannot say how (if it's possible) to have actual GLES driver used inside the chroot...

**Comment by seisdr** [comment]
Is your device rooted?

**Comment by AllPlatform** [comment]
Thanks for everything and I also laughed at myself

**Comment by AllPlatform** [comment]
Pls Help 
How can I get GL4ES to load the libEGL.so, libGLESv2.so library in another directory ?

**Comment by ptitSeb** [comment]
Use the environment variable `LIBGL_EGL=/path/to/libEGL.so` and `LIBGL_GLES=/path/to/libGLESv2.so`

**Comment by AllPlatform** [comment]
I use command
Method 1

>LD_LIBRARY_PATH=/home/akirayuki/lib LIBGL_EGL=home/akirayuki/android/libEGL.so glxgears

Output 

>LIBGL: Initialising gl4es
......
LIBGL: LIBGL_GLES override failed: /home/akirayuki/android/libEGL.so: can't open shared object: No such file or directory 
LIBGL: loaded:libEGL.so.1
LIBGL: Using GLES 2.0 backed
..... 

it works normally with mesa but it doesn't load my library i'm sure the libEGL.so library is located in 

> /home/akirayuki/android/libEGL.so

I use method 2

> export LIBGL_EGL=home/akirayuki/android/libEGL.so

>export LIBGL_GLES=/akirayuki/android/libGLESv2.so

>LD_LIBRARY_PATH=/home/akirayuki/lib glxgears 


Output
![IMG_20200329_095234](https://user-images.githubusercontent.com/44525248/77840235-3fb0fa80-71af-11ea-82a0-6f1cde8038dc.jpg)

I think it still hasn't loaded my 2 libraries Or is it already loading my library?
I should recompile again the gl4es library 
So where did I wrong? 
Sory i bad English

**Comment by ptitSeb** [comment]
If it doesn't "found" the library when pointing to it, that means the file is not with the correct architecture. You are using a armhf chroot, but your android is probably arm64, so library are not the architecture (plus, android libs on linux OS don't load correctly anyway).

Also, you need to override both EGL and GLESv2. don't override just one.

To see if lib is loaded, check the "Vendor" in LIBGL output....
