### ISSUE TITLE
GLU functions link error

### ISSUE THREAD

**Issue by liming0791** [ptitSeb/gl4es#16]
I use gl4es in **android ndk**, after **ndk-build** I got such linking errors:

> error: undefined reference to 'gluNewQuadric'
error: undefined reference to 'gluSphere'
error: undefined reference to 'gluDeleteQuadric'

Does gl4es support functions like **gluSphere()** ? Or did I got something wrong ?

**Comment by lubomyr** [comment]
try to use GLU library
https://github.com/pelya/commandergenius/tree/sdl_android/project/jni/glu

**Comment by ptitSeb** [comment]
Yep, exactly. Thoses functions are part of libGLU, a separate lib...
