### ISSUE TITLE
VBO does not work with VertexAttribPointer

### ISSUE THREAD

**Issue by mittorn** [ptitSeb/gl4es#161]
v->real_buffer is 0, so FPE just pushes buffer->data instead of vbo pointer
workaround that helped (but need test):
```
	if( v->buffer )
	{
		v->real_buffer = v->buffer->real_buffer;
		v->real_pointer = pointer;
	}
```
in the end of gl4es_glVertexAttribPointer
Maybe it need to be checked if it safe to use this format directly

**Comment by ptitSeb** [comment]
Thanks for the analysis and for the potential fix, I'll look into this soon.
