### ISSUE TITLE
OpenMW Shaders have wrong reflexions

### ISSUE THREAD

**Issue by ptitSeb** [ptitSeb/gl4es#165]
So i think it didnt solve this issue, same behavior still happening. I already found workaround for terrain and object shader (in glsl and small change in engine). Only that water reflection is broken now. Do you have any idea how to solve that? This is how it look (refraction need depth buffer, but reflection should work, and its working if object shader is disabled, but if object is rendered with shader, then that object have bad reflection in most cases)
https://youtu.be/vSZThnY9c3o

**Comment by Sisah2** [comment]
Do you have any idea whats wrong here?

**Comment by ptitSeb** [comment]
No idea. Do you have the source of the shader?

**Comment by Sisah2** [comment]
Sources are here
https://github.com/OpenMW/openmw/tree/master/files/shaders
Weird thing is that only object that use shaders have bad reflection, also mostly object that touch water or are slightly higher, causing it.

**Comment by ptitSeb** [comment]
I don't see anything wrong on a quick look at this.

A test should be done on a PC/Linux, with mesa and with gl4es, to check if the behaviour is the same.

**Comment by Sisah2** [comment]
So linux with gl es hardware? Cant do that sadly :(

**Comment by ptitSeb** [comment]
No, linux with GL hardware. GLES is include with most (all?) driver, so it's easy to compare GL vs gl4es

**Comment by Sisah2** [comment]
So i can confirm that this issue is even on my pc with gl4es, but this test was painfull. So many issues on my intel hd graphics.

**Comment by ptitSeb** [comment]
Ok, so the same shader gives a reflexion with y reversed on gl4es?!

**Comment by Sisah2** [comment]
Probably yes, with gl4es it looks the same as on android, with default libGL.so.1 it was working nicely with the same shaders on pc. I can make better video of it.

**Comment by ptitSeb** [comment]
Yes, maybe that's the case.

Can you do a quick test: in `src/gl/fpe.c` line 809, just before `fpe_ReleventState(...)` can you add
```
if (glstats->fpe_state->plane) printf("Use Plane within custom shader!\n");
```
and check if that printf trigger when there is water?

**Comment by Sisah2** [comment]
Yes, they are triggered.

**Comment by ptitSeb** [comment]
I didn't found a place were they trigger on my side, but hopefully that commit works and don't break anything else

**Comment by Sisah2** [comment]
With this commit performance is really bad, it didnt solved this issue and even some textures are missing. you can reproduce this bug with those setting
[Shaders]
force shaders = true
in
~/.config/openmw/openmw.cfg

**Comment by ptitSeb** [comment]
Ah ok, there are some bugs in my new shaders :(

**Comment by ptitSeb** [comment]
And I'm finaly able to reproduce some stuff on my Pandora (including the missing ground texture/shader)

**Comment by ptitSeb** [comment]
I have fixed the shader isse.
Not sure if it fixed the bad reflexion (I can't find a spot were I see case)

**Comment by Sisah2** [comment]
you can try type "coc ebonheart" then "tcl" to ingame console, then move on the stairs and you should see this error when looking on water.

**Comment by Sisah2** [comment]
Btw just found that those white lines on textures are caused by 88e8203, not by last two commits.

**Comment by ptitSeb** [comment]
What white lines? I didn't noticed any on your video, or did I miss something?

**Comment by Sisah2** [comment]
If you look carefuly there are some white lines on rocks in no far distance, after few soconds of that video, they disapear if i come closer.
Looks like this
https://www.photobox.co.uk/my/photo?album_id=5854358852&photo_id=502942497779

**Comment by ptitSeb** [comment]
I fixed the issue with the grass texture.

But the reflexion issue is still there.

**Comment by ptitSeb** [comment]
This push fixes the bad reflexion issue. I let you test before closing the ticket.

**Comment by Sisah2** [comment]
Yes it working fine now, even with refraction. Thank you :)
