### ISSUE TITLE
OpenMW shadows

### ISSUE THREAD

**Issue by Sisah2** [ptitSeb/gl4es#171]
in OpenMW shadows doesnt work (everything goes black if they are enabled), sadly i cant give you more info, i know only that its dependent on depth buffer which is a known limitation, so if there is no way to get them working just close this ticket. Shadows in openmw was added in 0.46 builds which is now in RC phase and stable will be released soon (so they are not in 0.45 stable). They can be enabled in settings.cfg with 
[Shadows]
enable shadows = false
Shadows related shaders are here
https://github.com/OpenMW/openmw/tree/master/files/shaders
And most shadows related code here
https://github.com/OpenMW/openmw/blob/master/components/sceneutil/mwshadowtechnique.cpp
There are two fragment shaders withou their vertex counterparts, but according to openmw devs they are not used, and if they are by other aplications, open scene graph generate default vertex shader for them.

**Comment by ptitSeb** [comment]
I have made a change in texture conversion. Maybe that helped depth textures.

My OpenMW local build is not 0.46. I have updated my git clone and will build latest version, but that will take time and will not be able to reproduce anything on my side until build is done and working...

**Comment by Sisah2** [comment]
Ok, that first commit didnt changed anything i think, compiling second one then i must do clean build which take me 2 hours (there are some shadows  related things, that are disbled in android port, because some object had red texture on itself). also if you compile openmw you must change 
uniform bool simpleWater = false;
to 
uniform bool simpleWater;
in object_fragment.glsl or shaders dont compile with gl4es.

**Comment by Sisah2** [comment]
This is what happen if shadows are enabled.
https://www.mediafire.com/view/y9068lcis7adxlb/Screenshot_20200517-113749_OMW_%28Debug%29.jpg/file
And this is what happening with refraction.
https://youtu.be/_bRjcI_bNLA
I also tried shadows on pc, here it look even more broken i think :D

**Comment by ptitSeb** [comment]
You mean on pc with gl4es?

**Comment by Sisah2** [comment]
Yes

**Comment by ptitSeb** [comment]
I took a look at the shaders: they use sampler2Dshadow and this is not supported on gl4es for now.

I have plan to try support that, but it's not done yet...

**Comment by Sisah2** [comment]
There is one merge request with soft shadows support, it look like he changed sampler2Dshadow to sampler2D and shadows working. I try that.
https://gitlab.com/OpenMW/openmw/-/merge_requests/193/diffs?commit_id=11fadd9be08f61a2c6f7a72c9f6701e68a4b16a6

**Comment by Sisah2** [comment]
Please can you help? For some reason this in shaders break compilation.
const vec2 poissonDisk[25] = vec2[](
    vec2(0.513658, -0.361747),
    vec2(0.7941055, -0.5156633),
    vec2(0.4015315, 0.00368995),
    vec2(0.2348373, -0.5646414),
    vec2(0.08148332, -0.1521704),
    vec2(0.9071004, -0.04301345),
    vec2(0.5765684, -0.7820904),
    vec2(0.02575831, -0.9248317),
    vec2(-0.4247141, -0.7601865),
    vec2(-0.1650984, -0.5609509),
    vec2(-0.00553054, 0.4322597),
    vec2(0.374622, 0.536724),
    vec2(0.629549, 0.3171313),
    vec2(-0.1453903, 0.8028749),
    vec2(0.1050673, 0.9782572),
    vec2(0.7705216, 0.6211317),
    vec2(-0.5209134, -0.2073833),
    vec2(-0.2157063, -0.05150497),
    vec2(-0.7314271, -0.4448851),
    vec2(-0.9658175, -0.08176702),
    vec2(-0.6456084, 0.08727718),
    vec2(0.4758473, 0.8578165),
    vec2(-0.4970213, 0.3748735),
    vec2(-0.79823, 0.4584326),
    vec2(-0.4652869, 0.7911729)
);
Need this array for those soft shadows. Any idea?

**Comment by ptitSeb** [comment]
And like that!
```
const vec2 poissonDisk[25] = {
{0.513658, -0.361747},
{0.7941055, -0.5156633},
{0.4015315, 0.00368995},
{0.2348373, -0.5646414},
{0.08148332, -0.1521704},
{0.9071004, -0.04301345},
{0.5765684, -0.7820904},
{0.02575831, -0.9248317},
{-0.4247141, -0.7601865},
{-0.1650984, -0.5609509},
{-0.00553054, 0.4322597},
{0.374622, 0.536724},
{0.629549, 0.3171313},
{-0.1453903, 0.8028749},
{0.1050673, 0.9782572},
{0.7705216, 0.6211317},
{-0.5209134, -0.2073833},
{-0.2157063, -0.05150497},
{-0.7314271, -0.4448851},
{-0.9658175, -0.08176702},
{-0.6456084, 0.08727718},
{0.4758473, 0.8578165},
{-0.4970213, 0.3748735},
{-0.79823, 0.4584326},
{-0.4652869, 0.791172}
};
```

**Comment by Sisah2** [comment]
It also dont compile :( i add it manually with wall of ifs.

**Comment by Sisah2** [comment]
So blackness is now gone, shader compile, but still no shadows. There is also shadows debug hud that can be enabled in settings.cfg. it have 3 windows that showing scene from three different angles (3 shadow maps). With gl4es that first window never show anything and the others flickering, like one frame there is scene in second window, another frame its in third window. On pc without gl4es it dont flicker and first window showing stuff too.

**Comment by AbduSharif** [comment]
You might not know this, but in OoenMW Android a part of shadows is commented out (to fix some issues when shadows were merged and they weren't working anyway, so whatever you do won't work unless you remove the patch added by xyzz.

**Comment by Sisah2** [comment]
I know (its probably not needed with latest gl4es, at least with es2 renderer). Btw replacing sampler2Dshadow with sampler2D should work, then change shadow2DProj() with 
float sampleShadow(sampler2D shadowMap, vec4 coords)
{
    vec3 coordsProj = coords.xyz/coords.w;
    return float(coordsProj.z <= texture2D(shadowMap, coordsProj.xy).r);
}
On pc without gl4es shadows work with this change, on pc with gl4es it cause crash.

**Comment by NielsGx** [comment]
Is this still being worked on?
Thanks for your amazing project btw!

**Comment by ptitSeb** [comment]
It is still worked (I mean gl4es as a whole, not ShadowSampler specificaly) on, but very slowly.

**Comment by Sisah2** [comment]
I wanna ask, there is extension called GL_EXT_shadow_samplers
Is it possible to enable it in pure glsl (before conversion) without editing gl4es?
Because if i add
#extension GL_EXT_shadow_samplers : require 
To shaders then i get errors that sampler2Dshadow is reserved and shadow2DProjEXT dont exist, which is i think the same as shadow2DProj on desktop opengl

**Comment by Sisah2** [comment]
Seems like using shadow sampler can be easily avoided, but there is big issue with 
gl_EyePlaneS/T/R/Q
They alway return vec4(0.0) and its needed to get right shadow map coordinates. Shadow map texture seems to work fine, any idea why this happening?

**Comment by Sisah2** [comment]
Closing this, as shadow sampler is not needed at all, problem is in texture coordinates.

**Comment by NielsGx** [comment]
Why close this ?

The issue is still there.
It's not what you thought it was, maybe, but still, "OpenMW shadows" have issues.


Thanks for your work Seb
