### ISSUE TITLE
XFCE xfwm4 Support

### ISSUE THREAD

**Issue by jgmdev** [ptitSeb/gl4es#172]
The XFCE compositor has basic glx support to implement vsync, looking at their code it seems that only few glx extensions are missing from gl4es to support xfwm4. I did a breakdown of the xfwm4 [compositor.c](https://github.com/xfce-mirror/xfwm4/blob/5f29827fd47e677bbefaae0cce67edfa00cd7e7f/src/compositor.c#L1132) requirements for it to work with glx:
```
------------------------------------------------------------------
GLX_DRAWABLE_TYPE
    GLX_PIXMAP_BIT
------------------------------------------------------------------

------------------------------------------------------------------
GLX_BIND_TO_TEXTURE_TARGETS_EXT
    GLX_TEXTURE_RECTANGLE_BIT_EXT
        GL_TEXTURE_RECTANGLE_ARB;
        GLX_TEXTURE_RECTANGLE_EXT;
            
    or

    GLX_TEXTURE_2D_BIT_EXT
        GL_TEXTURE_2D
        GLX_TEXTURE_2D_EXT
------------------------------------------------------------------

------------------------------------------------------------------
GLX_RED_SIZE < 8
------------------------------------------------------------------

------------------------------------------------------------------
GLX_BIND_TO_TEXTURE_RGBA_EXT,
    TRUE
    
    or
        
GLX_BIND_TO_TEXTURE_RGB_EXT,
    TRUE
------------------------------------------------------------------
```

Looking at the gl4es code it seems that GLX_PIXMAP_BIT should be easy to do since it seems that it already supports it but doesn't advertise it on:
```c
case GLX_DRAWABLE_TYPE:
        *value = GLX_WINDOW_BIT;
        break;
```
The other extensions I don't know how hard would be or if they are already supported, I'm not sure how they are used since my GL knowledge is null...

In any case besides games or pure 3d/2d applications it would be great to have at least one desktop compositor working with gl4es and the XFCE xfwm4 seems like a great fit to support for those that want desktop accelerated graphics using this project that brings support for desktop GL on these arm boards that only support EGL.

By the way I created images for the [Odroid N2](https://forum.odroid.com/viewtopic.php?f=179&t=38835) and [Odroid C4](https://forum.odroid.com/viewtopic.php?f=203&t=38897&sid=8fa88777556f1ad4b07885effc1b7ef3) with gl4es enabled globally by default with xfce and it is pretty stable :) I need to recreate them with newer gl4es with glmark2 fixes and the use of LIBGL_GL=30

**Comment by seisdr** [comment]
xfce4 ?

**Comment by jgmdev** [comment]
More information can be seen here: https://xfce.org/

**Comment by jgmdev** [comment]
After taking a deeper look and trying it for my self I think this is impossible with fbdev driver so I will close this
