### ISSUE TITLE
'remap_pixel()' function takes up to 20% running time on Android device

### ISSUE THREAD

**Issue by liming0791** [ptitSeb/gl4es#18]
While I successfully run gl4es on Android device, in the profile of my ndk-based APP, the cost of running time for the function 'remap_pixel()' reach up to 20% of the whole running time.

```
 Flat profile:
 
 Each sample counts as 0.01 seconds.
   %   cumulative   self              self     total           
  time   seconds   seconds    calls   s/call   s/call  name    
  25.93     24.19    24.19     3692     0.01     0.01  bool PTAMM::Bundle::Do_LM_Step<PTAMM::Tukey>(bool*)
  22.70     45.37    21.18                             remap_pixel
  10.78     55.43    10.06                             profCount
   5.90     60.93     5.50                             __gnu_mcount_nc
   2.92     63.65     2.72 32623260     0.00     0.00  PTAMM::Bundle::ProjectAndFindSquaredError(PTAMM::Meas&)
   2.43     65.92     2.27     3805     0.00     0.00  double PTAMM::Bundle::FindNewError<PTAMM::Tukey>()
```

The cost is too much, so what can I do to reduce or avoid it ?

**Comment by ptitSeb** [comment]
remap_pixel is the "slow path" for the pixel_convert function.
That function is used to convert one of the many Texture format supported by desktop OpenGL to one of the few supported by GLES.
Most of the most common format have a "fast path" coded in pixel_convert. What kind of texture are coverted here? (you can find out yourself by uncommenting the printf in pixel.c, line 666).

**Comment by ptitSeb** [comment]
@liming0791 : is this still an issue? I have done some changes lately that should have improved things.
