### ISSUE TITLE
OpenMW es2 fog

### ISSUE THREAD

**Issue by Sisah2** [ptitSeb/gl4es#188]
Hello, please can you look on this? If using gles2 renderer without shaders fog break at 50000 range, only strange white line remain. Its not happening with es1, or with shaders. Looks like this.
https://youtu.be/MqVDMXNAPao

**Comment by ptitSeb** [comment]
That's probably because the fogcoord in the generated shaders are "mediump". They should be pushed to "highp" I guess. You can try be altering `src/gl/fpe_shader.c` llines 338, 343-345, 845 and 847-849. And change all the "mediump" to "highp" also in 1327-1337.
So all fog calculation will be in highp then.

**Comment by Sisah2** [comment]
So increasing precision dont helped, but i added calculation as they are in openmw shaders and its fine now. so thank you again.

**Comment by Sisah2** [comment]
Which is.
Vertex shader:
varying float linearDepth;
gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
linearDepth = gl_Position.z;

Fragment shader:
varying float linearDepth;
float fogValue = clamp((linearDepth - gl_Fog.start) * gl_Fog.scale, 0.0, 1.0);
gl_FragData[0].xyz = mix(gl_FragData[0].xyz, gl_Fog.color.xyz, fogValue);

**Comment by Sisah2** [comment]
So i was wrong. With this formula fog dont disappear at 50000, but instead with increasing distance (starting at 50000) the fog loss his intensity and begin being more transparent, so culled terrain become visible :( in custom shaders this not happening. So can it be something with gl_Fog values?

**Comment by ptitSeb** [comment]
I'll try to have a look and get something that work.

**Comment by ptitSeb** [comment]
Ok, I tried something, and it seems to work fine on my side. Can you try?

**Comment by Sisah2** [comment]
On my side everything become white if distance is more than 50000 :(

**Comment by ptitSeb** [comment]
So, it did improved, but it's still not enough?

**Comment by Sisah2** [comment]
No i was wrong about that distance, it was always around 65520. now fog dont dissapear at that range, but everything become white (even close things) at exactly same spot.

**Comment by ptitSeb** [comment]
Yeah, I have reproduce the issue on my Pandora. And the commit I have pushed fixed it for me.

Question, in the LIBGL start, does it print "Extension GL_OES_fragment_precision_high  detected and used" or "high precision float in fragment shader available and used" ?
Because I noticed it seems to need "highp" precision, along with another change (both are pushed).

**Comment by Sisah2** [comment]
For some reason android dont give me those messages via adb logcat :( it print only few empty lines with "LIBGL:" prefix

**Comment by ptitSeb** [comment]
ah.  mmm. I have pushed a change list to try fix that.

**Comment by Sisah2** [comment]
Sorry i had to rebuild whole project, now i got some nice messages.
06-12 20:18:28.339 23387 23387 I LIBGL   : Initialising gl4es
06-12 20:18:28.339 23387 23387 I LIBGL   : v1.1.3 built on Jun 12 2020 18:59:14
06-12 20:18:28.339 23387 23387 I LIBGL   : Using GLES 2.0 backend
06-12 20:18:28.341 23387 23387 I LIBGL   : loaded: libGLESv2.so
06-12 20:18:28.342 23387 23387 I LIBGL   : loaded: libEGL.so
06-12 20:18:28.342 23387 23387 I LIBGL   : Using GLES 2.0 backend
06-12 20:18:28.343 23387 23387 I LIBGL   : Hardware Full NPOT detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_blend_minmax  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : FBO are in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : PointSprite are in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : CubeMap are in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : BlendColor is in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : Blend Substract is in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : Blend Function and Equation Separation is in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : Texture Mirrored Repeat is in core, and so used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_mapbuffer  detected
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_element_index_uint  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_packed_depth_stencil  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_depth24  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_rgb8_rgba8  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_texture_format_BGRA8888  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_depth_texture  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_texture_stencil8  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_texture_rg  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_color_buffer_float  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_color_buffer_half_float  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : high precision float in fragment shader available and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Max vertex attrib: 16
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_OES_standard_derivatives  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Max texture size: 8192
06-12 20:18:28.343 23387 23387 I LIBGL   : Max Varying Vector: 15
06-12 20:18:28.343 23387 23387 I LIBGL   : Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
06-12 20:18:28.343 23387 23387 I LIBGL   : Extension GL_EXT_texture_filter_anisotropic  detected and used
06-12 20:18:28.343 23387 23387 I LIBGL   : Max Anisotropic filtering: 16
06-12 20:18:28.343 23387 23387 I LIBGL   : Max Color Attachments: 1 / Draw buffers: 1
06-12 20:18:28.343 23387 23387 I LIBGL   : Hardware vendor is ARM
06-12 20:18:28.345 23387 23387 I LIBGL   : GLSL 300 es supported
06-12 20:18:28.345 23387 23387 I LIBGL   : GLSL 310 es supported and used
06-12 20:18:28.345 23387 23387 I LIBGL   : sRGB surface supported
06-12 20:18:28.347 23387 23387 I LIBGL   : EGLImage to Texture2D supported
06-12 20:18:28.347 23387 23387 I LIBGL   : EGLImage to RenderBuffer supported
06-12 20:18:28.347 23387 23387 I LIBGL   : Targeting OpenGL 2.1
06-12 20:18:28.347 23387 23387 I LIBGL   : NPOT texture handled in hardware
06-12 20:18:28.347 23387 23387 I LIBGL   : Not trying to batch small subsequent glDrawXXXX
06-12 20:18:28.347 23387 23387 I LIBGL   : try to use VBO
06-12 20:18:28.347 23387 23387 I LIBGL   : glXMakeCurrent FBO workaround enabled
06-12 20:18:28.347 23387 23387 I LIBGL   : FBO workaround for using binded texture enabled
06-12 20:18:28.347 23387 23387 I LIBGL   : glX Will try to recycle EGL Surface
06-12 20:18:28.347 23387 23387 I LIBGL   : Current folder is:/

**Comment by ptitSeb** [comment]
Ok, so it seem you do have highp in Fragment shader, but still have wrong fog.

As a test, in `src/gl/fpe_shader.c` line 1376, can you change
```
sprintf(buff, "%s float FogF = clamp((gl_Fog.end - fog_c) / (gl_Fog.end - gl_Fog.start), 0., 1.);\n", fogp);
```
to
```
sprintf(buff, "%s float FogF = (gl_Fog.end-clamp(fog_c, gl_Fog.start, gl_Fog.end)) / (gl_Fog.end - gl_Fog.start);", fogp);
```

**Comment by Sisah2** [comment]
Its the same result, everything become fully foged.

**Comment by ptitSeb** [comment]
Ok, I'm seen that I needed more "highp"... Is it better now?

**Comment by Sisah2** [comment]
Oh yes it seems to be good now (hopefully :D) can i have one unrelated question before closing? In openmw there is nice sunglare effect around sun, it need arb_occlusionquery extension. Your readme says that occlusion query is implemented but with 0 bit precision. Is it possible to put some precision to it? Or its some limitation as with depth buffer.
But anyway thank you very much, another bug stomped.

**Comment by ptitSeb** [comment]
Yeah, it's hardware limit here. Cannot had any precision unless the hardware support it (which I don't check at all for now, and I'm not even sure there is an OpenGLES2 extension for that).

**Comment by Sisah2** [comment]
Ok, so thank you and closing this.
