### ISSUE TITLE
Compiling error on rpi4

### ISSUE THREAD

**Issue by tacgnol3** [ptitSeb/gl4es#193]
Hello/Salut PtitSeb,

I installed a fresh install of raspi os 

downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2020-05-28/2020-05-27-raspios-buster-armhf.zip

I installed cmake usint apt-get.
Installed box86 without issue, and can play papers please. All good so far.

Now, I'm trying to install gl4es (seems to be necessary for shovel knight .. start okay regularly, but if my dualshock3 is in sync over bluetooth (using the sixaxis driver from retropie) the game either crash if it was started, or won't start at all), using the odroid profile as specified in compile.md

here's my output error :

[  8%] Building C object src/CMakeFiles/GL.dir/gl/blit.c.o
In file included from /home/pi/gl4es/include/EGL/egl.h:36,
                 from /home/pi/gl4es/src/gl/loader.h:11,
                 from /home/pi/gl4es/src/gl/blit.c:10:
/home/pi/gl4es/include/EGL/eglplatform.h:89:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/GL.dir/build.make:128: src/CMakeFiles/GL.dir/gl/blit.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/GL.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Any idea what seems to be wrong ?

forgot to add, I downloaded the files using this specific command :
git clone --depth=1 https://github.com/ptitSeb/gl4es.git

**Comment by ptitSeb** [comment]
You need X11 header. Try
`sudo apt install libx11-dev`

That should help.

**Comment by tacgnol3** [comment]
it definitely did !

now I have another error when trying to install : 

pi@raspberrypi:~/gl4es/build $ sudo make install
[  1%] Building C object src/CMakeFiles/GL.dir/gl/build_info.c.o
[  2%] Linking C shared library ../../lib/libGL.so.1
[100%] Built target GL
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/lib/gl4es/libGL.so.1
-- Set runtime path of "/usr/lib/gl4es/libGL.so.1" to ""
CMake Error at src/cmake_install.cmake:80 (file):
  file INSTALL cannot find "/home/pi/gl4es/src/include".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


make: *** [Makefile:106: install] Error 1

**Comment by ptitSeb** [comment]
Ok. The install is very new.

I have pushed something, I hope it fixed the issue.

**Comment by tacgnol3** [comment]
pi@raspberrypi:~/gl4es/build $ sudo make install
[  1%] Building C object src/CMakeFiles/GL.dir/gl/build_info.c.o
[  2%] Linking C shared library ../../lib/libGL.so.1
[100%] Built target GL
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/lib/gl4es/libGL.so.1
-- Set runtime path of "/usr/lib/gl4es/libGL.so.1" to ""
-- Installing: /usr/include/gl4es/gl4esinit.h
-- Installing: /usr/include/gl4es/gl4eshint.h



Look's good now, thanks !
