### ISSUE TITLE
GL_ARB_framebuffer_object cause Minecraft to use GL30 API and crashed by unsupported method

### ISSUE THREAD

**Issue by khanhduytran0** [ptitSeb/gl4es#194]
I'm trying to run Minecraft 1.7.2 using bash script on Ubuntu PRoot in Android with your GL4ES and another library that stream OpenGL ES over network. Minecraft 1.5.2 and below works. Old GL4ES version without `GL_ARB_framebuffer_object` so Minecraft 1.7.2 works, but when game detect that for available, it crashed by calling `org.lwjgl.opengl.ARBFramebufferObject.glGenFramebuffers()` which is not available because that method call to `GL30` API.

```
Stack: [0x0000007fb461b000,0x0000007fb481b000],  sp=0x0000007fb4818d00,  free space=2039k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL30C.nglGenFramebuffers(IJ)V+0
j  org.lwjgl.opengl.GL30C.glGenFramebuffers()I+20
j  org.lwjgl.opengl.ARBFramebufferObject.glGenFramebuffers()I+0
j  dgl.q()I+48
j  dgf.b(IIZ)V+29
j  dgf.d(IIZ)V+26
j  dgf.a(IIZ)V+25
j  dgf.<init>(IIZZ)V+72
j  dlx.<init>(Ldus;)V+872
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1250
v  ~StubRoutines::call_stub
```

It may be disabled by modify GL4ES or LWJGL but I like to keep original. Can you add an environment variable to disable exposuring `GL_ARB_framebuffer_object`? Thanks in advance.

**Comment by khanhduytran0** [comment]
Looks like I found a solution. Closing.

**Comment by ptitSeb** [comment]
And what was that solution?

**Comment by khanhduytran0** [comment]
I think maybe filtering out FBO on GLES but was not tested. Then tried manually comment out `GL_ARB/EXT_framebuffer_object` then attempt to run on another version: Minecraft 1.16-rc1 (updated manually to LWJGL 3.2.3). Looks like Minecraft versions with Blaze3D require framebuffer.
```
java.lang.IllegalStateException: Could not initialize framebuffer support.
	at dgl.a(SourceFile:289)
	at com.mojang.blaze3d.platform.GLX._init(SourceFile:113)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1043)
	at dlx.<init>(SourceFile:466)
	at net.minecraft.client.main.Main.main(SourceFile:177)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dgl.a(SourceFile:289)
	at com.mojang.blaze3d.platform.GLX._init(SourceFile:113)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(SourceFile:1043)
	at dlx.<init>(SourceFile:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
```

**Comment by khanhduytran0** [comment]
Or putting `fboEnable: false` to options.txt worked.
