### ISSUE TITLE
GL4ES with gl-streaming render a blank screen

### ISSUE THREAD

**Issue by khanhduytran0** [ptitSeb/gl4es#196]
Hi ptitSeb,
I'm trying to bring OpenGL hardware acceleration to Linux running inside Android using [my fork of gl-streaming](https://github.com/khanhduytran0/android-gl-streaming) , it send OpenGL ES command to a server Android app, render to a native surface then send back return value (if it's `glGetString`, or client-modify method, etc...). When I try `es2_info, es2gears and es2tri`, it works well with some small tricks, but when I'm trying to run `glxgears` or any OpenGL application, the server print a lot of lines below and screen show only `glClear()` color.
```
I/Adreno-ES20( 2904): <validate_vertex_attrib_state:61>: validate_vertex_attrib_state: No vertex attrib is enabled in a draw call!
```

So I added little debug to gl-streaming and saw that `es2tri` has some `glEnable/DisableVertexAttribArray` commands:
```
Uniform modelviewProjection at 0
Attrib pos at 0
Attrib color at 1
gls debug: executing command glViewport
gls debug: executing command glUniformMatrix4fv
gls debug: executing command glClear
gls debug: executing command glEnableVertexAttribArray
gls debug: executing command glEnableVertexAttribArray
gls debug: executing command glGenBuffers
gls debug: executing command glBindBuffer
gls debug: executing command glBufferData
gls debug: executing command glVertexAttribPointer
gls debug: executing command glGenBuffers
gls debug: executing command glBindBuffer
gls debug: executing command glBufferData
gls debug: executing command glVertexAttribPointer
gls debug: executing command glBindBuffer
gls debug: executing command glDrawArrays
gls debug: executing command glDisableVertexAttribArray
gls debug: executing command glDisableVertexAttribArray
```

Then I tried to run `glxdemo` with GL4ES but didn't see any `glEnable/DisableVertexAttribArray` commands.
[glxdemo_gl4es_glstreaming.txt](https://github.com/ptitSeb/gl4es/files/4840636/glxdemo_gl4es_glstreaming.txt)

What am I doing wrong? Is the wrong at gl-streaming or GL4ES?

**Comment by ptitSeb** [comment]
I don't know, but the log seems really inclomplete. There is just the initialization part of gl4es and not much more.
(gl4es create a PBuffer first to gather some capabilities).
Maybe gl4es use an unsupported command?

Also, you can run with `LIBGL_NOTEST=1` to disable the initial test.

**Comment by khanhduytran0** [comment]
> I don't know, but the log seems really inclomplete. There is just the initialization part of gl4es and not much more.
That's all from `glxdemo` which draw only 1 frame.

> (gl4es create a PBuffer first to gather some capabilities).
Oh, but current all `eglCreate*Surface` were stub on `eglGetCurrentSurface(EGL_DRAW)` since on sever already initialized. Before I tried to stream any EGL commands but without success.

> Maybe gl4es use an unsupported command?
I almost filled up any unsupported commands, so if another one unsupported then a segfault will be.

> Also, you can run with `LIBGL_NOTEST=1` to disable the initial test.
Hardware test works fine, so I don't have reason to disable. Even disabled, `No vertex attrib is enabled in a draw call` still there.

**Comment by khanhduytran0** [comment]
> I don't know, but the log seems really inclomplete. There is just the initialization part of gl4es and not much more.

Oh, I checked and it save only 4kb...

**Comment by khanhduytran0** [comment]
So it's the full log of glxdemo
[glxdemo_gl4es_glstreaming.txt](https://github.com/ptitSeb/gl4es/files/4841345/glxdemo_gl4es_glstreaming.txt)

**Comment by ptitSeb** [comment]
I noticed many type of call mising. There is indeed the `glEnableVertexArray(...)` that is missing (note that on glxgear, I don't expect to see any `glDisableVertexArray(...)`, just a couple of Enabled at start and that's it).
Also, I see a `glBindBuffer(...)` but no `glBufferData(...)` wich is strange.
Most of the rendering loop occur in `src/gl/fpe.c` so what you can do is uncomment line 16 of this file, to see what is happening on gl4es side...

**Comment by khanhduytran0** [comment]
I did and got it in `glxdemo`
```
Redraw event
fpe_glEnableClientState(GL_VERTEX_ARRAY)
glstate->vao->vertexattrib[0].enabled (was 0) = 1 (hardware=0)
fpe_glVertexPointer(4, GL_FLOAT, 80, 0x30000420b0)
fpe_glDisableClientState(GL_NORMAL_ARRAY)
glstate->vao->vertexattrib[2].enabled (was 0) = 0 (hardware=0)
fpe_glDisableClientState(GL_COLOR_ARRAY)
glstate->vao->vertexattrib[3].enabled (was 0) = 0 (hardware=0)
fpe_glDisableClientState(GL_SECONDARY_COLOR_ARRAY)
glstate->vao->vertexattrib[4].enabled (was 0) = 0 (hardware=0)
fpe_glDisableClientState(GL_FOG_COORD_ARRAY)
glstate->vao->vertexattrib[5].enabled (was 0) = 0 (hardware=0)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[8].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE1)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[9].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE2)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[10].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE3)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[11].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE4)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[12].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE5)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[13].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE6)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[14].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE7)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[15].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE8)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[16].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE9)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[17].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE10)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[18].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE11)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[19].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE12)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[20].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE13)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[21].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE14)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[22].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE15)
fpe_glDisableClientState(GL_TEXTURE_COORD_ARRAY)
glstate->vao->vertexattrib[23].enabled (was 0) = 0 (hardware=0)
fpe_glClientActiveTexture(GL_TEXTURE0)
fpe_glDrawArrays(GL_TRIANGLE_FAN, 0, 4), program=0, instanceID=0
Creating FPE shader : 4(0x3000053930)
Use FPE program 4
```

**Comment by khanhduytran0** [comment]
Looks like `vertexattrib[*].enabled` were false at all.

**Comment by ptitSeb** [comment]
Initially, all vertex attrib array are disabled yes, so that's fine
and the 1st one (vertex) get enabled
now, last log is "Use FPE program 4", wich is line 1095 of `src/gl/fpe.c`
After that, I expect uniforms to be setup (because at least MVP matrix needs to be updated), but there is no log from fpe.c about that (you can uncomment line 9 of `src/gl/uniform.c` to have more logs) and then the VA should be enabled. There is a log only on changing state... 
But, maybe the issue is with `glGetActiveAttrib(...)` (and also `glGetUniformLocation(...)`). This function is used to get size / type of VertexAtribute of any shader. If the information returnned if wrong, and, for example, the size of the va is 0, then the VA will not be setup.
Try to uncomment line 14 of `src/gl/program.c` to see what's going on there.

**Comment by khanhduytran0** [comment]
Now I got
```
// As log before
// ..............
fpe_glClientActiveTexture(GL_TEXTURE0)
fpe_glDrawArrays(GL_TRIANGLE_FAN, 0, 4), program=0, instanceID=0
glCreateProgram()
glAttachShader(1, 2)
glAttachShader(1, 3)
glLinkProgram(1)
glBindAttribLocation(1, 0, "_gl4es_Vertex")
glBindAttribLocation(1, 3, "_gl4es_Color")
 link status = 1
glGetProgramiv(1, GL_LINK_STATUS, 0x7ff380ce7c)
Creating FPE shader : 1(0x3000053930)
Use FPE program 1
```

**Comment by ptitSeb** [comment]
Yeah, well, look at the `fill_program(..)` function in `src/gl/program` starting line 531. You'll see it's supposed to log the uniforms found line 594 and the VA found line 650. But there is nothing in your log. So either `glGetProgramiv(...)` with `GL_ACTIVE_UNIFORMS` return 0 or `glGetActiveUniform(...)` return a size of 0 (and same for attributes). I would say arror is on gl_stream side.

**Comment by khanhduytran0** [comment]
That's weird, `glEnable/DisableVertexAttribArray` never get called or address located, even I try to undefine but GL4ES still run, while `es2*` print error:
```
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/root/gl4es
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
^C
root@localhost:~/gl4es# es2gears
es2gears: symbol lookup error: es2gears: undefined symbol: glDisableVertexAttribArray
root@localhost:~/gl4es#
```

**Comment by khanhduytran0** [comment]
In gl-streaming side there's no EGL/GLES error, only `debug log line`: `No vertex attrib is enabled in a draw call`.

**Comment by ptitSeb** [comment]
ges dynamically look for all GL/EGL functions. Even if you undefined them, you will not see any linker error. But you will see, in runtime, some Warning that the function is NULL and then it will crash

But, as I stated on my last comment, the functions are not called because `glGetProgramiv(...)` and `glGetActiveUniform(...)` are probably not working.

Did you printf the values returned by thoses function?

**Comment by ptitSeb** [comment]
Anyway, the error is in gl-streaming side, there is nothing more I can do for now.

**Comment by khanhduytran0** [comment]
Thanks for help! Now I located the error and GL4ES started
```
fpe_glClientActiveTexture(GL_TEXTURE0)
fpe_glDrawArrays(GL_TRIANGLE_FAN, 0, 4), program=0, instanceID=0
Creating FPE shader : 7(0x3000053930)
Use FPE program 7
VertexAttribArray[0]:Enable, divisor=0
glVertexAttribPointer(0, 4, GL_FLOAT, 0, 80, 0x30000420b0)
Segmentation fault
```

**Comment by khanhduytran0** [comment]
I have some more problem with gl-streaming side so it segfault.

**Comment by ptitSeb** [comment]
Ok, that's a start.

Segfault are usualy easier to debug then bad behavior. At least, gdb gives a good view of what is going on most of the time...

Good luck with gl-streaming debugging.

**Comment by khanhduytran0** [comment]
Thanks, it's a bit easier because I'm working with another developer.
