### ISSUE TITLE
How to compile android version

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/gl4es#202]
I installed android ndk but I don't know how to compile

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
(you know you don't need to tag me, I receive a notification even without that)

there is an `Android.mk` that can be use with `ndk-build`. Most of the time, you use gl4es associated with some other sources, like SDL2.
You can check on the net for example, there are a few project using gl4es on adnoird (like EternalLand or Gish)

**Comment by pmtip** [comment]
![Screenshot_20200721_200138_com tencent mobileqq](https://user-images.githubusercontent.com/67471944/88052582-056bce80-cb8d-11ea-8617-8fcf36546e24.jpg)

**Comment by pmtip** [comment]
![Screenshot_20200721_200401](https://user-images.githubusercontent.com/67471944/88052758-55e32c00-cb8d-11ea-8377-adfcf0819372.jpg)

**Comment by pmtip** [comment]
what should I do

**Comment by ptitSeb** [comment]
Current "Android" version of gl4es is not disegned to generate a libGL.so.1, because that woul dmake no sense on Android, there is no X11 to use glX and create a context.
Look for example https://github.com/EXL/Gish this project to see how it's used.

Now, if you building libGL to use on linux chroot on Android, it's the regular "Linux" version that you should use.

**Comment by pmtip** [comment]
I want to use it in android chroot environment.
How should I compile?

**Comment by ptitSeb** [comment]
use the cmake, and just build it. (something like `cmake && make`)

**Comment by pmtip** [comment]
What parameters does cmake need.

**Comment by pmtip** [comment]
What parameters does cmake need?

**Comment by ptitSeb** [comment]
I you are building on the device itself, none.
If you cross compile, you nee to define the crosschain tool (but I can't help you there)

**Comment by pmtip** [comment]
Ok

**Comment by pmtip** [comment]
How should I make Android chroot opengl use GPU?

**Comment by ptitSeb** [comment]
I'm pretty sure I have already asnwsered that question, on another ticket.

**Comment by pmtip** [comment]
I know, but can you tell me more?

**Comment by pmtip** [comment]
I did not understand.

**Comment by pmtip** [comment]
I compiled and installed GL4ES and then what should I do?

**Comment by pmtip** [comment]
gl4es works, how to make it use GPU?

**Comment by pmtip** [comment]
@ptitSeb "LIBGL: Hardware Full NPOT detected and used"
gl4es outputs this.
Is the GPU used?

**Comment by ptitSeb** [comment]
No, not really.

Look at "LIBGL: Hardware vendor is XXXX": what is that XXXX

**Comment by pmtip** [comment]
LIBGL: Hardware vendor is VMware.

**Comment by pmtip** [comment]
GPU is not used.

**Comment by pmtip** [comment]
@ptitSeb what should i do.

**Comment by ptitSeb** [comment]
I don't know. It depends on the method you used to get your chroot. And I have no experience it that. You should ask the provider of the linux chroot method you use.

**Comment by pmtip** [comment]
I used gl4es of mcinabox and mounted /system.
GPU is used!

**Comment by pmtip** [comment]
How do I compile gl4es like this.

**Comment by pmtip** [comment]
@ptitSeb

**Comment by pmtip** [comment]
Use the NDK?

**Comment by ptitSeb** [comment]
Yes, I assume they used NDK to build it. But that will not gives you GPU aceleration inside your linux chroot.

**Comment by pmtip** [comment]
Can I compile this on Android?

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
This what? gl4es? "on Android"? you mean "on your phone directly" or "for Android"?

**Comment by pmtip** [comment]
I want to compile gl4es "for android" on Android.

**Comment by ptitSeb** [comment]
You can't (at least to my knowledge). You need a Windows or Linux system with the NDK installed.
Maybe you can do that in your linux chroot, but I don't know.

**Comment by pmtip** [comment]
OK.

**Comment by pmtip** [comment]
linux cannot use android gl4es.
I should compile gl4es for linux.
I should let gl4es load /vendor/lib/egl/libGLES_mali.so.
But I don’t know what to do.

**Comment by pmtip** [comment]
@ptitSeb Can you help me?

**Comment by pmtip** [comment]
/vendor/lib/egl/libGLES_mali.so
This is the EGL/GLES driver for Android.

**Comment by pmtip** [comment]
Android gl4es loads this file.

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
Again, ask the one that provide the linux chroot. I cannot help you here, and I already told you all that (that you need EGL/GLES driver in linux/chroot).

**Comment by pmtip** [comment]
OK.

**Comment by pmtip** [comment]
@ptitSeb Can box86 use Android gl4es?

**Comment by pmtip** [comment]
Can I set BOX86_LIBGL to gl4es for Android?

**Comment by ptitSeb** [comment]
No, Android lib don't work on Linux.
