### ISSUE TITLE
Minecraft (mcinabox) rendering error

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#212]
![Screenshot_20201006-180605_MCinaBox](https://user-images.githubusercontent.com/63176856/95262256-2645d680-0802-11eb-82ab-175a5b9f03d5.jpg)
Hi...gl4es is giving no texture on game ..how to fix that ?i tried the newest one 1.1.4 and fix the textures but fps still 0..thanks for a possible answer

**Comment by ptitSeb** [comment]
So you are on Android I suppose. and from your test:
Version 1.1.2 is fast but missing texture
Version 1.1.4 have texture but super slow

What about current sources (so 1.1.5), did you try it?

**Comment by pedrosouzabrasil** [comment]
I will ask the @dev (mcinabox)and try an updated release of gl4es (the latest)and i will give you a feedback if the game works properly..(will not close the issue yet)..

**Comment by ptitSeb** [comment]
Ok, no problem

**Comment by artdeell** [comment]
Also, it seems that Mali GPUs got better performance, but broken geometry

**Comment by ptitSeb** [comment]
> Also, it seems that Mali GPUs got better performance, but broken geometry

Better performance comparing what to what?

**Comment by artdeell** [comment]
Mali GPUs to Adreno GPUs

**Comment by ptitSeb** [comment]
> Mali GPUs to Adreno GPUs

Ah ok. And that with gl4es v1.1.2 ?

**Comment by artdeell** [comment]
With 1.1.4

ср, 7 окт. 2020 г., 13:06 ptitSeb <notifications@github.com>:

**Comment by ptitSeb** [comment]
Ok. Waiting result with current v1.1.5

**Comment by artdeell** [comment]
We can't test with PojavLauncher, but maybe Mcinabox can...

ср, 7 окт. 2020 г., 13:42 ptitSeb <notifications@github.com>:

**Comment by ptitSeb** [comment]
Why?

**Comment by artdeell** [comment]
Some issues when setting context.
I think @khanhduytran0 will explain better.

ср, 7 окт. 2020 г., 13:47 ptitSeb <notifications@github.com>:

**Comment by khanhduytran0** [comment]
It likely has something wrong in making current...
```
S/jrelog  (22082): FATAL ERROR in native method: Thread[Thread-0,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
S/jrelog  (22082): 	at org.lwjgl.opengl.GL11.glShadeModel(Native Method)
S/jrelog  (22082): 	at com.mojang.rubydung.RubyDung.init(RubyDung.java:73)
S/jrelog  (22082): 	at com.mojang.rubydung.RubyDung.run(RubyDung.java:104)
S/jrelog  (22082): 	at java.lang.Thread.run(java.base@9-internal/Unknown Source)
```

**Comment by ptitSeb** [comment]
Ah ok,
Are you building an Android gl4es or a Linux version?

**Comment by artdeell** [comment]
Android ofcourse

ср, 7 окт. 2020 г., 14:21 ptitSeb <notifications@github.com>:

**Comment by khanhduytran0** [comment]
I'm built use Android target.

**Comment by ptitSeb** [comment]
You build using cmake or Android.mk?

**Comment by ptitSeb** [comment]
And if you build the 1.1.4 you don't have the "context" issue? It's only when building 1.1.5 that lwjgl complains about context creation?

**Comment by khanhduytran0** [comment]
> You build using cmake or Android.mk?

I built use Android.mk with modifies to fix #144 and enable GLES2.

**Comment by ptitSeb** [comment]
Ok. I did the Android.mk change, so it should build by iteslf now.

Do you now how to `git bisect`? Does by any chance commit b1fc44a55413a9571721e79b6e8b321cda70c99e broke the "context" ?

**Comment by khanhduytran0** [comment]
Hm... Is there any way to enable double buffer?

**Comment by ptitSeb** [comment]
That is what that commit change (from double buffer by default to single buffer, as this seems to be actual default on X11), but maybe that was a bad idea

**Comment by artdeell** [comment]
It seems that performance on Adrenos improved when LIBGL_MIPMAP was set to 3

ср, 7 окт. 2020 г., 15:48 ptitSeb <notifications@github.com>:

**Comment by pedrosouzabrasil** [comment]
Maybe snap 865 has some shortcomings. We try to fix this by ignoring mipmap in new version.(cosinemath)

**Comment by pedrosouzabrasil** [comment]
I will close the issue by now...problem solved..thanks só much ptitseb and devs

**Comment by ptitSeb** [comment]
How was it solved?

**Comment by artdeell** [comment]
Env var: LIBGL_MIPMAP=3

чт, 8 окт. 2020 г., 08:51 ptitSeb <notifications@github.com>:

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201007-190243_Samsung Internet.jpg](https://user-images.githubusercontent.com/63176856/95420056-34364d00-0911-11eb-9539-2c85609f99e4.jpg)

![Screenshot_20201007-135308_Samsung Internet.jpg](https://user-images.githubusercontent.com/63176856/95420085-3d271e80-0911-11eb-83a8-e9c19d7e6575.jpg)

![Screenshot_20201007-190238_Samsung Internet.jpg](https://user-images.githubusercontent.com/63176856/95420100-44e6c300-0911-11eb-8282-bd607c715e73.jpg)


New code line added...possible  fix ..today a new release (mcinabox)we will see..

**Comment by ptitSeb** [comment]
Ok :)

**Comment by pedrosouzabrasil** [comment]
Would you like to join your discord (when free time )?@ptitSeb

**Comment by pedrosouzabrasil** [comment]
https://discord.gg/nZ6tt5

**Comment by ptitSeb** [comment]
I can, but don't expect me to be very active (I'm not a minecraft player)

**Comment by pedrosouzabrasil** [comment]
Ok..really apreciate.

**Comment by khanhduytran0** [comment]
Ah I also modified to build shared lib... but not yet commented out `-DSTATIC_LIB`...

**Comment by khanhduytran0** [comment]
Now trying build latest commit with commented out `-DSTATIC_LIB` (as I using shared lib)

**Comment by khanhduytran0** [comment]
So it works, but I think caused by static lib flag when build shared lib...

**Comment by pedrosouzabrasil** [comment]
@ptitSeb so sorry to disturb you again ..but how can i add this code to make tha app work(setenv("LIBGL_MIPMAP","3")?i tried and crash

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201007-125309_HTML Viewer.jpg](https://user-images.githubusercontent.com/63176856/95641442-b7be7e00-0a78-11eb-894b-76d26834c266.jpg)

**Comment by ptitSeb** [comment]
I don't see why it would crash with a setenv.
If you prefer, you can directly force that value in gl4es: is `src/gl/init.c` line 246 (so there https://github.com/ptitSeb/gl4es/blob/master/src/gl/init.c#L246 )  line. change
```
globals4es.automipmap=ReturnEnvVarInt("LIBGL_MIPMAP");
````
to
```
globals4es.automipmap=3
```
And it will be forced to 3 without reading the env var (so no more parametrable).

But I suspect your crash is something else.
In Android.mk, did you leaved line 94 commented (that one `#LOCAL_CFLAGS += -DNO_INIT_CONSTRUCTOR`) or not?
If it's uncommented, you need to call `initialize_gl4es();` from gl4es before any GL function. If it's commented then fine, the function should be called automatically.

**Comment by pedrosouzabrasil** [comment]
Thanls...Nice to learn ..i will test here

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201010-125142_MCinaBox.jpg](https://user-images.githubusercontent.com/63176856/95662850-4a5e2c00-0b10-11eb-890a-baa3eceb44da.jpg)



It workssss!thanks @ptitSeb !closed issue
