### ISSUE TITLE
Color rendering is wrong

### ISSUE THREAD

**Issue by davie504** [ptitSeb/gl4es#213]
Hello,textures in half-life 2 don't render normally via GL4ES.
But with Regal its okay.I think it has to do with srgb textures. Any ideas to fix this? ;)
Regal
![B5t2Q4OVYnQ](https://user-images.githubusercontent.com/59658354/95385917-499e7d80-08f7-11eb-9868-5a7a1207908e.jpg)
GL4ES
![0BmbAZlVtAA](https://user-images.githubusercontent.com/59658354/95385991-60dd6b00-08f7-11eb-8e84-1757e6178f6a.jpg)

**Comment by davie504** [comment]
And there is a trouble : static models are dark

**Comment by ptitSeb** [comment]
HalfLife 2 is open source now (as you run with regal)?

Some texture don't seem to tranfert quite well. As a first test, can you try to run with `LIBGL_MIPMAP=3`? Also, anything from gl4es in the logcat?

**Comment by davie504** [comment]
It's reverse-engenired how port by nvidia.

**Comment by davie504** [comment]
I will check this later.

**Comment by nillerusr** [comment]
> HalfLife 2 is open source now (as you run with regal)?
> 
> Some texture don't seem to tranfert quite well. As a first test, can you try to run with `LIBGL_MIPMAP=3`? Also, anything from gl4es in the logcat?

LIBGL_MIPMAP=3 dont help. Source also using GL_FRAMEBUFFER_SRGB and require non-linear colorspace( i think ). Lightmap textures are dark. The same problem occurs when using srgb conversion in gltools. 
logcat: https://0x0.st/i0Uc.xz

**Comment by nillerusr** [comment]
logcat: https://0x0.st/i0U9.xz

**Comment by nillerusr** [comment]
`
10-08 01:11:02.242 10559 11104 I LIBGL   : glTexImage2D on target=GL_TEXTURE_2D with unpack_row_length(0), size(32,32) and skip(0,0), format(internal)=GL_BGRA(GL_RGBA8), type=GL_UNSIGNED_INT_8_8_8_8_REV, data=0xc0720000, level=0 (mipmap_need=0, mipmap_auto=0, base_level=-1, max_level=0) => texture=8 (streamed=0), glstate->list.compiling=0
10-08 01:11:02.242 10559 11104 I LIBGL   : realize_bound(0, GL_TEXTURE_2D), glsate->actual_tex2d[0]=8 / 8
10-08 01:11:02.242 10559 11104 I LIBGL   : LIBGL: glGetError(): GL_INVALID_OPERATION
`

**Comment by nillerusr** [comment]
https://www.youtube.com/watch?v=S03rZnFC3Qo&t=47s

**Comment by ptitSeb** [comment]
In the logcat, I see those line in the initialization phase:
```
0-08 01:10:59.553 10559 11104 V EGLWRAP : gl4es_GetProcAddress(eglGetCurrentDisplay) = 0x0
10-08 01:10:59.553 10559 11104 I SRCENGINE: Could not find required OpenGL entry point 'eglGetCurrentDisplay'! Either your video card is unsupported, or your OpenGL driver needs to be updated.
10-08 01:10:59.553 10559 11104 I LIBGL   : glGetProcAddress("eglQueryString")
10-08 01:10:59.553 10559 11104 I LIBGL   : NULL
10-08 01:10:59.553 10559 11104 I STDERR  : Could not find required OpenGL entry point 'eglQueryString'!
10-08 01:10:59.553 10559 11104 I LIBGL   : glGetString(0x1F02)
10-08 01:10:59.554 10559 11104 V EGLWRAP : gl4es_GetProcAddress(glFramebufferRenderbuffer) = 0xc72d5add
10-08 01:10:59.554 10559 11104 I LIBGL   : 0xc72b5021 (gl4es_glBindMultiTexture)
10-08 01:10:59.554 10559 11104 V EGLWRAP : gl4es_GetProcAddress(glBindMultiTextureEXT) = 0xc72b5021
10-08 01:10:59.555 10559 11104 I LIBGL   : NULL
10-08 01:10:59.555 10559 11104 V EGLWRAP : gl4es_GetProcAddress(glGenSamplers) = 0x0
10-08 01:10:59.555 10559 11104 I SRCENGINE: Could not find required OpenGL entry point 'glGenSamplers'! Either your video card is unsupported, or your OpenGL driver needs to be updated.
10-08 01:10:59.555 10559 11104 I STDERR  : Could not find required OpenGL entry point 'glGenSamplers'!
```
the eglXXX call could be wrapped I guess. The glGenSamplers is an OpenGL 3.0 function. It's on my TODO for some time now. Not having samplers handled can be an issue here I guess.

And wow, it's a full DEBUG enabled build of gl4es... So much log, it will need some time to analyse.

**Comment by ptitSeb** [comment]
> https://www.youtube.com/watch?v=S03rZnFC3Qo&t=47s

This is running gl4es or regal or something else?

**Comment by nillerusr** [comment]
> > https://www.youtube.com/watch?v=S03rZnFC3Qo&t=47s
> 
> This is running gl4es or regal or something else?

GL4ES

**Comment by nillerusr** [comment]
glGenSamplers also OpenGLES 3 function, hm. Maybe i will make later my wrapper based on gl4es that supports gles3

**Comment by ptitSeb** [comment]
> glGenSamplers also OpenGLES 3 function, hm. Maybe i will make later my wrapper based on gl4es that supports gles3

It is planed, but not for now, it's for later...

**Comment by nillerusr** [comment]
> > glGenSamplers also OpenGLES 3 function, hm. Maybe i will make later my wrapper based on gl4es that supports gles3
> 
> It is planed, but not for now, it's for later...

well but i will replace funtions that emulated. I have a new issue but maybe i will fix it myself

**Comment by nillerusr** [comment]
I/SRCENGINE: Required OpenGL extension "GL_EXT_texture_sRGB_decode" is not supported. Please update your OpenGL driver.

**Comment by ptitSeb** [comment]
Ok, I'll check to see what I can do. It's a pretty big extension, I need to study it.

**Comment by nillerusr** [comment]
I am try to add srgb support. But i will get some problems. 
I think you dont should look at my code,because of shitcode :)

https://youtu.be/jsDO-AWbKpA

**Comment by nillerusr** [comment]
logs:32843:10-11 12:59:19.645 10177 11076 I LIBGL   : glEnable(0x8DB9), glstate->list.pending=0
logs:32881:10-11 12:59:19.646 10177 11076 I LIBGL   : glDisable(0x8DB9), glstate->list.pending=0
GL_FRAMEBUFFER_SRGB \= . I dont know what to do with that

**Comment by ptitSeb** [comment]
Yep, that will be something tricky here.

Do you know if you hardware driver support sRGB?

**Comment by nillerusr** [comment]
Yeap my hardware driver support srgb and i checked this in extensions list

**Comment by nillerusr** [comment]
Well shit, i think my problem in glBlitFramebuffer.

**Comment by ptitSeb** [comment]
Well glBlitFramebuffer is emulated by gl4es, so if there is some color correction to do there, it can be done with a custom shader.

**Comment by nillerusr** [comment]
Well, i fix it. I will send pull request tommorow.

**Comment by seisdr** [comment]
there's a trouble  😂

**Comment by RusJJ** [comment]
What's the reason of that?

**Comment by RusJJ** [comment]
@ptitSeb, hey! Take a look on it and implement it more carefully, please!

https://github.com/nillerusr/gl4es/commit/3f2ab70902182e0712b328ef1b3c5c22286f8e65

**Comment by ptitSeb** [comment]
Looks interresting.

I haven't started working on sRGB yet. I wanted to have a test app on my side (Portal/linux), but it still need more OpenGL 3.x function or extension to even start...
Without a test app, it's difficult to do anything.
Maybe I have to find another test app...

**Comment by RusJJ** [comment]
I hope you can fix this... (i mean normal maps/bump textures). Also freakin particles are weirdo too. nillerusr said he got two types of shader: one with weirdo fire, BUT NOT LIKE THE CURRENT. And the second that is the current (broken).

**Comment by RusJJ** [comment]
Hi again @ptitSeb! Also forgot... Looks like GL4ES cannot handle compressed DXT1 textures (i think so) so they looks so bad. As you can see at the upper screenshot.

**Comment by RusJJ** [comment]
Im here. Again. Still not enough precision?

![image](https://user-images.githubusercontent.com/8864329/97800962-4d999300-1c4a-11eb-8f29-46e84b9b70a2.png)

**Comment by ptitSeb** [comment]
mmm, how `-1.55009923e-6` get transformed to `-0.0720847`? There seems to be a bug in the float reading then.

**Comment by RusJJ** [comment]
lol idk. Upper in the same shader there's the same value (but without mantissa, just a 0.0 .... 155 - converted very carefully).

**Comment by RusJJ** [comment]
Lost in your conversion code xD
Will you try to update it today? Or it needs more time to debug?

**Comment by RusJJ** [comment]
Still waiting for sRGB implementation since latest updates broke our sRGB hack.

**Comment by ptitSeb** [comment]
Yes, last updated broke a few things arround texture handling. I need to fix those regressions. It's on my todo.

**Comment by RusJJ** [comment]
Btw is sRGB in yours ToDo too? Because our lil hack is working, but textures are bright a bit. But while using maps that are compiled with HDR enabled, brightness like on PC. Only on Adreno. Mali/PowerVR cannot see the difference/

**Comment by ptitSeb** [comment]
Yes, it is too. Not the same priorirty as the regressions, but I want to add support for that in short term. (just, for now, box86 is on higher priority than gl4es, so things are quite slow on that side for now. I'm trying to push a stable version of box86 soon and than focus a bit on gl4es)

**Comment by davie504** [comment]
@ptitSeb still waiting for srgb implementation...for almost 6 mouth..

**Comment by ptitSeb** [comment]
Yes, I know, I'm not really working on gl4es for now. Still on my todo, but still foccused on other things for now. Hopefully I'll get some time soon (this week or next week) to work on gl4es.

**Comment by RusJJ** [comment]
GG.

**Comment by davie504** [comment]
Okay,we dont use gl4es anymore
