### ISSUE TITLE
issue possible not related to gl4es..

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#214]
hi @ptitSeb ..its me again im very glad you help us fixing the issue before.. you are very good at programming so maybe can you help me fix this other issue on mcinabox(aarch64 runtime crash when try enter to game )...

[crash-2020-10-10_21.50.47-client.txt](https://github.com/ptitSeb/gl4es/files/5360322/crash-2020-10-10_21.50.47-client.txt)

**Comment by ptitSeb** [comment]
It seems you are missing abuild of libglfw.so, you probably have armhf built but not aarch64 (you may also want to use different folder for each architecture).

**Comment by pedrosouzabrasil** [comment]
Thanks so much(your knowledge is amazing)

**Comment by khanhduytran0** [comment]
```
java.lang.UnsatisfiedLinkError: Failed to dynamically load library: /data/user/0/com.aof.mcinabox/files/runtime/boat/libglfw.so(error = dlopen failed: library "/data/user/0/com.aof.mcinabox/files/runtime/boat/libglfw.so" needed or dlopened by "(unknown)" is not accessible for the namespace "(anonymous)")
```
It's about Android does not allow to load that GLFW library as namespace restricted (but it should be happend on loading private system lib only).
