### ISSUE TITLE
Trouble with particles in half-life 2

### ISSUE THREAD

**Issue by nillerusr** [ptitSeb/gl4es#215]
https://youtu.be/WA9vsa-1G2Y
I really dont know what to do with that. mittorn says that it can be issue of glUniform

**Comment by ptitSeb** [comment]
Wow, that's odd. No idea where that could come from. glUniform why not.

**Comment by nillerusr** [comment]
I found which shader is the problem. Before ConvertShader the shader looks like this: https://pastebin.com/XqFkzsU0, after https://pastebin.com/urbBusPR Can the absence of gl_ClipVertex affect particles?

**Comment by ptitSeb** [comment]
Yes, that can indeed.
I need to think on how to handle this one, it was planned to have ClipVertex modified in the vertex shader, but current handling is in the fragment shader, so that still could work.

**Comment by nillerusr** [comment]
What? I dont see.
https://github.com/ptitSeb/gl4es/blob/master/src/gl/shaderconv.c#L1078
I see that gl_ClipVertex dont used.

**Comment by ptitSeb** [comment]
Yes, but https://github.com/ptitSeb/gl4es/blob/master/src/gl/shaderconv.c#L1080 I have the code, "just" need some copypasta...

**Comment by nillerusr** [comment]
idk. I dont see ClipVertex in the fragment shader. I found only this https://github.com/ptitSeb/gl4es/blob/master/src/gl/shaderconv.c#L1078 .

**Comment by ptitSeb** [comment]
It needs some copypasta from this code: https://github.com/ptitSeb/gl4es/blob/master/src/gl/fpe_shader.c#L1393

**Comment by nillerusr** [comment]
Well, but idk how to do this. I am dont understand how it should work

**Comment by ptitSeb** [comment]
I'll do it, later. I need to implement sRGB FrameBuffer first.

**Comment by abasgames** [comment]
> I'll do it, later. I need to implement sRGB FrameBuffer first.

does the srgb implemented yet or no ?

**Comment by ptitSeb** [comment]
Not yet.

**Comment by RusJJ** [comment]
What we need to do with Vertex shader?

**Comment by RusJJ** [comment]
![Uploading Screenshot_2020-10-29-10-58-15-157_com.nvidia.valvesoftware.halflife2.jpg…]()
Well...

**Comment by ptitSeb** [comment]
can you check the generated shaders, to see if when vertex shader have a `gl_ClipVertex` the associated fragment shader also have it (it will be named `gl4es_ClipVertex` in transformed shader).

**Comment by RusJJ** [comment]
Sadly i cannot do that on Android 10 because of some changes to GLES libraries (so GLTools that can extract shaders) isn't working. Added Log instead, seems like gl_ClipVertex detected.

**Comment by RusJJ** [comment]
Also add an #ifdef ANDROID in the next commit for log.c/LogFPrintf/fprintf please? For me it isn't compiling currently.

**Comment by RusJJ** [comment]
Hmm. Looks like that the latest version wasn't compiled. Recompiled. Seems like there's some error in a changed shader so it's not compiling -> everything is black.

**Comment by ptitSeb** [comment]
Mmm yeah, that ClipPlane function is not correct.. I need more wrapping and more changes...

**Comment by nillerusr** [comment]
Well, i will upload compiling log, wait

**Comment by nillerusr** [comment]
Ahahahaha you forgot ";"

**Comment by nillerusr** [comment]
Expected token ';' , found highp )))

**Comment by ptitSeb** [comment]
well, yes, but no, it's more complicated than that.

**Comment by RusJJ** [comment]
Fixed shader compilation. But as you know it didn't help. Waiting! Thanks for your replies!

**Comment by ptitSeb** [comment]
yeah, because `gl_ClipVertex` needs to be tested against ClipPlanes, but only thoses activated. I need to check how to carefully used existing mecanism here.

**Comment by nillerusr** [comment]
shit

**Comment by nillerusr** [comment]
it not helps to fix particles /=

**Comment by nillerusr** [comment]
most likely a bug elsewhere

**Comment by ptitSeb** [comment]
check that the code in `fpe_shader.c` line 1434 is used, just to be sure.

**Comment by ptitSeb** [comment]
In `fpe_CustomShader(...)` in line 424 of `fpe.c`

**Comment by ptitSeb** [comment]
I should be called if the program use `glEnable(GL_CLIP_PLANEX)`, with X from 0 to 5. I never enabled for than 6 planes. If you can check if it tries to enable other planes maybe (the `glEnable` funciton is defined in `enable.c`)?

**Comment by RusJJ** [comment]
Kinda hard to figure it out. What i need to do?

**Comment by ptitSeb** [comment]
Add a log if it tries to enable GL_PLANE7,8,9 or 10?

**Comment by RusJJ** [comment]
> Add a log if it tries to enable GL_PLANE7,8,9 or 10?

Oki doki, give me some time!

**Comment by RusJJ** [comment]
It looks like that clip_plane0-5 isn't enabled at all.
![Screenshot_2020-10-29-18-17-15-836_com nvidia valvesoftware halflife2](https://user-images.githubusercontent.com/8864329/97593780-11302200-1a13-11eb-9a5b-d2bc43af4210.jpg)
![IMG_20201029_181229](https://user-images.githubusercontent.com/8864329/97593812-17be9980-1a13-11eb-8ba7-f99ce6f177bd.jpg)

**Comment by ptitSeb** [comment]
can you do something like
`if(cap>=GL_CLIP_PLANE0 && cap<=(GL_CLIP_PLANE0+15) LogPrintf("glEnable(%s)\n", PrintEnum(cap));`
And also add a log in `planes.c`, on `gl4es_glClipPlanef(...)` function.

**Comment by RusJJ** [comment]
There it is!
![Screenshot_2020-10-29-18-41-59-918_com nolanlawson logcat](https://user-images.githubusercontent.com/8864329/97597195-9f59d780-1a16-11eb-891e-20b0e6cf28e3.jpg)
![Screenshot_2020-10-29-18-42-52-240_com nvidia valvesoftware halflife2](https://user-images.githubusercontent.com/8864329/97597202-a1bc3180-1a16-11eb-8509-1c852176085d.jpg)

**Comment by RusJJ** [comment]
ClipPlane was used 2 more times on menu loading finishing. There's no more glEnable(GL_CLIP_PLANEx) or any glClipPlanef anymore.

**Comment by ptitSeb** [comment]
I reread OpenGL specs to see how gl_ClipVertex should be handled. I added something, should work better now.

**Comment by RusJJ** [comment]
I'll take a look a bit later. Thanks!

**Comment by RusJJ** [comment]
Sad, not fixed. Aww... Maybe there's something else?
![Screenshot_2020-10-29-20-00-22-114_com nvidia valvesoftware halflife2](https://user-images.githubusercontent.com/8864329/97607081-94587480-1a21-11eb-96f4-332d298b8f03.jpg)

**Comment by ptitSeb** [comment]
Yeah, that's probably something else.

**Comment by RusJJ** [comment]
Fire is Y-cutted (also fire particle renders inside of "this" without any glitches). But there's some weirdo horizontal lines... What can it be, lol?

**Comment by ptitSeb** [comment]
It would be much more simple to analyse with a GL capture of some kind... Tools like PVRTrace will not work neither?

**Comment by RusJJ** [comment]
Thanks for the hint, i'll try to use it sometime

**Comment by RusJJ** [comment]
![image](https://user-images.githubusercontent.com/8864329/97804387-952b1980-1c60-11eb-96f6-70c675f5e43b.png)
Okay, there's really conversion problem.

**Comment by RusJJ** [comment]
Uploading PR will be so slow, so:
https://github.com/nillerusr/gl4es/blob/7976ec2b25503f0b96804f182446497ad27ffd92/src/gl/preproc.c#L226
Change to: fnb *= powf(10.0f, expsign*nb);

@ptitSeb

**Comment by nillerusr** [comment]
Well, it helped. Issue can be closed after pull request accept
