### ISSUE TITLE
SDL2 alpha problem?

### ISSUE THREAD

**Issue by MagaTailor** [ptitSeb/gl4es#22]
Hi,

I've just found an interesting issue, trying out [nimgame2's](https://github.com/Vladar4/nimgame2) demo [No. 1](https://github.com/Vladar4/nimgame2/tree/master/demos/demo1). 

In short, SDL2/GLES (or MESA OpenGL, minus fps) looks like this:
![gles](https://cloud.githubusercontent.com/assets/12054457/23818272/01d30dee-05fa-11e7-881f-dc1d98d7b21c.jpg)

whereas SDL2/OpenGL + gl4es like this:
![gl](https://cloud.githubusercontent.com/assets/12054457/23818286/26d7b608-05fa-11e7-8976-0bb29881f57a.jpg)

I was running @16 bpp and there should probably be no difference between the two scenarios. (what about performance-wise?)

I suspect it's not going to be necessary for you to dabble in nim to get to the bottom of the issue but, just in case, here's the [nim distro tarball](https://www.dropbox.com/s/qawa6kenvj3djk4/nim-latest-armhf.tar.xz?dl=0) I'm using on my Odroid.

**Comment by ptitSeb** [comment]
That's a strange issue, and yeah, nim and so on, that will be tricky to debbug.
I assume you don't use any particular command line?
Can you try with `LIBGL_BEGINEND=0` just in case ?

**Comment by MagaTailor** [comment]
Nope, didn't help.

Nim works everywhere a C compiler does, so after cloning, getting to the demo binary requires just two commands `nimble install` and then `nim c -d:release demo1.nim` (depends on SDL2_gfx library)

**Comment by MagaTailor** [comment]
Or even quicker, you can use a VM and just run the binary inside it.

[demo1.zip](https://github.com/ptitSeb/gl4es/files/835703/demo1.zip)

**Comment by ptitSeb** [comment]
It's ok, I have built nim, nimble and the demo1 (I had some issue because libc from the Pandora is old and doesn't support execvpe, but I built a workaround).
I still need to build SDL2_gfx and then I'll debug that issue.

**Comment by MagaTailor** [comment]
Great, thanks for taking the trouble!

**Comment by ptitSeb** [comment]
Ok, I tested ... and it's working on my side.

Maybe it's an issue with some advanced Blend function used, as if I remember correctly, some glBlendXXX function are not available on some odroid models.

**Comment by MagaTailor** [comment]
How can we find out which? It would be logical to always build `gl4es` without it.

**Comment by ptitSeb** [comment]
I have done an analysis.

It seems to use `glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA)`
but I'm not sure where this is used (SDL2 probably?)
The function is an extension on GLES 1.1 and DesktopGL 1.5 and should not be exposed if the GLES hardware doesn't have it.
You can check at start what LIBGL is giving as info, on my side I have:
```
LIBGL: Initialising gl4es
LIBGL: v0.9.5 built on Feb 26 2017 10:41:29
LIBGL: framebuffer output enabled
LIBGL:loaded: libGLES_CM.so
LIBGL:loaded: libEGL.so
LIBGL: Extension GL_OES_blend_subtract detected and used
LIBGL: Extension GL_OES_blend_func_separate detected and used
LIBGL: Extension GL_OES_blend_equation_separate detected and used
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_texture_cube_map detected and used
LIBGL: Max texture size: 2048
LIBGL: Texture Units: 4, Max lights: 8
```
Important line here is `LIBGL: Extension GL_OES_blend_func_separate detected and used`

**Comment by ptitSeb** [comment]
Ok, SDL2 has hardcoded use of that function.
In SDL_render_gl.c, around line 1102 you will see
```
static void
GL_SetBlendMode(GL_RenderData * data, int blendMode)
{
    if (blendMode != data->current.blendMode) {
        switch (blendMode) {
        case SDL_BLENDMODE_NONE:
            data->glDisable(GL_BLEND);
            break;
        case SDL_BLENDMODE_BLEND:
            data->glEnable(GL_BLEND);
            data->glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);
            break;
        case SDL_BLENDMODE_ADD:
            data->glEnable(GL_BLEND);
            data->glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE, GL_ZERO, GL_ONE);
            break;
        case SDL_BLENDMODE_MOD:
            data->glEnable(GL_BLEND);
            data->glBlendFuncSeparate(GL_ZERO, GL_SRC_COLOR, GL_ZERO, GL_ONE);
            break;
        }
        data->current.blendMode = blendMode;
    }
}
```

**Comment by MagaTailor** [comment]
Right, and mine doesn't have it:

````
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_cube_map detected and used
LIBGL: Max texture size: 4096
LIBGL: Texture Units: 8, Max lights: 8
LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5
````

**Comment by ptitSeb** [comment]
The GLES 1.1 part of SDL has some fallback version of the blend function, using glBlendFunc that is supported. I can hardcode that fallback in gl4es in case the extension is not supported.

**Comment by MagaTailor** [comment]
That explains why the GLES backend of SDL2 seemed to work fine here.

**Comment by ptitSeb** [comment]
GLES2 has this function in core. Issue is only with GLES1.1

**Comment by ptitSeb** [comment]
@MagaTailor can you try with 7a73d86aa7616bbce84954bb2f38754e9ddb81f6 , it should fix the issue.

**Comment by MagaTailor** [comment]
Indeed, it has! Thank you very much.

**Comment by MagaTailor** [comment]
Not related to the patch, but I'm getting huge memory usage spikes leading to minute long pauses on this 1GB system that happen exclusively during SDL2/OpenGL execution of the demo. 

I'll have to investigate if it's related to gl4es in any way. Didn't notice previously cause I was closing the window almost immediately.

**Comment by MagaTailor** [comment]
@ptitSeb Does any of the following look familiar to you? 

Memory usage starts growing after switching to a different virtual desktop where there's chromium (probably any X app) running. After switching back memory usage goes back down.

So it could be related to the X server not repainting the screen. Strange that SDL2/GLES backend copes fine with this scenario.

**Comment by ptitSeb** [comment]
No, this doesn't ring a bell. But I guess there are some glX function I miss maybe (that SDL2 emulate with egl with dealing with GLES backend)? No idea what thoses functions can be.

**Comment by MagaTailor** [comment]
OK, thanks. 

BTW, demo 11 doesn't start for me:
`could not import: SDL_CreateRGBSurfaceWithFormat`

Might be related to the 16bpp ufo bug in some way. The game (SDL 1.2) still crashes on start-up.

**Comment by MagaTailor** [comment]
Oops, forgot to check if MESA was ok. It doesn't work either, sorry! GLES does work though :)
