### ISSUE TITLE
float accuracy is too low in shaders

### ISSUE THREAD

**Issue by nillerusr** [ptitSeb/gl4es#228]
As a result, alyx looks like this.
![bruh](https://user-images.githubusercontent.com/42746659/96373712-f0e0a780-1176-11eb-99f8-a6cbdc460b74.png)

**Comment by nillerusr** [comment]
i changed here https://github.com/ptitSeb/gl4es/blob/master/src/gl/preproc.c#L234 %f to %10.10f and its solved problem. bionic libc is a piece of shit

**Comment by ptitSeb** [comment]
Oh, ok. I can add a `ifdef ANDROID` then to force some more decimal? (default should be 6 decimals)

**Comment by nillerusr** [comment]
I have 6 decimals on android. But its not enough

**Comment by nillerusr** [comment]
Maybe %e should be used?

**Comment by ptitSeb** [comment]
did you tried? or `%#e`?

**Comment by nillerusr** [comment]
Yep , it works with `%#e
![Screenshot_20201019-172404](https://user-images.githubusercontent.com/42746659/96464162-2b5a4b00-1230-11eb-856a-5059beefe6e3.jpg)
`
