### ISSUE TITLE
add support for glBlendEquationEXT

### ISSUE THREAD

**Issue by AaronRays468** [ptitSeb/gl4es#23]
this glBlendEquationEXT is requried by many games and apps.

**Comment by ptitSeb** [comment]
Done, whith 8fa6140ab75b875ceab865c9a5a63b0b6f948378

**Comment by AaronRays468** [comment]
When i am compiling.I get into this error:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at src/CMakeLists.txt:98 (add_library):
  Cannot find source file:

    gl/blend.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: GL
CMake Error: Cannot determine link language for target "GL".
-- Generating done
-- Build files have been written to: /home/pi/gl4es
Scanning dependencies of target GL
make[3]: *** No rule to make target 'src/CMakeFiles/GL.dir/build'.  Stop.
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/GL.dir/all' failed
make[2]: *** [src/CMakeFiles/GL.dir/all] Error 2
CMakeFiles/Makefile2:97: recipe for target 'src/CMakeFiles/GL.dir/rule' failed
make[1]: *** [src/CMakeFiles/GL.dir/rule] Error 2
Makefile:118: recipe for target 'GL' failed
make: *** [GL] Error 2

**Comment by ptitSeb** [comment]
Ooops.
Has always, I have forgoted to push the new files...

It's fixed with 0e38b5a8e3c035eeae0f226450504728b8020cdb
