### ISSUE TITLE
Typo on if condition?

### ISSUE THREAD

**Issue by Iscle** [ptitSeb/gl4es#232]
I've noticed, while compiling, that the compiler threw some warnings about some if conditions. 

One of them was the following: 
https://github.com/ptitSeb/gl4es/blob/6fc1bd1bbf61823277afd68f18b82164aae07be3/src/gl/gl4es.h#L111

Shouldn't this be == instead of =? Right now, the condition always evaluates to "GL_NO_ERROR", which is 0, so that if case is never true!

**Comment by Iscle** [comment]
> I've noticed, while compiling, that the compiler threw some warnings about some if conditions.
> 
> One of them was the following:
> https://github.com/ptitSeb/gl4es/blob/6fc1bd1bbf61823277afd68f18b82164aae07be3/src/gl/gl4es.h#L111
> 
> Shouldn't this be == instead of =? Right now, the condition always evaluates to "GL_NO_ERROR", which is 0, so that if case is never true!

**Comment by ptitSeb** [comment]
Yes you are right! Need to change that.

**Comment by Iscle** [comment]
Just made a pull request :)
