### ISSUE TITLE
Is support for glEnableVertexAttribArray missing ?

### ISSUE THREAD

**Issue by sviscapi** [ptitSeb/gl4es#24]
Hi ptitSeb :)

I tried to run some OpenGL application on the Pandora through your gl4es wrapper (v.0.9.5), but it failed with the following error message:

agp lookup(glEnableVertexAttribArray) failed, missing req. symbol.
Aborted

Is it something you could fix in a future version ?

Cheers, Magic Sam from the Open Pandora community

**Comment by ptitSeb** [comment]
glEnableVertexAttribArray is part of OpenGL 2.x specs. It will eventually be supported (or at least the symbol will be define), but not before gl4es v1.x

**Comment by sviscapi** [comment]
Hi,

Ok thanks, I thought glEnableVertexAttribArray was part of OpenGL 1.x specs, sorry about that.

Cheers, Magic Sam

**Comment by ptitSeb** [comment]
No problem Magic Sam.

Some support will come eventually :)
