### ISSUE TITLE
Reduced texture resolution by half in half-life 2

### ISSUE THREAD

**Issue by davie504** [ptitSeb/gl4es#244]
hi, this problem is very obvious.Each texture has a lower resolution than the PC version with the same quality options.
For example,this is original VTF of pistol.
![pistol](https://user-images.githubusercontent.com/59658354/98237018-4db0d000-1f75-11eb-9fbf-e2e5d241db89.png)
It has 256x resolution.
![Tex_0038_0](https://user-images.githubusercontent.com/59658354/98237132-7b961480-1f75-11eb-8c61-b28a0c38a72c.png)
This is pulled from memory thanks to NinjaRipper from DX9. It also has 256x resolution.
![b292](https://user-images.githubusercontent.com/59658354/98237316-c6179100-1f75-11eb-9042-9c6f12b76912.png)
And this,ripped from gl4es version,and it has 128x resolution.
How to solve this problem?

**Comment by ptitSeb** [comment]
Are you sure this is gl4es fault?

gl4es has the ability to reduce texture resolution on the flight, but it's controled by the `LIBGL_SHRINK` ev. var., and by default, no shrinking is done, even on s3tc compressed textures.

Also, be aware that gl4es may have to build mipmap textures, so a 128x128 version might be computed if the 256x256 version is uploaded (depending on some other texture parameters)...

**Comment by davie504** [comment]
LIBGL_SHRINK is zero...

**Comment by davie504** [comment]
and LIBGL_MIPMAP=3 doesnt help with it...

**Comment by davie504** [comment]
I'm not sure,but I think that this happens with compressed dxt1 textures, now I'll run a couple of tests and write here

**Comment by RusJJ** [comment]
Need to make some tests with Regal version (on Tegra). Watching vids of Chapter 3, starting danger sign is literally GOOD QUALITY.

**Comment by RusJJ** [comment]
Guess where's Regal/GL4ES? XD
This is the same device, so...
![Screenshot_20201105-154327_Half-Life_2](https://user-images.githubusercontent.com/8864329/98243032-670a4a00-1f7e-11eb-8c1e-c51f971d1b16.png)
![Screenshot_20201105-153927_Source_Engine](https://user-images.githubusercontent.com/8864329/98243040-696ca400-1f7e-11eb-883c-6053b345caff.png)

**Comment by ptitSeb** [comment]
Again, not sure what the issue is, but gl4es will not degrade texture for nothing. Maybe the textures are declared with some specific GL_TEXTURE_MAX_LEVEL or GL_TEXTURE_BASE_LEVEL ? I can only see something like that to force the use of some lower res mipmap...

**Comment by RusJJ** [comment]
Every texture is /2 sized. 512x512 -> 256x256. Fonts (generated, every char goes to the image handle), models, GUI, sprites. Everything is halfsized.
Again, while using Regal its ok, that only happens on GL4ES. Logged glCompressedTexImage2D <- size already halfsized. What can it be?

**Comment by RusJJ** [comment]
You're right! MipMaps disabled completely -> At the right side.
![image](https://user-images.githubusercontent.com/8864329/98257252-81e5ba00-1f90-11eb-9bd8-c4dfb2e14c8e.png)
So what can it be?

**Comment by RusJJ** [comment]
We were blind, sorry for an issue. Our mistake.

**Comment by ptitSeb** [comment]
Ah, ok. So no issue there?

**Comment by davie504** [comment]
yup
