### ISSUE TITLE
Some itens in minecraft are rendering white...

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#245]
![Screenshot_20201107-192101_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/98452624-e1c69700-212f-11eb-9648-66b3788cd95b.jpg)
Hi pittseb..i am playing minecraft on pojavlauncher (minecraft Java on Android.. )and some itens are white..how to fix..?is related to gl4es?hope you are well(im using latest gl4es 1.1.5)
![Screenshot_20201107-191815_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/98452645-0fabdb80-2130-11eb-934d-2e82d6e69e9c.jpg)

**Comment by ptitSeb** [comment]
I don't know. Did you tried with `LIBGL_MIPMAP=3` already (or maybe it's be default?). Is there some error in the logcat?

**Comment by khanhduytran0** [comment]
Yeah, `LIBGL_MIPMAP=3` is already set. Logcat is being obtained by @artdeell.

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201108-114443_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/63176856/98468163-f51d4500-21b7-11eb-8cdb-cf742a072c9d.jpg)![Screenshot_20201108-114436_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/63176856/98468166-f8b0cc00-21b7-11eb-94d7-8cfa871289a0.jpg)

**Comment by pedrosouzabrasil** [comment]
Also clouds are rendering with lines inside them

**Comment by pedrosouzabrasil** [comment]
Any ideas @ptitSeb ?it is really related to gl4es?

**Comment by ptitSeb** [comment]
Maybe it is, but I'm unsure. I need reference picture also (I'm not a minecraft player), and the logcat. I was thinking of maybe some wrong shader? but without logcat or something, it's difficult to say.

**Comment by pedrosouzabrasil** [comment]
Ok ..thanks..maybe in future this bug will be fixed.

**Comment by pedrosouzabrasil** [comment]
I am trying to put the log here but without sucess...(zip is not working..)..i will send you a link here to mediafire so you can check if help.

**Comment by pedrosouzabrasil** [comment]
http://www.mediafire.com/file/vw2i5himrcz2s64/logs.zip/file

**Comment by ptitSeb** [comment]
I only see this:
[code]
[22:49:26] [main/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[/code]
In the catlog that seems suspicious. Not sure wich version of lwjgl it's expected vs what version it have, and if it can explains the issue, but I don't see anything else suspicious in the log...

**Comment by pedrosouzabrasil** [comment]
Thanks so much!for your time and patience!

**Comment by artdeell** [comment]
I think the whole glColor processing has some issues in gl4es. At first, I can say, if there are leafs nearby banners (Minecraft), banner's color on the back will change according to them with some fluctuations (will send video later)
Also, when holding leafs in hand, their color is just white. But it's correct in the inventory.

**Comment by pedrosouzabrasil** [comment]
@ptitSeb ...

**Comment by ptitSeb** [comment]
I don't think glColor can alter transparency.
Also, IIRC, the "lightmap effect" of micecraft is not a glColor color command, but a single glMultiTexCoord par minecraft block. This should be hanlded correctly, but may I broke the handling of that. I have seen this technique used only on minecraft. I'll try to run minecraft on my Pandora to see if I can reproduce any of this. I assume it's latest vanilla version?

**Comment by pedrosouzabrasil** [comment]
Thanks..sorry tô ping.

**Comment by khanhduytran0** [comment]
>  I assume it's latest vanilla version?

Yes, 1.16.4 is current latest vanilla release.

**Comment by pedrosouzabrasil** [comment]
Please share news about testing on pandora..when you finalized testing.

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201112-063956_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/63176856/98925763-2c8c3a00-24b5-11eb-9b54-e1dd4b84fd54.jpg)

Another bug on mob textures (fish are white)

**Comment by ptitSeb** [comment]
They are supposed to be purple or something like that?

**Comment by pedrosouzabrasil** [comment]
Many different colors...

**Comment by pedrosouzabrasil** [comment]
Some interesting notes(known bugs)

1... Sheeps are only white in game
2... Fish colors are white only (a variation of fish only)
3... Banners in game are only white too
4... Some itens helding in hand are white Textures (grass blocks and some mob spawners)
5... More to Discover?
Hope i helped

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201112-120337_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/63176856/98957020-7be76000-24df-11eb-8a5d-a31e0b43be3d.jpg)



When the character (skin)are closer to a block..in some angle the color appear correctly...in hand

**Comment by ptitSeb** [comment]
That's a bit strange. I hope I'll be able to reproduce on the Pandora, and also able to make GL capture of the command to better understand what is happening.

On your side, can you try to use `LIBGL_BATCH=10` and see if it make any changes?

**Comment by pedrosouzabrasil** [comment]
Thanks so much! i will pass your information to the dev of the app..blessed day..If it works i will be very happy and close this issue.

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201112-131013583.jpg](https://user-images.githubusercontent.com/63176856/98965160-780c0b80-24e8-11eb-843f-7ffec65da971.jpg)......still dont fix

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201112-131123513.jpg](https://user-images.githubusercontent.com/63176856/98965238-9245e980-24e8-11eb-8527-86583b0a0ecd.jpg)

**Comment by ptitSeb** [comment]
"-LIBGL_PATCH=10"? Isn't it "-DLIBGL_BATCH=10"

Also, what color is wrong on the screenshot? The sheep?

**Comment by pedrosouzabrasil** [comment]
The sheep egg spawn is right when in cert position..in game

**Comment by ptitSeb** [comment]
I still don't understand what color is wrong on the last screenshot, but nevermind, there are enough case described already

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201112-135812_Samsung Internet.jpg](https://user-images.githubusercontent.com/63176856/98970863-33d03980-24ef-11eb-863e-5e582d8a0739.jpg)![20201112_134318.jpg](https://user-images.githubusercontent.com/63176856/98970878-3763c080-24ef-11eb-9bf6-69c787b097a4.jpg)


To finalized..Its a problem related to version 1.16.4 for the game only..when change the code the textures works correctly (older versions like 1.14.4 for example)

**Comment by pedrosouzabrasil** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/blob/v3_openjdk/app/src/main/java/net/kdt/pojavlaunch/utils/JREUtils.java



Still dont work.. waiting for some news or a possible fix.. thanks

**Comment by pedrosouzabrasil** [comment]
News on Pandora?good night..

**Comment by ptitSeb** [comment]
tried a bit to run on Pandora, but 1.16 is really to much for that old system. I'll try on some RPi or something else to reproduce.

**Comment by pedrosouzabrasil** [comment]
Maybe try on an Android decide Android 10 recommended...

**Comment by pedrosouzabrasil** [comment]
Tutorial.... install apk normally.. you need to add jre runtime...give app permissions..and close app..no need account online..,after put all content inside(es file explorer)(use show hidden files on app settings)(put on.games folder).. lwgl2 bridge on lwgl3 folder...less lwjgl.jar .and lwjglfw ..(i send a link for a separate version of the archives,..they need to go to lwjgl3 folder..too..and after that open the app normally and install a version.(1.16.4 in this case)(need stable internet connection for download)..and try play normally

**Comment by pedrosouzabrasil** [comment]
White horses..(they are usually with some colors)on version 1.16.4

**Comment by ptitSeb** [comment]
I want to reproduce to I can record the frame with PVRTrace, so I can analyse more precisily what is going on. I don't like much dev. on android (or debugging on android), so I'll try on device as a last resort...

**Comment by pedrosouzabrasil** [comment]
Ok.. waiting for news regarding this rendering bug.

**Comment by pedrosouzabrasil** [comment]
maybe you are busy these days..

**Comment by ptitSeb** [comment]
Yes, I'm busy, and gl4es is not my priority lately. So you need to be patient, sorry.

**Comment by pedrosouzabrasil** [comment]
At least you are very educated..ok..later i will give you a donation tô support your work..i will not disturb you anymore...(until some news..
Have a blessed day.

**Comment by ptitSeb** [comment]
In the mean time, you can try to get a PVRTrace yourself: https://www.imgtec.com/downloads/download-tag/pvrtrace/ the tools is downloadable by anyone I think, and should work on many devices (not only ImgTec one I think). Having a trace would help me a lot, as I would be able to see part of what gl4es does wrong.

**Comment by pedrosouzabrasil** [comment]
Ok..i Will try to help

**Comment by khanhduytran0** [comment]
Does it work with any GPU or just PowerVR GPU?

**Comment by ptitSeb** [comment]
I'm unsure. It may work with any GPU. It needs to be tried.

**Comment by pedrosouzabrasil** [comment]
I tried to find the apk in the oficial website....but i cant...where is the apk?the documentation i already download...i dont know if i can help to find the render problem...because um not a programmer.

**Comment by ptitSeb** [comment]
It's not an APK! It's a set of library that you use to overload system ones. It is very usefull to be able to capture all GL command and replay them, step by step... There is nothing to program here, but it's more complicated then sideloading an APK indeed.

**Comment by pedrosouzabrasil** [comment]
I have find a nice tutorial on YouTube..i Will try

https://youtu.be/J6o87ZlmDBc

**Comment by pedrosouzabrasil** [comment]
I tried pvrhub on my device...first its not made for android 10 ..secondly it requires root acess..(for me at least).so the only hope is you trying there (ptitseb)..no preassure..

**Comment by pedrosouzabrasil** [comment]
News?

**Comment by ptitSeb** [comment]
No, no news, I haven't worked on that yet.

**Comment by pedrosouzabrasil** [comment]
Hi!i just want to say that i tried everything...i used nox emulator... Android Studio and my device but unfortunely no sucess to find the render bug on pojavlauncher..also yesterday..me and one of the devs tried too(no sucesss)(we tried to run the app on BlueStacks..but didnt work)so....i dont have any more ideas..also im very frustrated..and tired ..the only hope is you (pttitseb)to help us.. thanks and sorry...and no preassure (you can try whenever you want)..blessed day

**Comment by ptitSeb** [comment]
Ok, So I have a good news: I can reproduce the issue on my PI4.
But I have a bad news: I cannot make a PVRTrace, it make Minecraft crash.

But I have a plan B: I made an OpenGL apitrace of the game, looking at a black sheep (that appear white with gl4es), so I should have some material to find the issue...

I'll keep you posted.

**Comment by pedrosouzabrasil** [comment]
Greatttt...thanks só much..waiting for news

**Comment by pedrosouzabrasil** [comment]
Also..if you not sucessfull on pojavlauncher..you can try mcinabox..wait for link for How to install (thats because the render bug is occuring on mcinabox too (gl4es is used)

**Comment by pedrosouzabrasil** [comment]
https://github.com/AOF-Dev/MCinaBox/releases

**Comment by ptitSeb** [comment]
Based on the apitrace, I did a PVRTrace using gl4es.
![image](https://user-images.githubusercontent.com/3250792/99811289-41b43900-2b45-11eb-8920-a24d656805c2.png)
I should have eveyrthing to understand why colors are not there.

**Comment by pedrosouzabrasil** [comment]
Thanks so much pttiseb really apreciate..also i will donate again to suport

**Comment by pedrosouzabrasil** [comment]
Maybe the error (s) that will be find on sheeps are the same as banner..also clouds too..and some other mobs white textures

**Comment by pedrosouzabrasil** [comment]
To remember     


1 sheep textures only white in game (they are Black.. Pink (rare)and brown)
2 experience orbs from experience bottles are white
3a type of fish mob is white
4 a type of horse is white too
5 banners are all white
6 some itens in inventory are wrong texture(white)
7 clouds are rendering with lines inside them(bug)on fancy graphics
8..mipmaps dont work in game(?)...blurry textures in distance 
.....hope i helped and really apreciate if you could check these itens

**Comment by ptitSeb** [comment]
So, I think the issue is around the normal calculatio in an generated shader, but I haven't been able to find that source of the issue.
But I have added a workaround, as it's better then nothing. Use `LIBGL_NORMALIZE=1` with latest version of gl4es. That should fix most (all?) the color issues.

**Comment by pedrosouzabrasil** [comment]
Great! Lets test

**Comment by pedrosouzabrasil** [comment]
That works! .. all textures in game are fixed..(only clouds not)

**Comment by pedrosouzabrasil** [comment]
Can you check in a later moment why clouds in fancy graphics are not rendering correcto(its not a priority right now ..)

**Comment by ptitSeb** [comment]
I'll check later yes... not sure when...

**Comment by pedrosouzabrasil** [comment]
No problem..amazing work so far..im already so happy.. thanks so much

**Comment by khanhduytran0** [comment]
Also, Minecraft 1.7.10 broken on 1.1.5...
![](https://cdn.discordapp.com/attachments/753382883082633316/779867985082449962/Screenshot_20201121-213633_PojavLauncher_Minecraft_Java_Edition_for_Android.jpg)

**Comment by pedrosouzabrasil** [comment]
So...some problems in minecraft using latest gl4es 1.1.5..a new one i found is that entities are blue in distance on minecraft  1.16.3 using fabric and sodium(mod inside minecraft) 
![Screenshot_20201121-215917_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/99891153-97700a80-2c45-11eb-80e9-d20481f75130.jpg)

**Comment by pedrosouzabrasil** [comment]
So developer of gl4es...a list to remember the problems and help you to find the issues related to them..
1.some older minecraft versions (1.17.10 )dont work using latest gl4es(bug)
2.some entities are blue in distance in ocean using fabric mod inside pojavlauncher (if you need the folder to put inside game for you to analize i can help you)
3 cloud lines (render bug)inside minecraft on fancy grahics (settings in game)
4..the other issue is about some settings dont work using latest gl4es 1.1.5...screnshoot below 
![Screenshot_20201121-220014_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/99891244-8b387d00-2c46-11eb-8714-5f58be2138cc.jpg)

Also thanks so much to help me and minecraft community..blessed day /night

**Comment by ptitSeb** [comment]
Please create 1 ticket per issue. So I can track indiviual problem, and can close the ticket when it's solve (and avoid having 1 ticket with hundreds of entry that speak about everything).

**Comment by pedrosouzabrasil** [comment]
Sorry

**Comment by pedrosouzabrasil** [comment]
So (this issue)final fix..About clouds ....any news?

**Comment by ptitSeb** [comment]
Nope, I haven't looked at it, or I would have mentionned something.

**Comment by pedrosouzabrasil** [comment]
hi again..i want to apologize for anything..it may seem like i'm rushing you to solve this problem .. however..I'm super calm about it and I want you to work first to resolve your priorities, be they here (gl4es ) or something else that you develop ... in addition I thank you wholeheartedly for the effort in solving various problems in gl4es .. (programming can sometimes become difficult) .. and I hope a blessed day for you and your family ..
