### ISSUE TITLE
VBO regression in xash3d

### ISSUE THREAD

**Issue by mittorn** [ptitSeb/gl4es#250]
New VBO code (commits 0b173f318dd8a0a4232300cb5264487fb7d17415 and ac70d837ce56e04e058d01056ef70284d674ba0f) completely breaks rendering in xash3d. After loading world even some menu/console elements disappears., setting drawing to Begin/End does not help.  It seems, something wrong with BO binding/unbinding.

**Comment by ptitSeb** [comment]
Ah ok. the binding/unbinding optim seemed simple enough. There must be a special case I missed somehow.

**Comment by Sisah2** [comment]
Openmw is also affected, missing buildings, body parts :)

**Comment by ptitSeb** [comment]
Yes indeed, I reproduce on my side. Maybe that one will be simpler to debug for me.

**Comment by ptitSeb** [comment]
@mittorn is it fixed with latest commit?

**Comment by ptitSeb** [comment]
@Sisah2 it should be fixed now for openmw.

**Comment by mittorn** [comment]
Yes, seems to be fixed now
