### ISSUE TITLE
Gl4es + sodium(minecraft optimizer) on android crash

### ISSUE THREAD

**Issue by Malaska678** [ptitSeb/gl4es#251]
When i run minecraft with sodium it crash before even minecraft load. It uses modern open gl for making chunk loading better.

**Comment by Malaska678** [comment]
Note that: where not even loading chunks. Were crash when launch minecraft

**Comment by ptitSeb** [comment]
maybe it's too modern. GL4ES support only OpenGL 2.1, not 3.x or more.

**Comment by khanhduytran0** [comment]
Sodium uses Oneshot renderer if run in OpenGL 2.x, so it should be compatible with GL4ES.

**Comment by ptitSeb** [comment]
Ok. well, there is an open ticket with the "new VBO" optim that may crash is some cases, so maybe this one is related (ticket #250 )

**Comment by khanhduytran0** [comment]
Sodium started to work by disable these 
![B6439633-1142-4F92-AC24-228B43BD8F52](https://user-images.githubusercontent.com/40482367/99890055-f194be00-2c8d-11eb-8bba-37522c4722db.jpeg)

Also, tested by @pedrosouzabrasil, it uses Oneshot GL 3.0 but still works...
![img](https://media.discordapp.net/attachments/753382883082633316/779852539352186910/Screenshot_20201121-203451_PojavLauncher_Minecraft_Java_Edition_for_Android.jpg)

**Comment by BigGuyBlue** [comment]
Noice

**Comment by BigGuyBlue** [comment]
Oh wrong account

**Comment by Malaska678** [comment]
Closing

**Comment by khanhduytran0** [comment]
Also, he says uses GL 2.0 cause crashes, but GL 3.0 make it works.

**Comment by Malaska678** [comment]
Can i test it now?

**Comment by Malaska678** [comment]
69420
