### ISSUE TITLE
Minecraft java(pojavlauncher)clouds is not rendering correctly in game (lines inside tem)(version 1.16.4)

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#252]
Hi gl4es dev!i have created this issue..(i know you already knows this problem)but to make things more organized ...this is happen to clouds in game.. screenshot below
![Screenshot_20201123-113114_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/100091671-b0d6a980-2e33-11eb-8fc4-3db2538cde79.jpg)

![Screenshot_20201126-110010_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/63176856/100359820-d7811580-2fd6-11eb-9086-7e5af241c813.jpg)

So how its suposed tô be...(below)..also latest version of gl4es 1.1.5

![Screenshot01](https://user-images.githubusercontent.com/63176856/100091894-014e0700-2e34-11eb-97f2-b19fc4401359.png)

Blessed day...

**Comment by pedrosouzabrasil** [comment]
Hi..i was worried about you..(pttiseb)if you are ok..but i saw commits on box86..keep amazing work!

**Comment by ptitSeb** [comment]
Yeah, sorry, still very busy with box86...

The cloud seems transparent where they should not. Strange. Again, I'll will have to make an apitrace capture, than a PVRTrace of the apitrace probably, to understand what is happening.

**Comment by pedrosouzabrasil** [comment]
Ok..time is yours..good luck....later i will donate to your project again..to support..also..this is a little problem ...blessed day as always..when news..share with us

**Comment by pedrosouzabrasil** [comment]
I saw a new release of box86...also steam games works?(sorry if not related here)only a question..and cloud news?

**Comment by ptitSeb** [comment]
Yes, box86 still have most of my focus for now (so no clouds news). Steam wrosk yes, some steam games also works (not all). It also greatly depends of the OpenGL driver there.

**Comment by pedrosouzabrasil** [comment]
Understand..also have a wonderful day as always

**Comment by pedrosouzabrasil** [comment]
Can i help you in cloud bug?how to do an apitrace?

**Comment by pedrosouzabrasil** [comment]
How development is going on box86 dev?

**Comment by pedrosouzabrasil** [comment]
Hi..sorry disturb again but there is an apitrace tutorial on youtube?for me to help you?

**Comment by ptitSeb** [comment]
I don't know if there is an apitrace tutorial. using apitrace on computer is easy. The cloud issue is not a high priority issue, that's all.

**Comment by pedrosouzabrasil** [comment]
You are right..

**Comment by pedrosouzabrasil** [comment]
Good night dev..hope you are well..

**Comment by pedrosouzabrasil** [comment]
Maybe in this week you will have a free time to see cloud bug.(hope)

**Comment by pedrosouzabrasil** [comment]
I send you a small donation for support your projects!..

**Comment by ptitSeb** [comment]
Yeah, I have seen. Thanks you. I still think this is a minor issue. Anyway, it should be fixed now (precision issue in the Depth texture for a FBO).

**Comment by pedrosouzabrasil** [comment]
Thanks so much!!!!!!!!

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201202-101231273.jpg](https://user-images.githubusercontent.com/63176856/100877079-0b50b500-3487-11eb-9084-0dfeaf00f447.jpg)



Game is weird now..you have tested pttiseb?

**Comment by ptitSeb** [comment]
Maybe the hardware doesn't support depth texture with float correctly?

You can try to change the `GL_FLOAT` on line 162 of `gl/texture.c` to `GL_UNSIGNED_INT` or `GL_FLOAT_32_UNSIGNED_INT_24_8_REV`. Maybe that help?

You can also try to use `LIBGL_NODEPTHTEX=1` env. var. to disable depth texture.

**Comment by pedrosouzabrasil** [comment]
Thanks for hard work. We will try later today..

**Comment by ptitSeb** [comment]
`GL_UNSIGNED_INT` should help (according to gles3.0 spec, I assume it should be the same for gles2.0).
If it's ok, I change the fix the use that instead.

**Comment by pedrosouzabrasil** [comment]
The custom var fix render problem..clouds still..i need add that other custom var in game..?

**Comment by ptitSeb** [comment]
Try to change line 167 of src/gl/texture.c, from `GL_FLOAT` to `GL_UNSIGNED_INT` and without the env. var.

**Comment by ptitSeb** [comment]
So with just the Env. Var., the rendering is correct, but not the clouds?

**Comment by pedrosouzabrasil** [comment]
Thanks

**Comment by pedrosouzabrasil** [comment]
![Screenshot_20201202-113319588.jpg](https://user-images.githubusercontent.com/63176856/100886129-368cd180-3492-11eb-90e5-dbc4d4521565.jpg)




Fixed!!!!!!wowow

**Comment by pedrosouzabrasil** [comment]
Only did that change on src..worked perfectly!

**Comment by ptitSeb** [comment]
Out of curiosity, what is your phone? (so solid 60fps on 2340x1080 with fancy graphics is very good!)

**Comment by pedrosouzabrasil** [comment]
Im on samsung tab s7 (snapdargon 865 plus haha)
