### ISSUE TITLE
Minecraft 1.14.4 below is not working (pojavlauncher)

### ISSUE THREAD

**Issue by pedrosouzabrasil** [ptitSeb/gl4es#253]
Latest gl4es 1.1.5 is not working on older versions of Minecraft inside pojavlauncher...

**Comment by Malaska678** [comment]
Additional info: Minecraft 1.14 and below reauire display list

**Comment by Malaska678** [comment]
While 1.15+ dont

**Comment by pedrosouzabrasil** [comment]
Thanks for help @Malaska678

**Comment by Malaska678** [comment]
maybe im wrong

**Comment by Malaska678** [comment]
Im not sure if its causing the problem. Becoz im dumb

**Comment by SavagePy10** [comment]
Ptitseb, hello!

**Comment by SavagePy10** [comment]
What's going on this issue?

**Comment by pedrosouzabrasil** [comment]
I will retest because some news commits..to see if older versions are working normally..(gl4es 1.1.5)

**Comment by SavagePy10** [comment]
> I will retest because some news commits..to see if older versions are working normally..(gl4es 1.1.5)

Good!

**Comment by pedrosouzabrasil** [comment]
All version are working great just Add -Dorg.lwjgl.opengl.libname=libgl4es_115.so and its solved!good gameplay everybody
