### ISSUE TITLE
Fricking Shark issues (was : speed descrease in frickingshark since adding of handling 16 TMU instead of 8 in 2020 17 Febrary)

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#258]
@ptitSeb 

It's me again 👍 So currently Hans adds to our warp3dnova all the missing instructions, and I can build fine again fresh gl4es and do all the tests.

Now, if you remember I report some time ago in a closed issue about the fricking shark game, that there is some strange speed decrease on 15 FPS and pauses in the menu. I traced that to the commit: https://github.com/ptitSeb/gl4es/commit/62c9db85746760d16f17c8a31b0e95384bd15c3d

This one, where 16 TMU instead of 8 were added. 

I also tested the very latest issues of gl4es: the issue still there and the same.

You may try it on Pandora to see if that gives you the same problems: just build fricking with this commit, and one previous, and compare the FPS at the beginning of the game (by pressing F4). On my side, FPS drop is pretty noticeable, as well as in the menu I have massive slowdowns too.

That may be not related to the exact fact of adding 16 TMU instead of 8, but maybe there some bug flying around in that code (like broken ifs/else or something of that sort) that can cause this.

I can help with any remote tests, just say what/where to check so you will not lose your time to build all things yourself.

Thanks!

**Comment by kas1e** [comment]
Btw, in the same commit I can see there were changes done to shaderconv.c as well, maybe that somehow related, and not TMU exactly...

**Comment by kas1e** [comment]
Ok, changes in config.h ```#define MAX_TEX 16``` on ```#define MAX_TEX 8```, do back FPS to normal, as well as no slowdowns in the menu. I also do check the very latest gl4es with the same change from 16 back to 8 and speed back to a normal state.

Now to understand is it a general question or some limitation of amigaos4 drivers? That needs to be checked on Pandora. I may try to check it on my x86 Linux as well...

**Comment by ptitSeb** [comment]
So, you want me to check if with just MAX_TEX to 16 or 8 on the Pandora I have a speed difference in game in FrikingShark?

**Comment by kas1e** [comment]
Yes, so we will know if it gl4es, or AmigaOS :) To test I just run it in 2 ways: with and without shaders. The First 2 tests do on the build with MAX_TEX 8 and another 2 tests with the same build of gl4es just with 16 MAX_TEX.  FPS I count just by starting level1, press f4, and see for the first 3 seconds what is shown. It's enough to see a difference.

And not only FPS drop, on my side, but the Menu also start to be jerky too (just need to wait for first ships to be shows)

**Comment by ptitSeb** [comment]
![frikingshark_16](https://user-images.githubusercontent.com/3250792/102258844-9e213300-3f0e-11eb-9eef-277f949777e4.png)
Here is a screenshot with current version (so TEX_MAX = 16).
I'm rebuilding gl4es with 8 now... It will take some time.

**Comment by ptitSeb** [comment]
![frikingshark_8](https://user-images.githubusercontent.com/3250792/102260310-91054380-3f10-11eb-8a4d-2ccfb63beced.png)
And here with 8. FPS on the screenshot is lower, but that's the screenshot itself that changed the value.
Truth is, it worked the same

(note that the Pandora only have 8 physical TMU anyway)

**Comment by kas1e** [comment]
Are you sure ?:) What I mean, with 20 FPS : 3 fps difference, with 60 FPS: 9fps differences, with 120FPS ~18 fps difference: exactly what I have.

Is it with shaders? Try for example to disable them (so to use gl4es ones), to see more FPS, maybe the difference will be more visibly.

**Comment by ptitSeb** [comment]
Yes I'm sure. Plus, it's the "8" version that have lower fps displayed, not the 16.
Everyrhing was the same. Even the intro with boats.

**Comment by kas1e** [comment]
Damn. I was so hoping it will be gl4es  :( I Will try to ask Daniel about it, but maybe have any idea in which area we may check? In end, we of course can add amigaos4 ifdef in config.h, but less ifdef always better.

Btw, can you also remove ifdef AMIGA from ```fpe_shader.c``` now, we have implemented all the stuff from.

**Comment by kas1e** [comment]
@ptitSeb 

Found some interesting details, maybe they will bring some idea.

I checked with the shaders coming with the game (not gl4es generated). So results with latest gl4es and different max_tex in config.h:

With shaders from game disabled : "IgnoreShaderSupport = 1".

Original public release:    117FPS.

max_tex_16 :  119 FPS
max_tex_14:   120 FPS
max_tex_10:   119 FPS
max_tex_8:    119 FPS
max_tex_2:    121 FPS

So there is no change when we use shaders generated by GL4ES.


Now with shaders from game enabled : "IgoreShaderSupport = 0".


Original public release: 73 FPS

max_tex_16 :  58 FPS
max_tex_14:   62 FPS
max_tex_10:   70 FPS
max_tex_8:    75 FPS
max_tex_2:    97 FPS


See, the less max_tex I use, the more FPS I have in the shader-which-come-with-game version of fricking! Up to almost 100FPS when I use max_tex_2 (and, with max_tex_2, the game still renders and plays correctly !)

Can you please try another time on Pandora, but be sure you have goreShaderSupport = 0, and test with just 2 tests: MAX_TEX_16 and MAX_TEXT_2 (so just 2, minimum). If there will be no differences, then it 100% warp3dnova.

Thanks for your time!

**Comment by ptitSeb** [comment]
That's certainly because some if the shader use an array of texture coord, and gl4es is unable to find the array max dimension and so put [MAX_TEX]. And the unused texture coord are not discarded on AmigaOS but are tracked and the data refreshed I guess.
I don't remember the custom shader used, but IIRC there are some texture array access, with some defined values or things like that.
Use the `LIBGL_DBGSHADERCONV` env to get the generated shaders.

**Comment by kas1e** [comment]
Hm, settings LIBGL_DBGSHADERCONV to 1, produce me 1:1 the same outputs for both versions of the game: with MAX_TEX2 and with MAX_TEX16. Need to dig in into options a bit more :)

**Comment by ptitSeb** [comment]
`LIBGL_DBGSHADERCONV=1` is fine, it will give all the shaders.

Did you "diff" the shader or just quickly checked with your eyes? Because it's easy to not spot that difference.

**Comment by kas1e** [comment]
I just grab the whole output, saved it to 2 different files, and then use "filecompare" tool to see a difference, and there is none :( Very strange.

**Comment by kas1e** [comment]
Double rechecked, shaders seems identical, see:

http://kas1e.mikendezign.com/a/friking_shaders_MAX_TEX_16.txt
http://kas1e.mikendezign.com/a/friking_shaders_MAX_TEX_2.txt

The only differences its input names and output of the gl4es a little, but shaders remain 100% identical (at least "filecompare" says so).

**Comment by ptitSeb** [comment]
Yes indeed. The `_gl4es_TexCoord` array is limite to `_gl4es_TexCoord[2]`, so it's not what I thought it could be.

**Comment by kas1e** [comment]
Very strange. And on your side on Pandora when original shaders is used, be it MAX_TEX_16 or MAX_TEX_2 (not 8, but 2), there is absolutely zero difference?

**Comment by kas1e** [comment]
Daniel's guess is that Frickin' for whatever weird reason (bug) enables a VA for every existing TMU (without actually using them then). At least that would explain the performance i  measuring. I send him different binaries with differetn MAX_TEX to play with.

Maybe on Pandora you didn't notice it, as you have proper DMA, etc ?

**Comment by ptitSeb** [comment]
Unused VA are are disable with `glDisableVertexAttribArray(i);` function. The disabling is on `scr/gl/fpe.c` lines 1518 - 1522. You can enable log (or put a printf) there to be sure if you want.

Also, I don't see direct corelation betweeb TMU number and VA.

You can check, MAX_TEX is not used much in fpe.c. The place were things could happens is in lines 1110-1140, but it's only about FBO.

And sampler themselvess are set lines 1398-1407 (using a macro) with GoUniformiv not calling any actual GLES2 function is the uniform is not present (but again, you can activate debug on `uniform.c` to be sure).

**Comment by kas1e** [comment]
Wait but we mean not GL4ES bug, but that it's maybe Friking's bug. And on Pandora, you may not see it because of DMA. I will check other games to see if they affected or it only fricking.

**Comment by ptitSeb** [comment]
But what bug? I mean, do you see any crazy access to various TMU or VA?

**Comment by kas1e** [comment]
@ptitSeb 
I found some regression in Fricking Shark rendering: it happens with both original Shaders and Non-Shaders (so even with pure gl4es internal ones). When you start to fly and move to the left, then the main ship starts to be darker, almost black... Like something with lighting happens. When you move to the right, no problems.

I tracked it down to the commit https://github.com/ptitSeb/gl4es/tree/a4486d5d65c299559e8e001ee17911221bf04c58 , called 
```Added a workaround for normal calculation bug in FPE (bug source still not found, to help #245)```. And seeing that this #245 is about things being "white", it seems that this workaround makes in some parts now being things black, while it shouldn't.

**Comment by kas1e** [comment]
Ok, find out, exactly change in the ```gl/matvec.c``` cause this. I.e. once i comment out that line:

```float det = 1.0f/(m[0]*r[0] + m[4+0]*r[1] + m[8+0]*r[3]);```

and put back as it was before:

```float det = 1.0f/(m[0]*r[0] + m[4+0]*r[3] + m[8+0]*r[6]);```

Then everything works fine again.

**Comment by ptitSeb** [comment]
Ok, I'll check, but why didn't you create a new ticket for this? It would be so much simple to track things down! Look at how it was easier to track the regression with a the ticket number and all. Now looks at this ticket? How meny issues are there? How to know wich commit fixes what issue?

**Comment by kas1e** [comment]
yeah, close, open new one
