### ISSUE TITLE
Minecraft JE framebuffer gave error on iOS

### ISSUE THREAD

**Issue by khanhduytran0** [ptitSeb/gl4es#263]
Hi. So after found a JVM for jailbroken iOS, I went to attempt get LWJGL3 and Minecraft working on. The project is mostly based on PojavLauncher Android, but with EGL replacement to EAGL. I had to modify GL4ES to get it built as dynamic library. Almost everything works, until Minecraft starting initialize framebuffer.
[crash-2021-01-05_06.36.26-client.txt](https://github.com/ptitSeb/gl4es/files/5768514/crash-2021-01-05_06.36.26-client.txt)
As on crash report, `glCheckFramebufferStatus()` returned `GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT`. I don't know what was wrong with my code. I tried these ways:
- Use `GLKView`.
- Use `GLKView` with pre-init framebuffer.
- Use `GLKView` and changed `LIBGL_FB` to 1 and 2.
- Use GLES context created by JavaFX.

I'm very new to iOS and coding that app without a Mac OS X device, so debugging is quite hard. I could not find a GLES debug tool for jailbroken device. I don't know what to do. May I modify to enable GL commands logging? Could you try to fix it? Thanks in advance.

**Comment by khanhduytran0** [comment]
Also, tested device: iPhone 6s plus, iOS 13.4.1.

**Comment by khanhduytran0** [comment]
Also, this is GL4ES log
```

LIBGL: Initialising gl4es
LIBGL: v1.1.4 built on Jan  3 2021 03:20:53
LIBGL: using framebuffer + fbo
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware test on current Context...
LIBGL: Hardware Limited NPOT detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_shader_texture_lod detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 15
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Max Color Attachments: 1 / Draw buffers: 1
LIBGL: Hardware vendor is Apple Inc.
LIBGL: GLSL 300 es supported and used
LIBGL: ignore MipMap
LIBGL: Targeting OpenGL 2.1
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: glXMakeCurrent FBO workaround enabled
LIBGL: Current folder is:/
LIBGL: Shuting down
```

Ohh. I noticed this line
```
LIBGL: glXMakeCurrent FBO workaround enabled
```
How do I make current with it?

**Comment by ptitSeb** [comment]
Activate debug for `framebuffers.c` bu uncommenting line `12` of the file and rebuild everything.
That will gives detail on the framebuffers function only. It should be enough to understand what's going on.

(On don't have access to any jailbreaked iPhone/iPad device to test)

**Comment by ptitSeb** [comment]
Size 0x0 :O
that's not good.
The Viewport is probably not correctly initialized

**Comment by ptitSeb** [comment]
In `glstate.c`
can you insert this
```C
printf("Viewport %dx%d\n, glstate->raster.viewport.width, glstate->raster.viewport.height);
```
line 393 and see the output?

**Comment by khanhduytran0** [comment]
It's 0x0...

**Comment by khanhduytran0** [comment]
May I call `glViewport(0, 0, witch, height);` before `initialize_gl4es()`?

**Comment by ptitSeb** [comment]
IS the GL context already created before calling `initialize_gl4es()`? Because it seems not.

**Comment by khanhduytran0** [comment]
Context is already created, if not, LWJGL would crash earlier.

**Comment by ptitSeb** [comment]
Then, yeah, maybe set the viewport.
But if you call it before initialize_gl4es, this need to using GLES2.0 lib (so probably from Swift side). You can do it on C side after initialize_gl4es also.

**Comment by khanhduytran0** [comment]
After add `glViewport()`, rd-132211 works at 1000fps but nothing rendered on screen. Maybe GLKView has 0x0 size?...

**Comment by khanhduytran0** [comment]
Other versions stills not working and reports same framebuffer error, size 0x0.

**Comment by khanhduytran0** [comment]
Also, if you know iOS programming, could you take a look at https://github.com/PojavLauncherTeam/PojavLauncher_iOS/tree/main/Natives to see what's wrong...

**Comment by khanhduytran0** [comment]
So I rewrote the UI of app to use a ViewController and it started to work... only rd-132211 then swap buffers called from multiple places made game crashes... I will try framebuffered versions once got rd-132211 fully works.

**Comment by khanhduytran0** [comment]
So, I got rd-132211 worked stable. But framebuffered versions stills complains about framebuffer size 0.

**Comment by khanhduytran0** [comment]
Oh. I fingered out it's my missing implementation. Anyways thanks for help.

**Comment by khanhduytran0** [comment]
Almost any versions rendered incorrectly. No versions rendered splash screen.

1.6.x only render panorama at bottom left screen.
![image](https://user-images.githubusercontent.com/40482367/103849487-59d11f00-50d7-11eb-903e-9e36182a1450.jpeg)
Also, screen flickering when run. It repeatly printed GL error in log:
```
2021-01-07 03:56:11 [CLIENT] [SEVERE] ########## GL ERROR ##########
2021-01-07 03:56:11 [CLIENT] [SEVERE] @ Post render
2021-01-07 03:56:11 [CLIENT] [SEVERE] 1282: Invalid operation
2021-01-07 03:56:11 [CLIENT] [SEVERE] 
```

**Comment by khanhduytran0** [comment]
Any ideas?

**Comment by ptitSeb** [comment]
What you see is drawn "offscreen", then a "glReadPixel" is used and the actual menu then drawn, with that little backdround use as Background.

That you see this is not really normal, but can happens in some cases when you don't have double buffering and when using `glReadpixels(..)` provoque a flush. I do have this behaviour on the Pandora when I use `LIBGL_FB=1` (and I did a wrkaround for it with `LIBGL_FB=2`).

**Comment by khanhduytran0** [comment]
I added `LIBGL_FB=2`, but it stills on tiny panorama...

**Comment by khanhduytran0** [comment]
Also, I used `[[EAGLContext currentContext] presentRenderbuffer:GL_RENDERBUFFER];` for swapping buffers. May I use `glXSwapBuffers()` instead? Or that method is stub when `NOEGL=1`?

**Comment by ptitSeb** [comment]
You should be able to use `glXSwapBuffers(...)`

**Comment by khanhduytran0** [comment]
Do I need to call `presentRenderbuffer` after `glXSwapBuffers()`?

**Comment by khanhduytran0** [comment]
Also, where do I get required parameters of `glXSwapBuffers`?

**Comment by khanhduytran0** [comment]
Or may I call `gl4es_SwapBuffers_currentContext()`?

**Comment by khanhduytran0** [comment]
I could not call that, some symbols could not be located. At the first try to compile, I got `aliases are not supported on Darwin` so I changed to `#pragma weak` but symbol won't not get exported...

(for GL calls I had to modify LWJGL to redirect to `gl4es_gl*` as workaround).

**Comment by khanhduytran0** [comment]
Any more ideas? I don't know how to dealing with alias export on iOS.

**Comment by khanhduytran0** [comment]
Almost 2 week of slilence... you have no more ideas? Or i just declare glX methods manually?

**Comment by ptitSeb** [comment]
Ah yeah, sorry, I'm busy with box86.
Alias not beeing supported on Darwin is a problem, as this functionnaly is heavily used on gl4es. I probably need to create another way to do the Alias macor, and change the whole lot of things. Not sure when I'll do that.

**Comment by khanhduytran0** [comment]
Ah okay..
But with `NOX11=ON`, how can I use `glXSwapBuffers()`?

**Comment by khanhduytran0** [comment]
So these files are excluded when `NOX11=ON`
```
src/glx/hardext.c
src/glx/glx.c
src/glx/lookup.c
src/glx/gbm.c
src/glx/streaming.c 
```
I gonna try compile with them and let you know result of using `glXSwapBuffers()`

**Comment by khanhduytran0** [comment]
So, `glXSwapBuffers()` was excluded from build. I can't use it. Any more ideas?

**Comment by khanhduytran0** [comment]
I just tried MetalANGLE (GLES -> Metal translator) with GL4ES (EGL disabled) and 1.16.5 rendered splash screen! Thank you so much for helping there. Keep your good work up!

**Comment by khanhduytran0** [comment]
> I could not call that, some symbols could not be located. At the first try to compile, I got `aliases are not supported on Darwin` so I changed to `#pragma weak` but symbols were not get exported...
> 
> (for GL calls I had to modify LWJGL to redirect to `gl4es_gl*` as workaround).

So, I found out that Darwin has `__DARWIN_ALIAS` macro, which is `attribute alias` solution. Can you check it? https://opensource.apple.com/source/xnu/xnu-1228.15.4/bsd/sys/cdefs.h
@ptitSeb
