### ISSUE TITLE
AmigaOS4: broken precompiled shaders

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#266]
Find out that with the latest GL4ES created .gl4es.psa files do not work as expected on the next run. I.e. if we have no such a file, run a game, it runs fine. Then on exit, it create .gl4es.psa. Then, next run: nothing renders, or almost nothing renders. Most of the parts black, etc. Tested that with some simple SDL test cases, and with few games. So it not related to the application in the question.

With gl4es from the old times, for example from 09/15/2019, everything fine. 

Maybe (just a wild guess) it is related to the fact, that now on the start, i have in output that:

```
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
````

While before (when all works as expected) it was only:

```
LIBGL: GLSL 300 es supported
```

But not sure if that it.

**Comment by ptitSeb** [comment]
It's strange, I don't have this issue on my side.
A build from more than a year old doesn't help much, it's a bit too old, there are way too many commit in between.

The message you listed will not have any impact on the psa archive reading.

Not sure what could be the issue here. First please uncomment line 12 of `fpe_cache.c` and grab the log from the creation of the psa archive (when it doesn't exist) then the log when loading the psa archive.

**Comment by kas1e** [comment]
It's very strange but when i uncomment that line, nothing changed much. In console it print nothing about. That what i have for 2 runs:

```
2/0.Work:aaaa> ls -la
total 2822
drwxr-xr-x  2 root wheel       0 2021-01-15 19:35 .
drwx------  2 root wheel       0 2021-01-15 19:35 ..
-rwxr-xr-x  1 root wheel 2889496 2021-01-15 19:35 lesson04

2/0.Work:aaaa> lesson04 
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jan 17 2021 19:31:30
LIBGL: Using GLES 2.0 backend
LIBGL: Using Warp3DNova.library v1 revision 83
LIBGL: Using OGLES2.library v3 revision 1
LIBGL: OGLES2 Library and Interface open successfuly
LIBGL: Targeting OpenGL 2.1
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: Current folder is:Work:aaaa
LIBGL: Hardware test on current Context...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Max Color Attachments: 1 / Draw buffers: 1
LIBGL: Hardware vendor is A-EON Technology Ltd. Written by Daniel 'Daytona675x' MьЯener @ GoldenCode.eu
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: Shuting down
LIBGL: Saved a PSA with 1 Precompiled Programs

2/0.Work:aaaa> ls -la
total 2824
drwxr-xr-x  2 root wheel       0 2021-01-15 19:36 .
drwx------  2 root wheel       0 2021-01-15 19:35 ..
-rw-r--r--  1 root wheel    1530 2021-01-15 19:36 .gl4es.psa
-rwxr-xr-x  1 root wheel 2889496 2021-01-15 19:35 lesson04

2/0.Work:aaaa> lesson04 
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jan 17 2021 19:31:30
LIBGL: Using GLES 2.0 backend
LIBGL: Using Warp3DNova.library v1 revision 83
LIBGL: Using OGLES2.library v3 revision 1
LIBGL: OGLES2 Library and Interface open successfuly
LIBGL: Targeting OpenGL 2.1
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: Current folder is:Work:aaaa
LIBGL: Loaded a PSA with 1 Precompiled Programs
LIBGL: Hardware test on current Context...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Max Color Attachments: 1 / Draw buffers: 1
LIBGL: Hardware vendor is A-EON Technology Ltd. Written by Daniel 'Daytona675x' MьЯener @ GoldenCode.eu
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: Shuting down 
```

And that all. When run first time all works, then you can see there .psa created and then second run it runs, just render black screen

**Comment by ptitSeb** [comment]
Well, yeah, there isn't much debug log there in fact.
Strange that this 1 precompile shader is wrong.

**Comment by ptitSeb** [comment]
I don't see any reason why this shouldn't work. Can you do a bisect to find the commit that broken it?

**Comment by kas1e** [comment]
Yeah, will check one by one

**Comment by kas1e** [comment]
Do some tests, all I can say is that in this commit 2137 from 24 Feb 2020 : https://github.com/ptitSeb/gl4es/tree/19d9c891ddbd8131e8826a6cb634e3e4883a67f1 

All still works fine.

Then, after it come to some refactoring by mittorn, then some of your fixes, and then after fix from Daniel about amigaos4 compile. And at this one thing already stop working.

So something happens 25 Feb 2020, but in which exactly commit I can't say, because they can't be linked due to amiga-build fail, but once amiga builds back on 28 Feb (and between 25 and 28 Feb there wasn't any more commit) .psa loading already broken.

So it can be or refactoring, or massive changes in f how VertexAttrib is handled.  Or maybe when amigaos4 build back, something went wrong too.

**Comment by kas1e** [comment]
In meantime I may try to fix the amigaos4 build right after Mittron's restructuration, so we can see if those changes broke .psa saving/and-or/loading/and-or/parsing, or it something which comes in the next few commits after.

**Comment by ptitSeb** [comment]
Ok.

I need to analyse allthoses commit to see what could break amiga handling of PSA (I don't hen know what is wrong, is it the read or the write of the PSA? or something else?)

**Comment by kas1e** [comment]
I may try to compile 2 different versions: one previous those restructuration, and one after. Compare the size of files, their content. And then we will have something. Will do so now.

**Comment by kas1e** [comment]
Ok done, as I see files creates, the same size, and absolutely identical by content, there is (just to be sure):

http://kas1e.mikendezign.com/aos4/gl4es/broken_psa/gl4es.psa_2137
http://kas1e.mikendezign.com/aos4/gl4es/broken_psa/gl4es.psa_2149

So that or loading, or parsing. Or what it also possible, a new way of handling VertexAttrib things?

**Comment by kas1e** [comment]
Also if I set ```LIBGL_NOTEXARRAY 1``` , then .psa not generated. I remember we add it especially back in past, to cure some past issues. Maybe now it should back (and maybe that also somehow related to the issue we had now ?)

**Comment by kas1e** [comment]
Ok, that was pain, but I find the guilty commit! : https://github.com/ptitSeb/gl4es/tree/ba2cc81ea4fe54002fab7ff30c0bf09d148df12c
called "Massive refactor of how VertexAttrib are handled"

And now when I tried to run some game over that commit and tried to see what happens after we tried to load it with generated .psa, it seems tried to render something, just all very black/dark/very little visibly.

Ah and I remember why we remove generating of .psa when LIBGL_NOTEXARRAY is used: because created shaders are different, and when we will try to run them when this environment not set, it will give us bugs. So probably that correct as it now.

Now to understand, what happens with this commit. Shaders are surely fine and work correctly. Then they saved to .psa, the same as before, but then since that commit loading/parsing of them are broken (or some values start to be broken, dunno).

**Comment by kas1e** [comment]
I give a go and check all the files from this commit which contains amigaos4 ifdefs, there those changed files:
```
buffers.c
getter.c
gl4es.c
glstat.c
```

So probably in one of those ones some amiga ifdef was or missed or forgotten when these massive change about vertex attrib happens.

Because if everything works, but fail to works when we run it with precompiled shaders, it means that some amigaos4 ifdef is just vanished or missing or something of that sort (because if something were broken, then it will not works first time too, so it IMHO some missing ifdef).

I may try to change back file by file, but I fear with this commit it impossible, as all the changes were done in one push meaning they all referenced with each other quite much...

**Comment by kas1e** [comment]
I will try for now by hands file by file change back changes from the guilty commit on latest gl4es, to see when precompiled shader start to works. There were indeed some big changes, but after careful look not _that_ much, so I can be lucky step by step switching back until found in what file changes start to be relevant for .psa loading.

**Comment by kas1e** [comment]
At least at the moment, i can say for sure that from this commit it is not changed in the stack.c/stack.h and shaderconv.c causes the issue. It's is exactly the remaining ones: which one reflects on the other so not sure if I can split them one by one to check where exactly.

**Comment by kas1e** [comment]
Yeah, once I put back those 17 files from pre-massive-vertex attrib commit, then .psa loading starts to work.

But I have some interesting news-details about it:

Interesting how it looks visually for one game which renders quite many details, so it not "black" on the second run. I.e. first run all fine, .psa creates. the Second run - loading from .psa - rendering heavily broken. And the third run (re-saved .psa?) gives a black screen.

See on images:

A first run:
![first_run](https://user-images.githubusercontent.com/664776/105610151-41435300-5dbf-11eb-836d-b77996d4fbfd.jpg)

A second run (with .psa)
![second_run](https://user-images.githubusercontent.com/664776/105610156-44d6da00-5dbf-11eb-8193-766256214d1c.jpg)

The third run with .psa gives a black screen.



I do check also with some very simple basic example (draw triangle), and trace a bit what happens so that what I see happens when I run it the first time:

```
... checked firstly usual shaders on 120, 300 es and 310 es, and then ...
Shell Process 'lesson04': W3DN_Submit: errCode 0 (W3DNEC_SUCCESS). Submit ID 7340859
Shell Process 'lesson04': W3DN_Query: query 14 (W3DN_Q_MAXVERTEXATTRIBS). Result 16
Shell Process 'lesson04': W3DN_Query: query 0 (W3DN_Q_MAXTEXUNITS). Result 32
Shell Process 'lesson04': OGLES2_glCreateProgram: created program 256
Shell Process 'lesson04': OGLES2_glCreateShader: type 0x8B31 (GL_VERTEX_SHADER). Created shader 256
Shell Process 'lesson04': OGLES2_glShaderSource: shader 256, count 1, string 0x5f2e660c length 0x0
Line 0: '#version 100
precision mediump float;
precision mediump int;
uniform highp mat4 _gl4es_ModelViewProjectionMatrix;
attribute highp vec4 _gl4es_Vertex;
attribute lowp vec4 _gl4es_Color;
// FPE_Shader generated
varying vec4 Color;

void main() {
gl_Position = _gl4es_ModelViewProjectionMatrix * _gl4es_Vertex;
Color = _gl4es_Color;
}
'
Shell Process 'lesson04': OGLES2_glCompileShader: shader 256
Shell Process 'lesson04': W3DN_CompileShader: errCode 0 (W3DNEC_SUCCESS), tags 0x55ec7d38 ([W3DNTag_DataBuffer: 0x55826848][W3DNTag_DataSize: 628][W3DNTag_Log: 0x55EC7D60][W3DNTag_LogLevel: 0]). Shader address 0x2863e798
```

So as can be seen, gl4es shader generated, compiles, and used.

Now, when I run a second time (with .psa), that what we have :

```
Shell Process 'lesson04': W3DN_Submit: errCode 0 (W3DNEC_SUCCESS). Submit ID 7350916
Shell Process 'lesson04': W3DN_Query: query 14 (W3DN_Q_MAXVERTEXATTRIBS). Result 16
Shell Process 'lesson04': W3DN_Query: query 0 (W3DN_Q_MAXTEXUNITS). Result 32
Shell Process 'lesson04': OGLES2_glCreateProgram: created program 256
Shell Process 'lesson04': OGLES2_aglGetProcAddress: name 'glProgramBinaryOES'. Address 0x7e6bb55c
Shell Process 'lesson04': W3DN_CompileShader: errCode 0 (W3DNEC_SUCCESS), tags 0x55ec7f38 ([W3DNTag_DataBuffer: 0x5E49D425][W3DNTag_DataSize: 628][W3DNTag_Log: 0x55EC7F60][W3DNTag_LogLevel: 0]). Shader address 0x2863e478
```

See, the difference is the OGLES2_aglGetProcAddress glProgramBinaryOES call.

So very possible that those massive changes in the VertexAttrib, somehow interact with aglGetProcAddress glPRogramBinaryOES call?

Maybe just something starts to be wrong with aglGetProcAddress after those changes about VertexAttrib?

**Comment by ptitSeb** [comment]
The call to `glProgramBinaryOES` is normal if a .psa archive is found: it's the function that allow loading a binary shader to GPU. If there is no .psa, then the shader is computed, compiled and linked. You'll have the same behaviour if you take a working build.

What still puzzle me is how the VA chnage can impact the psa handling...

**Comment by kas1e** [comment]
Yeah, the way how it works it's the same, just with build with vertex attrib changes it stops working, so I think that maybe somewhere missing ifdef, or maybe just GL4ES_LOAD_OES changed, or something of that sort... But what puzzle me even more, that it works for the first time! :)

**Comment by ptitSeb** [comment]
On this subject, I have a question (for Daniel): does the `glGetProgramBinary(...)`/`glProgramBinary(...)` handle `glBindAttribLocation(...)`? Because with that huge VA refactoring, fpe gl program now use `glBindAttribLocation(...)` were it wasn't the case before IIRC.

**Comment by kas1e** [comment]
Daniel says no, he didn't handle it :)  As unfortunately the spec's description sometimes sucks and he didn't get this detail. And so his glGetProgramBinary / glProgramBinary don't (re)store manual attribute bindings, which most likely is the reason for our broken .psa loading. Phew! One bug less then :)

**Comment by kas1e** [comment]
@ptitSeb 
After a while, Daniel add necessary stuff for glgetprogrammninary/et, so generated .psa works for us again now. 
So i close this one, thanks for help !
