### ISSUE TITLE
OpenMW's water shader flickers

### ISSUE THREAD

**Issue by AbduSharif** [ptitSeb/gl4es#269]
Latest commit seems to have the OpenMW interior lighting broken, it's mostly dark in them, and in exteriors too but somewhat lesser, it depends on camera movement so stuff will get lit or not is dependant on the camera angle, for example:
https://youtu.be/V7KxGRXcitw

Also the water shader sometimes flicker depending on the camera angle too, this was a bug before version 1.1.4, it was fixed in 1.1.4 and now it's returning.

**Comment by AbduSharif** [comment]
I'm using the latest nightly version of OpenMW and using OSG 3.6.5.

**Comment by AbduSharif** [comment]
There's also this warning spam from OSG in the OpenMW log, this warning spam wasn't present in OpenMW PC:
[03:05:07.567 W] Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)

**Comment by AbduSharif** [comment]
I was using this build:
https://github.com/AbduSharif/omw-android/actions/runs/504668777

**Comment by ptitSeb** [comment]
Is it the actual latest comit that broken it (e28f87abd6cb2013b4bee2f396efe488b28dce3f ) or just a figure of speech and it's broaken since some times?

**Comment by AbduSharif** [comment]
It may have been broken for sometime, I only recently tested the latest nightly of gl4es

**Comment by AbduSharif** [comment]
I was using this commit previously and OpenMW wasn't broken, only the warning spam from OSG is present:
498e11f8cbc80cf0255355db7af15ff6b954dff8

**Comment by AbduSharif** [comment]
OpenMW has this environment variable which is supposed to give detailed errors on OSG's warnings and errors in the OpenMW.log but I don't know how to use that with android:
-OPENMW_DEBUG_OPENGL=1

**Comment by psi29a** [comment]
Those are OpenGL info, warning, and error messages, not anything specific OSG.

**Comment by akortunov** [comment]
May be the same issue as #272, which is claimed to be introduced by a4486d5d65c299559e8e001ee17911221bf04c58.

**Comment by akortunov** [comment]
@AbduSharif, can you re-test upstream gl4es?

**Comment by AbduSharif** [comment]
This seems to have been fixed, there's still the warning from opengl but that's another issue for another day I guess, once we have a way of knowing why it happens.

**Comment by AbduSharif** [comment]
I was too hasty, the water shader flicker still exists.

**Comment by akortunov** [comment]
If this flickering is not present in 1.1.4, I only can suggest you to try to build different gl4es commits to determine when the issue appeared.

**Comment by AbduSharif** [comment]
The flicker seems to happen with refraction enabled, that was why I initially assumed it was fixed, but that was because I had refraction off then.

**Comment by AbduSharif** [comment]
While it seems that the bug with lighting and camera movement have been fixed, there seems to be another bug with how when you enter certain interiors the place gets dark for a few seconds and then gets lit (weirdly it happens in only a small number of interiors), and objects may flicker if an interior didn't get darker.

I haven't come across those with v1.1.4, and I can't get them on a video since they're pretty random.

**Comment by AbduSharif** [comment]
The water shader flicker, and I'm no longer sure it happens if  only when refraction is on, I guess I have to open my eyes more:
https://youtu.be/UuzYftiaZVU

**Comment by AbduSharif** [comment]
I finally know why the water shader flickers, I'll close this now as it became cluttered and I'll open a new issue for the water shader flicker and some related issues.
