### ISSUE TITLE
Question about draw buffers

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#274]
@ptitSeb 
Tried to port RedEclipse , and find out that it failed to run saying me that"
```Fatal error: Hardware does not support at least 4 draw buffers.```

Also when LIBGL query things, it returns:

```LIBGL: Max Color Attachments: 1 / Draw buffers : 1```

While in gl4es's config.h we have ```#define MAX_DRAW_BUFFERS    16``` 

The question is: what those "draw buffers" are? And is those ones didn't implemented on our side, or it some bug somewhere?

**Comment by kas1e** [comment]
From the game's code size it looks like this:
```
    glGetIntegerv(GL_MAX_DRAW_BUFFERS, &drawbufs);
    maxdrawbufs = drawbufs;
    if(maxdrawbufs < 4) fatal("Hardware does not support at least 4 draw buffers.");
```

Maybe it means aux buffers (an OpenGL 1 feature)?

**Comment by ptitSeb** [comment]
No, it's not aux buffers, is the ability to bind multiple color buffer to a single FBO.

**Comment by kas1e** [comment]
Is it something that should be implemented on our side in ogles2? How many Color Attachments / Draw Buffers you have on Pandora?

**Comment by ptitSeb** [comment]
Yes, it's on gles2 side, I don't have any workaround for that.
There is only 1 attachement on the Pandora, but 4 on an ODROID XU4 for example.

**Comment by kas1e** [comment]
Ok thanks, will then implement it later
