### ISSUE TITLE
OpenMW stretched textures

### ISSUE THREAD

**Issue by AbduSharif** [ptitSeb/gl4es#276]
- With the latest GL4ES nightly if I use this HD textures mod:
https://www.nexusmods.com/morrowind/mods/45247?tab=files
and compress and mipmap all it's textures that haven't been done (including the sky textures) using a tool named "Ordinator".

The sky also flickers when using the textures but it's more randomish, it doesn't happen if I try to use the default textures of Morrowind only, both seems connected because the water shader reflects the sky (now fixed).

- Second recent problem is ground textures (using mods or only default textures) look stretched and incorrect, probably because of this commit: https://github.com/ptitSeb/gl4es/commit/d8a2dc35ee49deea429aca316733f139e4bc597e (not fixed).

**Comment by AbduSharif** [comment]
![Uploading ground textures.jpg…]()

**Comment by AbduSharif** [comment]
![ground textures](https://user-images.githubusercontent.com/57298920/106941268-468f8e80-672b-11eb-8a8e-85031b72578f.jpg)

**Comment by AbduSharif** [comment]
Also side note: you can see in the picture OpenMW nightly finally supports grass instancing ;)
It works with gl4es but it doesn't have the best performance, it still works well for my device.

**Comment by AbduSharif** [comment]
This commit 7811022fef16183982ad99fce98c70d8e8df977d broke normal mapped textures rendering and water shader too:
![normalmapped_textures](https://user-images.githubusercontent.com/57298920/109827175-2ed0fa80-7c44-11eb-8f72-f79a70f7c183.jpg)
![texture_bug2](https://user-images.githubusercontent.com/57298920/109827184-309abe00-7c44-11eb-9008-485c718b798f.jpg)
![texture_bug3](https://user-images.githubusercontent.com/57298920/109827188-31335480-7c44-11eb-986a-ac70547158fc.jpg)

It didn't fix the bug with the stretched textures too:
![texture_bug1](https://user-images.githubusercontent.com/57298920/109827304-44debb00-7c44-11eb-8bf4-eb2592bf6cfd.jpg)

**Comment by AbduSharif** [comment]
Mipmapped Sky Textures work now though.

**Comment by ptitSeb** [comment]
I'll have to check on my side.
Not sure when, as I'm still working mainly on other stuffs.

I wasn't even aware of a "stretched textures" bug.
Too many issue are stacked on the same ticket.

**Comment by AbduSharif** [comment]
> I wasn't even aware of a "stretched textures" bug.
It's screenshot is above in the second post, it was there when I created the ticket.

**Comment by AbduSharif** [comment]
I'll put the normal mapped bug in another ticket, this current one isn't fixed though, so I won't close this.

**Comment by Sisah2** [comment]
This bug started to happen with d8a2dc35ee49deea429aca316733f139e4bc597e , not fixed with later commit, but hunting down that flickering of sky would be harder. There is more issues that overlap and some get fixed later.

**Comment by AbduSharif** [comment]
Flickering of sky with mipmapped textures is fixed.

**Comment by AbduSharif** [comment]
But there's instead flicker when crossing cell borders.

**Comment by Sisah2** [comment]
I think it dont have anything to do with mipmaped textures, i doubt sky even use mipmaps (why?).
Its still here when moving, looking around.

**Comment by AbduSharif** [comment]
With this the stretched textures look worse:
c3c172dc098dbd379420a3111b1142c4d7fbddd7

![stretched_textures_2](https://user-images.githubusercontent.com/57298920/112242305-3f2d3180-8c54-11eb-9f63-34e4448893f5.jpg)

**Comment by ptitSeb** [comment]
Yes, I reproduce the issue on my side. I'll work on that.

**Comment by AbduSharif** [comment]
Thanks for relentlessly trying to fix this, the issue is resolved now.

There was flicker at cell changes but that seems to have gone.

There was also a weird issue with water shader being black when first opening the game but that seems to have gone fixed too.

**Comment by Sisah2** [comment]
For me flickering sky/water/sometimes objects is still here.
