### ISSUE TITLE
FB pbuffer mode broken on a framebuffer-only device?

### ISSUE THREAD

**Issue by MagaTailor** [ptitSeb/gl4es#28]
Continuing from #27, here's what gl4es tells us after enabling `DEBUG` in `framebuffer.c` and `glx.c`;

`LIBGL_FB=1  glxgears` produces a black window and this output:
```shell 
LIBGL: Initialising gl4es
LIBGL: v0.9.7 built on Jun 18 2017 21:20:56
LIBGL: framebuffer output enabled
LIBGL:loaded: libGLESv1_CM.so
LIBGL:loaded: libEGL.so
LIBGL: Extension glBlendColor found and used
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_cube_map detected and used
LIBGL: Extension GL_OES_draw_texture detected and used
LIBGL: Max texture size: 4096
LIBGL: Texture Units: 8, Max lights: 8, Max planes: 1
LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5
LIBGL: Current folder is:/home/odroid/gl4es
glXChooseVisual(0x235d6760, 0, 0x7ffe098c98)
glXChooseFBConfig(0x235d6760, 0, 0x7ffe098c98, 0x7ffe098b24)
FBConfig redBits=1
FBConfig greenBits=1
FBConfig blueBits=1
FBConfig depthBits=1
glXCreateContext(0x235d6760, 0x235e5f50, (nil), 1), latest_visual=0x235e5f50, fbcontext_count=0 => 0x235e5fe0
LIBGL: ERROR: EGL Error detected: EGL_BAD_MATCH (0x0)
glXMakeCurrent(0x235d6760, 0x2c00002, 0x235e5fe0), isPBuffer(drawable)=0, context->drawable=(nil), context->eglSurface=(nil) => False
glXQueryExtensionString(0x235d6760, 0)
glXQueryDrawable(0x235d6760, 0x2c00002(0), GLX_SWAP_INTERVAL_EXT, 0x7ffe098e68 = 0)
300109 frames in 5.0 seconds = 60021.801 FPS
299919 frames in 5.0 seconds = 59983.754 FPS
````
whereas `LIBGL_FB=2` also this:
```shell
glXChooseVisual(0x1cc2e760, 0, 0x7fdf99b438)
glXChooseFBConfig(0x1cc2e760, 0, 0x7fdf99b438, 0x7fdf99b2c4)
FBConfig redBits=1
FBConfig greenBits=1
FBConfig blueBits=1
FBConfig depthBits=1
glXCreateContext(0x1cc2e760, 0x1cc3df50, (nil), 1), latest_visual=0x1cc3df50, fbcontext_count=0 => 0x1cc3dfe0
LIBGL: ERROR: EGL Error detected: EGL_BAD_MATCH (0x0)
glXMakeCurrent(0x1cc2e760, 0x2c00002, 0x1cc3dfe0), isPBuffer(drawable)=0, context->drawable=(nil), context->eglSurface=(nil) => False
glXQueryExtensionString(0x1cc2e760, 0)
glXQueryDrawable(0x1cc2e760, 0x2c00002(0), GLX_SWAP_INTERVAL_EXT, 0x7fdf99b608 = 0)
LIBGL: warning, gles_glBindFramebuffer is NULL
LIBGL: warning, gles_glBindFramebuffer is NULL
LIBGL: warning, gles_glCheckFramebufferStatus is NULL
301370 frames in 5.0 seconds = 60273.914 FPS
````

and finally, `LIBGL_FB=3` actually produces some moving sprites inside of the window:
```shell
glXChooseVisual(0x1a95c760, 0, 0x7fe9c253d8)
glXChooseFBConfig(0x1a95c760, 0, 0x7fe9c253d8, 0x7fe9c25264)
FBConfig redBits=1
FBConfig greenBits=1
FBConfig blueBits=1
FBConfig depthBits=1
glXCreateContext(0x1a95c760, 0x1a96bf50, (nil), 1), latest_visual=0x1a96bf50, fbcontext_count=0 => 0x1a96bfe0
glXMakeCurrent(0x1a95c760, 0x2c00002, 0x1a96bfe0), isPBuffer(drawable)=0, context->drawable=(nil), context->eglSurface=(nil)XGetGeometry gives 300x300 for drawable 0x2c00002
 => True
glXQueryExtensionString(0x1a95c760, 0)
glXQueryDrawable(0x1a95c760, 0x2c00002(1), GLX_SWAP_INTERVAL_EXT, 0x7fe9c255a8 = 0)
readfboBegin, fbo status read=0, draw=0, main=0, current=0
readfboEnd, fbo status read=0, draw=0, main=0, current=0
````
This is being tried on a system running at 720p/24bpp. The shim was compiled for ODROID which might be a wrong choice for a framebuffer system, as trying to use X11 fails with:

`glXCreateContext(0x3c02a760, 0x3c039f50, (nil), 1), latest_visual=0x3c039f50, fbcontext_count=0 => (nil)`

Anything actionable here or is the system simply broken?

**Comment by ptitSeb** [comment]
You can try to force 565 FrameBuffer, just in case (like on the Pandora).

In gx/glx.c, for functions `gl4es_glXCreateContext` and `gl4es_glXCreateContextAttribsARB` try to activate the PANDORA code (by changing the `#ifdef PANDORA` to `#if 1` for example).

**Comment by MagaTailor** [comment]
I activated a `PANDORA` define for lines 418-429  but that didn't make any difference.

**Comment by ptitSeb** [comment]
the one in line 412, 523 and 641 may also help.

**Comment by MagaTailor** [comment]
Did that everywhere and there's no visible difference in glxgears but I'm not sure why torcs seems to start fine but there's no performance difference compared to mesa. Probably related to this:

```shell
glXMakeContextCurrent(0x2c7beed0, 3000002, 3000002, 0x2c7c0240)
glXMakeCurrent(0x2c7beed0, 0x3000002, 0x2c7c0240), isPBuffer(drawable)=0, context->drawable=0x3000002, context->eglSurface=(nil) => True
Same context and drawable, doing nothing
````

**Comment by ptitSeb** [comment]
the log from torcs looks fine. The "doing nothing" is harmless, and is just an optimisation when activating a context that is already active.
You tried torcs with `LIBGL_FB=1` or `LIBGL_FB=3`. 
Can you run `eglinfo` to check if the GLES driver isn't mesa software?

**Comment by MagaTailor** [comment]
Only `LIBGL_FB=3` sort of works so that's what I'm forced to use every time.

Good idea vis. eglinfo cause I compiled it early on but never tried it as root.

**Comment by MagaTailor** [comment]
````
root@amlogic:/home/odroid#  eglinfo 
Using default X11 display

Could not obtain EGL display
````

The egl/gles libraries are correctly symlinked to `libMali` but the performance in torcs points to 100% software rendering (and no visual glitches, definitely wrong :) )

```shell
root@amlogic:/home/odroid# LIBGL_FB=3 torcs 
LIBGL: Initialising gl4es
LIBGL: v0.9.7 built on Jun 18 2017 23:26:51
LIBGL: using pbuffer
LIBGL:loaded: libGLESv1_Croot@amlogic:/home/odroid#  eglinfo 
Using default X11 display

Could not obtain EGL displayM.so
LIBGL:loaded: libEGL.so
LIBGL: Extension glBlendColor found and used
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_OES_texture_cube_map detected and used
LIBGL: Extension GL_OES_draw_texture detected and used
LIBGL: Max texture size: 4096
LIBGL: Texture Units: 8, Max lights: 8, Max planes: 1
LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5
LIBGL: Current folder is:/usr/share/games/torcs
glXQueryExtension(0x207f0ed0, (nil), (nil))
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
glXChooseFBConfig(0x207f0ed0, 0, 0x7ffc53fa20, 0x7ffc53fa14)
FBConfig redBits=1
FBConfig greenBits=1
FBConfig blueBits=1
FBConfig depthBits=1
glXGetVisualFromFBConfig(0x207f0ed0, 0x7f7fb66b38)
glXCreateNewContext(0x207f0ed0, 0x7f7fb66b38, 32788, (nil), 1), drawableType=0x01
glXCreateContextAttribsARB(0x207f0ed0, 0x7f7fb66b38, (nil), 1) config is RGBA:1110, depth=1, stencil=8, drawable=1
glXIsDirect(0x207f0ed0, 0x207f2240)
glXMakeContextCurrent(0x207f0ed0, 2800002, 2800002, 0x207f2240)
glXMakeCurrent(0x207f0ed0, 0x2800002, 0x207f2240), isPBuffer(drawable)=0, context->drawable=(nil), context->eglSurface=(nil)XGetGeometry gives 640x480 for drawable 0x2800002
 => True
glXMakeContextCurrent(0x207f0ed0, 2800002, 2800002, 0x207f2240)
glXMakeCurrent(0x207f0ed0, 0x2800002, 0x207f2240), isPBuffer(drawable)=1, context->drawable=0x2800002, context->eglSurface=0x20000001 => True
Same context and drawable, doing nothing
glXGetCurrentContext()
LIBGL: warning, gles_glBlendFuncSeparate is NULL
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e g happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
glXMakeContextCurrent(0x207f0ed0, 2800002, 2800002, 0x207f2240)
glXMakeCurrent(0x207f0ed0, 0x2800002, 0x207f2240), isPBuffer(drawable)=1, context->drawable=0x2800002, context->eglSurface=0x20000001 => True
Same context and drawable, doing nothing
````

This setup is probably broken. Could be the kernel part.

**Comment by ptitSeb** [comment]
Well, it seem the egl driver cannot connect to X11 Display at all.
So only `LIBGL_FB=3` seems usable. But that mode implies an offscreen rendering to a PBuffer (only thing that egl driver seems to be abble to work with) and then a glReadPixels + blit on X11 window for each frame. That can be a bit long, because of the blitting. So maybe it does render, but all performances are lost with the blit...

What you can do also is, in glx/hardext.c line 143, is to activate PANDORA code again (by using a `#if 0` here), to avoid using a glReadPixels on GL_RGB/565, may be it will speedup the blit.
Or, alternatively, you can, in glx/glx.c, activate PANDORA code in the Blit portion, at the end of the file for the functions `actualBlit` and `BlitEmulatedPixmap`

**Comment by MagaTailor** [comment]
Tried that but it seems the FPS are identical to the tenth of a frame to mesa GL. 

I have no idea how that's possible, (lsof shows `libMali` is opened by torcs) but maybe Mali knows how to fall back on soft rendering. (there are no glitches and IIRC it shouldn't be possible for unpatched torcs)

So the only real puzzle here is `glxgears` which produces garbled output. (sign of actually using some hardware?)

**Comment by ptitSeb** [comment]
I think torcs should work with no visual artifact now with gl4es. The patch are mainly for speed, not rendering.
Can you try a couple more program maybe, just to try understand what's happening (there are quite a few GL program on my github if you don't want to look for simple software, like StuntCarRemake, CandyCrisis or Prototype).

**Comment by MagaTailor** [comment]
Sure, with no SDL apps to choose from, which ones do you recommend?

**Comment by ptitSeb** [comment]
No SDL apps? Why SDL and/or SDL2 doesn't build ?

Prototype may work (but it use SDL_mixer). The Jedi Knight serie should also.

**Comment by MagaTailor** [comment]
Let me check, maybe I've remembered SDL didn't work for some other reason.

**Comment by MagaTailor** [comment]
Oops, you were right, other games show different effects of using gl4es (tried foobillardplus and armagetronad so SDL is fine too).

Performance is nearly identical to mesa (went back to a no-debug build of gl4es) but armagetronad is broken, with large parts of the screen going black.

I'll do some more testing tomorrow.

**Comment by MagaTailor** [comment]
No use keeping this open; the platform is too hacked-up at the moment.
