### ISSUE TITLE
OpenMW normal mapped textures don't work

### ISSUE THREAD

**Issue by AbduSharif** [ptitSeb/gl4es#285]
This commit 7811022fef16183982ad99fce98c70d8e8df977d broke normal mapped textures and water shader rendering in OpenMW:
![normalmapped_textures](https://user-images.githubusercontent.com/57298920/109846342-c2132b80-7c56-11eb-83ec-e787ed4e7e4e.jpg)
![texture_bug2](https://user-images.githubusercontent.com/57298920/109846346-c3dcef00-7c56-11eb-8dc0-8cd6ed1b344c.jpg)

**Comment by AbduSharif** [comment]
The water shader uses a normal mapped texture.

**Comment by akortunov** [comment]
Usually the game looks like this when shaders failed to compile for some reason, so in theery there should be errors in OpenMW logs.

**Comment by AbduSharif** [comment]
That's true, I'm seeing alot of errors.
[openmw.log](https://github.com/ptitSeb/gl4es/files/6092322/openmw.log)

**Comment by Sisah2** [comment]
Its actually f10c86b2941650cffbd0c1c2e383284184506c66 that break openmw shaders.

**Comment by ptitSeb** [comment]
Oh, interresting.
Do you have the error message when the shader fail to compile?

**Comment by Sisah2** [comment]
I dont know maybe this help?

> 03-08 12:29:06.144  8762 12967 I LIBGL   : varying vec2 decalMapUV;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 25
03-08 12:29:06.144  8762 12967 I LIBGL   : #if 0
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform sampler2D emissiveMap;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 29
03-08 12:29:06.144  8762 12967 I LIBGL   : #if 0
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform sampler2D normalMap;
03-08 12:29:06.144  8762 12967 I LIBGL   : varying vec4 passTangent;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 34
03-08 12:29:06.144  8762 12967 I LIBGL   : #if 0
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform sampler2D envMap;
03-08 12:29:06.144  8762 12967 I LIBGL   : varying vec2 envMapUV;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform vec4 envMapColor;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 40
03-08 12:29:06.144  8762 12967 I LIBGL   : #if 0
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform sampler2D specularMap;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 44
03-08 12:29:06.144  8762 12967 I LIBGL   : #if 0
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform sampler2D bumpMap;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform vec2 envMapLumaBias;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform mat2 bumpMapMatrix;
03-08 12:29:06.144  8762 12967 I LIBGL   : #endif
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 50
03-08 12:29:06.144  8762 12967 I LIBGL   : #define PER_PIXEL_LIGHTING (0 || (1))
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : #line 0 1
03-08 12:29:06.144  8762 12967 I LIBGL   : //#define LINEAR_LIGHTING
03-08 12:29:06.144  8762 12967 I LIBGL   : #define ATTEN_FIX
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : // contrast for day and night
03-08 12:29:06.144  8762 12967 I LIBGL   : // night setting also affects interiors
03-08 12:29:06.144  8762 12967 I LIBGL   : const float conday = 1.0;
03-08 12:29:06.144  8762 12967 I LIBGL   : const float connight = 0.75;
03-08 12:29:06.144  8762 12967 I LIBGL   : 
03-08 12:29:06.144  8762 12967 I LIBGL   : // self shadow
03-08 12:29:06.144  8762 12967 I LIBGL   : ShaderConv Source is:
03-08 12:29:06.144  8762 12967 I LIBGL   : #version 310 es
03-08 12:29:06.144  8762 12967 I LIBGL   : #define attribute in
03-08 12:29:06.144  8762 12967 I LIBGL   : #define _gl4es_MaxLights 8
03-08 12:29:06.144  8762 12967 I LIBGL   : #define varying out
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform highp mat4 _gl4es_IModelViewMatrix;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform highp mat4 _gl4es_ModelViewMatrix;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform highp mat3 _gl4es_NormalMatrix;
03-08 12:29:06.144  8762 12967 I LIBGL   : struct _gl4es_LightSourceParameters
03-08 12:29:06.144  8762 12967 I LIBGL   : {
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 ambient;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 diffuse;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 specular;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 position;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 halfVector;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec3 spotDirection;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float spotExponent;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float spotCutoff;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float spotCosCutoff;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float constantAttenuation;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float linearAttenuation;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float quadraticAttenuation;
03-08 12:29:06.144  8762 12967 I LIBGL   : };
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform _gl4es_LightSourceParameters _gl4es_LightSource[_gl4es_MaxLights];
03-08 12:29:06.144  8762 12967 I LIBGL   : struct _gl4es_LightModelParameters {
03-08 12:29:06.144  8762 12967 I LIBGL   :   vec4 ambient;
03-08 12:29:06.144  8762 12967 I LIBGL   : };
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform _gl4es_LightModelParameters _gl4es_LightModel;
03-08 12:29:06.144  8762 12967 I LIBGL   : struct _gl4es_MaterialParameters
03-08 12:29:06.144  8762 12967 I LIBGL   : {
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 emission;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 ambient;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 diffuse;
03-08 12:29:06.144  8762 12967 I LIBGL   :    vec4 specular;
03-08 12:29:06.144  8762 12967 I LIBGL   :    float shininess;
03-08 12:29:06.144  8762 12967 I LIBGL   : };
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform _gl4es_MaterialParameters _gl4es_FrontMaterial;
03-08 12:29:06.144  8762 12967 I LIBGL   : uniform _gl4es_MaterialParameters _gl4es_BackMaterial;
03-08 12:29:06.144  8762 12967 I LIBGL   : struct _gl4es_FogParameters {
03-08 12:29:06.144  8762 12967 I LIBGL   :     lowp vec4 color;
03-08 12:29:06.144  8762 12967 I LIBGL   :    
03-08 12:29:06.144  8762 12967 I LIBGL   : Compiler message is
03-08 12:29:06.144  8762 12967 I LIBGL   : 6:110: L0002: Undeclared variable 'gl_FragData'
03-08 12:29:06.144  8762 12967 I LIBGL   : 0:171: L0002: Undeclared variable 'gl_FragData'
03-08 12:29:06.144  8762 12967 I LIBGL   : 0:174: L0002: Undeclared variable 'gl_FragData'
03-08 12:29:06.144  8762 12967 I LIBGL   : LIBGL: End of Error log


source is definitely not 310 version, they are 120

**Comment by Sisah2** [comment]
Removing changes from preproc.c introduced in f10c86b2941650cffbd0c1c2e383284184506c66 allow them to compile fine.

**Comment by Sisah2** [comment]
Nice, thanks, it helped. stretched terrain textures and some weird flickering remain for openmw :D

**Comment by AbduSharif** [comment]
It's working now so I'm closing.
