### ISSUE TITLE
GLES2: Double free when trying to run glmark2

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/gl4es#29]
I'm trying to run glmark2 on the ES2 backend of GL4ES. The ES2 driver is the one of Mesa.

When finish running the first test and switch to the second one, the following error shows:
*** Error in `glmark2': double free or corruption (fasttop): 0x0000564125337990 ***

**Comment by Icenowy** [comment]
GDB says that the code that triggers this error is src/gl/program.c:131

Commit hash is 191f2fc91b6fcea79ac5e5d051417e28c0f2c2d0

**Comment by ptitSeb** [comment]
Thanks for the detailled bug repport. I'll look at fixing that soon.

**Comment by ptitSeb** [comment]
Should be fixed with a6d15fba1621db327d3b6b470eec83d2ec20a645

**Comment by Icenowy** [comment]
It now doesn't abort, however the image in the window stucks when switching test, and the FPS changed a lot: (62 should be vsync'ed value)

[build] use-vbo=false: FPS: 62 FrameTime: 16.129 ms
[build] use-vbo=true: FPS: 3366 FrameTime: 0.297 ms

**Comment by ptitSeb** [comment]
Yes, I have noticed there are some issue with glX context creation with glmark2. I need to analyse more this bug.

**Comment by ptitSeb** [comment]
It should be fixed with 44031a58f42349f2ba3d5dddbfa9814b98e47568

**Comment by Icenowy** [comment]
Yes, it's fixed.

The only problem now on glmark2 is that the vsync is still enabled (I think glmark2 will try to disable it with GLX_EXT_swap_control or GLX_MESA_swap_control)

**Comment by ptitSeb** [comment]
SwapInteval function was already supported. But Ihave added a few refinements with 03a213e5c98dfb9d689146b4eeff95ed01ed61fc

Also, if an interval is set to a value the GLES hardware doesn't support, you see a warning now.

(uncomment https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L34 to have logs of the call, you'll see `glXSwapInterval(0)` is called, wich call `eglSwapInterval(eglDisplay, 0)`)

**Comment by ptitSeb** [comment]
I think I can close this ticket.
