### ISSUE TITLE
Multisample FBO setup handling question

### ISSUE THREAD

**Issue by AbduSharif** [ptitSeb/gl4es#290]
OpenMW now supports alpha2coverage but to use it you need OpenMW's antialiasing but when enabling OpenMW's antialiasing option (I set it to 2) I get this error:
[12:56:47.635 W] RenderStage::runCameraSetUp(), multisample FBO setup failed, FBO status = 0x8cd6

And the character preview is sometimes black or white (because of it):

![black_review_2](https://user-images.githubusercontent.com/57298920/111092736-90943d00-853f-11eb-931d-d58889d07c13.jpg)

Does gl4es support it?

**Comment by AbduSharif** [comment]
(Sorry for the blurred picture, my photo editor got a bad update).

**Comment by ptitSeb** [comment]
No support for multisample FBO is faked in gl4es for now.
