### ISSUE TITLE
Maybe better to rename project from gl4es to gl2es?

### ISSUE THREAD

**Issue by AKonia** [ptitSeb/gl4es#291]
pros:
- no misunderstanding with gl4 association
- self-explanation of translation way gl2 -> es

**Comment by ptitSeb** [comment]
gl2es already exist.

**Comment by ptitSeb** [comment]
Yes, now gl4es is pretty well known, but when I first searched for a name, I got many hits with gl2es, so I choose gl4es as a name.

**Comment by AKonia** [comment]
Ok, it makes sense.
