### ISSUE TITLE
GLU Not Implemented

### ISSUE THREAD

**Issue by DanTheMan827** [ptitSeb/gl4es#292]
I'm trying to build a game that uses GLU, but methods like gluScaleImage, and gluBuild2DMipMaps aren't defined.

Could the GLU methods be implemented, or am I looking in the wrong place? I see you include the headers for GLU

**Comment by ptitSeb** [comment]
libGLU is a separate library.
You can find sources on the web, or you use my repo here: https://github.com/ptitSeb/GLU if you want
I will not merge GLU inside gl4es.

**Comment by DanTheMan827** [comment]
Ok, thanks
