### ISSUE TITLE
The gl4es shader

### ISSUE THREAD

**Issue by Minecraftmodster** [ptitSeb/gl4es#318]
When will it be released and what will it look like?
 
That's all i had to say.

**Comment by khanhduytran0** [comment]
@Minecraftmodster bruh
gl4es ≠ Open4ES

**Comment by khanhduytran0** [comment]
gl4es is not a shader.

**Comment by Minecraftmodster** [comment]
Well every 

> gl4es is not a shader.

Well everybody was talking about it on open4es shader

**Comment by khanhduytran0** [comment]
But this repository is gl4es, OpenGL to OpenGL ES renderer, NOT shader.

**Comment by Minecraftmodster** [comment]
> But this repository is gl4es, OpenGL to OpenGL ES renderer, NOT shader.

Well i didn't know bro damn well sorry for thinking it was a shader but have a nice day!

**Comment by khanhduytran0** [comment]
lmao

**Comment by Minecraftmodster** [comment]
Oh wait before i go i wanted to say if you knew when another update of open4es is going to come out you probably don't but i don't know that so that why i want to know

**Comment by khanhduytran0** [comment]
> goto https://github.com/Open4Es
