### ISSUE TITLE
Can gl4es Support X11 Android ?

### ISSUE THREAD

**Issue by AllPlatform** [ptitSeb/gl4es#319]
information
NDK android-ndk-r21e and X11 Cross-platform BY Termux

eglinfo [Link To Github eglinfo!](https://github.com/JoakimSoderberg/mesademos/blob/master/src/egl/opengl/eglinfo.c)
`clang -o eglinfo eglinfo.c -lEGL`
glxinfo [Link To github glxinfo](https://github.com/VirtualGL/virtualgl/blob/main/glxdemos/glxinfo.c)
`clang -o glxinfo glxinfo.c -lX11 -lGL`
glxgears [Link To github glxgears](
https://github.com/davidanthonygardner/glxgears/blob/master/glxgears.c)
`clang -o glxgears glxgears.c -lX11 -lGL`
I modified `box86/CMakelist.txt` and  `box86/src/CMakelist.txt`, with Here is LOG

>eglinfo
[eglinfo.log](https://github.com/ptitSeb/gl4es/files/6681839/eglinfo.log)

>glxinfo LIBGL_FB= 1 to 3 [ Not Work ]
[glxinfo_LIBGL_FB=1,2,3.log](https://github.com/ptitSeb/gl4es/files/6681840/glxinfo_LIBGL_FB.1.2.3.log)

>glxinfo LIBGL_FB=3 Worked /vendor/lib/egl/
libEGL_adreno.so
libGLESv2_adreno.so
[glxinfoFB=3.log](https://github.com/ptitSeb/gl4es/files/6681842/glxinfoFB.3.log)

>glxgear [ Crash Black Screen ] LIBGL_FB=3
[glxgearsFB=3.log](https://github.com/ptitSeb/gl4es/files/6681856/glxgearsFB.3.log)

Do you have any ideas? Or any further information my devices? 
i think that gl4es was not originally designed for android so some linux and android EGL extensions are very different like `EGL_ANDROID` Or Android Not Have EGL clinet
Thank you for looking at the issue

**Comment by ptitSeb** [comment]
gl4es works with what the GLES driver can work with. If the GLES driver support X11, it will work with `LIBGL_FB=0`. If it support Framebuffer, it will work with `LIBGL_FB=1` and `LIBGL_FB=2`. If it support OfScreen rendering (most do), it will support `LIBGL_FB=3` (but the speed of that one may not be optimal, as the blitting from offscreen to screen is not free). If there is some GBM support and gl4es has been built with it, `LIBGL_FB=4` might work (but this one is still WIP).

**Comment by AllPlatform** [comment]
Sad Android Have no `libgbm.so` I only see there are related files like `libdrm.so` i don't know if it will work i will try again
