### ISSUE TITLE
About a custom  GLES library and gl4es

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#321]
Recently, well, I have built a simple custom GLES translation library, which only calls GLES(2 or 3) without EGL, I put it into pojav, which provides the EGL context, to run. and it can print custom OpenGL information in the output log of POJAV (such as printing OpenGL4.4). However, I found that the maximum size of the printed texture was always -1x-1, whereas for this device it was 16384x16384. I tried to change the function to query the texture size, but it didn't work, and the MC startup screen didn't render. I then went to check the output log of GL4ES and it loaded EGL and printed the Eglimage2D support and then its texture calls were fine and it rendered the MC startup screen. I even saw GLX recycling the EGL surface. I'd like to know some reasons and details.

**Comment by luo9674** [comment]
![Uploading Screenshot_2021-07-19-12-28-50-297_com.kmplayer.jpg…]()

**Comment by ptitSeb** [comment]
you close the ticket as soon as open it?
