### ISSUE TITLE
About a custom GLES library and gl4es

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#322]
Recently, well, I have built a simple custom GLES translation library, which only calls GLES(2 or 3) without EGL, I put it into pojav, which provides the EGL context, to run. and it can print custom OpenGL information in the output log of POJAV (such as printing OpenGL4.4). However, I found that the maximum size of the printed texture was always -1x-1, whereas for this device it was 16384x16384. I tried to change the function to query the texture size, but it didn't work, and the MC startup screen didn't render. I then went to check the output log of GL4ES and it loaded EGL and printed the Eglimage2D support and then its texture calls were fine and it rendered the MC startup screen. I even saw GLX recycling the EGL surface. I'd like to know some reasons and details.

**Comment by luo9674** [comment]
Sorry I made a little mistake just now so I reopened the question please forgive me but the content is the same

**Comment by luo9674** [comment]
I want to know how GL4ES returns a maximum texture size, I tried an integerI want to know how GL4ES returns a maximum texture size, I tried to return a value directly in glGetInteger, but it didn't work. (Or something else, it seems that MC first calls glTexImage2D, then fails, then returns a texture size of -1.)

**Comment by ptitSeb** [comment]
that part is done in `hardext.c` file.
All information are grabbed using a temporary pBuffer only context.
