### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#324]
It goes like this:
I want to add a little GL function of my own to gl4ES,

1.
Create a.c under src/gl/ and write the following statement:
![IMG_20210722_235216](https://user-images.githubusercontent.com/85796761/126729884-9fb823dd-c1a2-491c-886b-063271e33b23.jpg)
2.
src/gl/gether.c
![IMG_20210722_234449](https://user-images.githubusercontent.com/85796761/126729939-b5441d71-1c8c-4230-87d7-004141d8b21e.jpg)
(To prevent redefining functions from causing errors;)
3.
Then compile (a.c + gl4es) with no error;
Run, however I find the output panel prints the original "version 2.1",
Does this mean that statements in a.c are not called?

I tried to add some new GL3.0 functions to GL4ES (a.c),
But output panel printing:
![IMG_20210722_234534](https://user-images.githubusercontent.com/85796761/126730061-591f07f5-bf98-4fa7-a2d0-b2b30107e5a3.jpg)

Does this mean that the function in a.c was not detected?
But if I compile a.c separately, the output panel prints:
Capabilities: -2.0-2.1-3.0 --
It's a little strange;
Is it caused by gl4es initialization?
I want to know what went wrong. thank you.

**Comment by ptitSeb** [comment]
With gl4es, your glGetString will not be called, because gl4es already have one. Also, using glXGetProcAddress will redirect to gl4es_glGetString

I want to stress out that adding GL 3.0 to gl4es, or doing GLES3.0->GL3.0 conversion is a complex task.

**Comment by luo9674** [comment]
> With gl4es, your glGetString will not be called, because gl4es already have one. Also, using glXGetProcAddress will redirect to gl4es_glGetString
> 
> I want to stress out that adding GL 3.0 to gl4es, or doing GLES3.0->GL3.0 conversion is a complex task.

Maybe I just want to add hardware support for MRT and shader. But that means I can add new functions by modifying glXGetProcAddress?

**Comment by ptitSeb** [comment]
Multiple Render Target is already supported in gl4es

GL3.0 Shader is complex, because it's not just "shaders" but all the functions associated, so, basically, almost all GL3.0 specs.

the glXGetProcAddress is in 2 part. One in `glx/lookup.c`, the other in `gl/gl_lookup.c`

**Comment by luo9674** [comment]
> Multiple Render Target is already supported in gl4es
> 
> GL3.0 Shader is complex, because it's not just "shaders" but all the functions associated, so, basically, almost all GL3.0 specs.
> 
> the glXGetProcAddress is in 2 part. One in `glx/lookup.c`, the other in `gl/gl_lookup.c`

Okay, I see how it works: customizable redirection.

**Comment by luo9674** [comment]
> gl4es 已经支持多渲染目标
> 
> GL3.0 着色器很复杂，因为它不仅仅是“着色器”，而是所有相关的功能，因此，基本上，几乎所有 GL3.0 规范。
> 
> glXGetProcAddress 分为两部分。一个在`glx/lookup.c`，另一个在`gl/gl_lookup.c`

Do I have to use the GL2.1 extension to use the MRT of gl4es1.1.4?

**Comment by luo9674** [comment]
> Multiple Render Target is already supported in gl4es
> 
> GL3.0 Shader is complex, because it's not just "shaders" but all the functions associated, so, basically, almost all GL3.0 specs.
> 
> the glXGetProcAddress is in 2 part. One in `glx/lookup.c`, the other in `gl/gl_lookup.c
