### ISSUE TITLE
segfault after Using GLES 2.0 backend

### ISSUE THREAD

**Issue by seisdr** [ptitSeb/gl4es#325]
root@localhost:~# glxgears                                             LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jul 23 2021 11:53:13                            LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so                                            LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend                                          Segmentation fault

**Comment by khanhduytran0** [comment]
~~chroot in android moment? how do you think Android OpenGL implementation can communicate with X11?~~ (actually `LIBGL_FB=3` is the solution)

**Comment by seisdr** [comment]
LIBGL_FB=3 glxgears
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jul 23 2021 11:53:13
LIBGL: using pbuffer
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
Segmentation fault

**Comment by ptitSeb** [comment]
I know nothing of your configuration and how you build gl4es. You need to gives some detail here!

**Comment by seisdr** [comment]
well first i did build or compile libhybris on i386 environment with android 5.1 headers when mine 7.1 probbly not an issue then i compile gl4es `mkdir build ; cd build ; cmake .. ; make`
on termux

**Comment by seisdr** [comment]
and i did move gl4es libGL.so.1 to /usr/lib/i386-linux-gnu/libGL.so.1

**Comment by ptitSeb** [comment]
It seems to crash when intializing EGL (probably at `eglInitialize(...)`), but I don't know why.

**Comment by seisdr** [comment]
maybe i need to build libhybris on arm64 not i386 ?

**Comment by ptitSeb** [comment]
I don't know. I'm not familiar with libhybris and running box86 under android. Can you use EGL and GLESv2 without gl4es? like with glmark2-gles2 or esgrears (not sure of the name)?

**Comment by seisdr** [comment]
well i did setup arm64 env and installed those 
```
libglapi-mesa/hirsute,now 21.0.1-2 arm64 [installed,automatic]
  free implementation of the GL API -- shared library

libgles2/hirsute,now 1.3.2-1 arm64 [installed]
  Vendor neutral GL dispatch library -- GLESv2 support

libgles2-mesa/hirsute,now 21.0.1-2 arm64 [installed]
  transitional dummy package

libgles2-mesa-dev/hirsute,now 21.0.1-2 arm64 [installed]
  transitional dummy package
``
i found them by searching gles2 on ubuntu 20 env idid build gl4es and tried and it worked but how do i know im not using software graphics? 
```
 root@localhost:~# glxgears
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Jul 23 2021 14:03:26
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays  detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
LIBGL: Max Color Attachments: 8 / Draw buffers: 8
LIBGL: Hardware vendor is Mesa/X.org
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: sRGB surface supported
LIBGL: EGLImage to Texture2D supported
LIBGL: EGLImage to RenderBuffer supported
LIBGL: Targeting OpenGL 2.1
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/root
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
844 frames in 5.0 seconds = 168.664 FPS
^C
root@localhost:~#
```

**Comment by seisdr** [comment]
yes this is software

**Comment by seisdr** [comment]
yes this is software
