### ISSUE TITLE
How to close the shader precompiler

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#332]
I found in the debug log that two copies of the shader compile error message are printed, one of which seems to be for gl4es. I want to close it, where should I change the code?

**Comment by ptitSeb** [comment]
I don't undertand the question and what you want to do.

**Comment by luo9674** [comment]
> I don't undertand the question and what you want to do.

Well, what I should have meant to say is that once the application has compiled the shader, it looks like gl4es will compile it again.

**Comment by ptitSeb** [comment]
The application doesn't compile the shader: the app call `glCompileShader(...)` that is in fact `gl4es_glCompileShader(...)` and will compile the shader.
However, depending on the shaders and GL state, a new shader might be created by gl4es (like, for example, to handle Alpha Test that is not supported on GLES2).

**Comment by luo9674** [comment]
> The application doesn't compile the shader: the app call `glCompileShader(...)` that is in fact `gl4es_glCompileShader(...)` and will compile the shader.
> However, depending on the shaders and GL state, a new shader might be created by gl4es, based on the original shader code (like, for example, to handle Alpha Test that is not supported on GLES2).

Whether to recreate a shader is through this function: redoShader(...)

**Comment by ptitSeb** [comment]
The main function that apply GL state before drawing in `realize_glenv(...)`
Check if shader needs a new variant is between lines 1065-1106 roughly.

**Comment by luo9674** [comment]
> The main function that apply GL state before drawing in `realize_glenv(...)`
> Check if shader needs a new variant is between lines 1065-1106 roughly.

OK
