### ISSUE TITLE
How to get the signal at the end of a frame

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#333]
I want to get the signal at the start or end of a frame when gl4es renders so I can do some counting and gl4es can print FPS, so how does gl4es do it? Or how do I get a fake vertical sync signal for gl4es?

**Comment by ptitSeb** [comment]
Frame start/end is at `glXSwapBuffer(...)` . Look for this function and at what it is doing.

**Comment by luo9674** [comment]
> Frame start/end is at `glXSwapBuffer(...)` . Look for this function and at what it is doing.

OK. thanks!
