### ISSUE TITLE
Enabling mipmap calls the CPU to render

### ISSUE THREAD

**Issue by luo9674** [ptitSeb/gl4es#335]
I want to open mipmap in MC. I set the environment variable LIBGL_MIPMAP to 0 in gl4es, but the rendering frame rate of MC drops dramatically.(from 120+ to 5-)
At the same time, I see that one of the CPU cores is extra occupied, while the GPU occupied decreased.
And mipmap doesn't work on some shaders.(They require the GL API to enable mipmap for multiple color buffers.)
This is because mipmap is a software implementation?
I would like to know some conversion details or solutions.😊

**Comment by ptitSeb** [comment]
mipmap support on gles is much limited than opengl. Many things needs to be emulated with CPU, and there are still stuff (like with FBO) not 100% supported).

**Comment by luo9674** [comment]
> mipmap support on gles is much limited than opengl. Many things needs to be emulated with CPU, and there are still stuff (like with FBO) not 100% supported).

Ok . but GL 2.x doesn't have glGenerateMipmap, how does it make mipmap?

**Comment by ptitSeb** [comment]
By setting AUTO MIPMAP to 1 with `glTexParameteri(...)`
