### ISSUE TITLE
ioq3 crash

### ISSUE THREAD

**Issue by Moldytzu** [ptitSeb/gl4es#338]
Terminal output:
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Subtract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 15
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Max Color Attachments: 1 / Draw buffers: 1
LIBGL: Hardware vendor is ARM
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: sRGB surface supported
LIBGL: EGLImage from Pixmap supported
LIBGL: EGLImage to Texture2D supported
LIBGL: EGLImage to RenderBuffer supported
LIBGL: Targeting OpenGL 2.1
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: glXMakeCurrent FBO workaround enabled
LIBGL: FBO workaround for using binded texture enabled
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/home/linaro/ioq3/build/release-linux-arm
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.667
...setting mode 2: 512 384
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '800x480 720x400 640x480'
GL_RENDERER: GL4ES wrapper
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...GL_S3_s3tc not found
...GL_EXT_texture_filter_anisotropic not found
...using GL_SGIS_texture_edge_clamp
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...GL_ARB_texture_float not found
...GL_ARB_depth_clamp not found
...GL_ARB_seamless_cube_map not found
...using GLSL version 1.20 via gl4es
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...GL_ARB_texture_compression_rgtc not found
...GL_ARB_texture_compression_bptc not found
...using GL_EXT_direct_state_access
Segmentation fault

**Comment by Moldytzu** [comment]
This is the terminal output when succesfuly running the game on software rendering (without gl4es):
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.667
...setting mode 2: 512 384
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 32 depth, 0 stencil display.
Available modes: '800x480 720x400 640x480'
GL_RENDERER: Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits)
Initializing OpenGL extensions
...GL_EXT_texture_compression_s3tc not found
...GL_S3_s3tc not found
...GL_EXT_texture_filter_anisotropic not found
...using GL_SGIS_texture_edge_clamp
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...ignoring GL_ARB_texture_float
...using GL_ARB_depth_clamp
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 3.30
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...ignoring GL_ARB_texture_compression_rgtc
...GL_ARB_texture_compression_bptc not found
...GL_EXT_direct_state_access not found

**Comment by Moldytzu** [comment]
So the problem may be that gl4es doesn't support the necessary gl extensions :-/

**Comment by ptitSeb** [comment]
gl4es doesn't work with the "OpenGL 2.0" driver of ioq3 IIRC. For the gl driver to GL 1.0 and it should work.

**Comment by Moldytzu** [comment]
I will try that!

**Comment by Moldytzu** [comment]
Thanks you for creating this great library for single board computers! It works.
