### ISSUE TITLE
prboom-plus Shader compile error

### ISSUE THREAD

**Issue by mvyskoc** [ptitSeb/gl4es#339]
Hello,
I tried to use gl4es to execute the game prboom-plus on Odroid GO Super handheld. I am using only SDL without x11. The library gl4es is loaded during the execution but the game crash with shader compile error.
I do not have any knowledge of computer graphics. Until now I did not know the shaders are small programs executed by GPU. I thought it relates with object shadow. ;-) Even if the code is so short I feel it is impossible for me to fix it.
Ok, back to the topic. I found the game is probably using only 2 shader source files:
I know it is not issue of your library, but maybe the solution of this problem will help to other people / beginners. Thank you for any response and your time. 
Best regards
             Martin

Fragment shadder `prboom2/data/lumps/glfp.lmp`:
```
#version 100               // <-- MY UPDATE
precision mediump float;   // <-- MY UPDATE
uniform sampler2D tex;
uniform float lightlevel;

#define DOOMLIGHTFACTOR 232.0

void main()
{
  vec4 color = gl_Color;

  // Doom lighting equation ripped from EDGE.
  float L = 63.0 * lightlevel;
  float min_L = clamp(36.0 - L, 0.0, 31.0);
  float dist = max(0.0, gl_FragCoord.z);
  float index = 59.0 + DOOMLIGHTFACTOR - L - DOOMLIGHTFACTOR / dist;
  color.rgb *= (1.0 - clamp(index, min_L, 31.0) / 31.0);

  gl_FragColor = color * texture2D(tex, gl_TexCoord[0].st);
}
```

Vertex shadder `prboom2/data/lumps/glvp.lmp`:
```
#version 100               // <-- MY UPDATE
void main()
{
  gl_FrontColor = gl_Color;
  gl_TexCoord[0] = gl_TextureMatrix[0] * gl_MultiTexCoord0;
  gl_Position = ftransform();
}
```
I tried to use `gsLangValidator` which produce following output:

**glfp.frag**: original name glfp.lmp
```martin@ntb-f15:~/shaders$ glslangValidator glfp.frag 
glfp.frag
ERROR: 0:10: 'gl_Color' : undeclared identifier 
ERROR: 0:10: '=' :  cannot convert from ' temp float' to ' temp mediump 4-component vector of float'
ERROR: 0:10: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
````

**glvp.vert**: original name glvp.lmp
````
martin@ntb-f15:~/shaders$ glslangValidator glvp.vert 
glvp.vert
ERROR: 0:4: 'gl_FrontColor' : undeclared identifier 
ERROR: 0:4: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
````

**Comment by ptitSeb** [comment]
the shaders are transformed by gl4es (it's the `shaderconv` function). Use `LIBGL_LOGSHADERERROR=1` env. var. to have detailled information of shader before and after transformation when compile or link fail.

**Comment by mvyskoc** [comment]
Hello,
thanks for the response. I executed the game in build directory by the following command:
````
LIBGL_LOGSHADERERROR=1 LD_LIBRARY_PATH=/usr/lib/gl4es ./prboom-plus -config ./prboom-plus.cfg &> prboom-plus.log
````
Full log file: [prboom-plus.log](https://github.com/ptitSeb/gl4es/files/7147710/prboom-plus.log)

Part of the log relating with shader error:
````
LIBGL: FPE Vertex shader compile failed: source is
// FPE_Shader generated
varying vec4 Color;

void main() {
gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
Color = gl_Color;
}


Error is: 
LIBGL: FPE Fragment shader compile failed: source is
// FPE_Shader generated
varying vec4 Color;
uniform float _gl4es_AlphaRef;
void main() {
vec4 fColor = Color;
if (floor(fColor.a*255.) < _gl4es_AlphaRef) discard;
gl_FragColor = fColor;
}

Error is: 
LIBGL: FPE Program link failed: source of vertex shader is
// FPE_Shader generated
varying vec4 Color;

void main() {
gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
Color = gl_Color;
}


source of fragment shader is 
// FPE_Shader generated
varying vec4 Color;
uniform float _gl4es_AlphaRef;
void main() {
vec4 fColor = Color;
if (floor(fColor.a*255.) < _gl4es_AlphaRef) discard;
gl_FragColor = fColor;
}
````

I  forgot to mention the GL4ES was compiled by me with the following flags:
````
cmake .. -DBCMHOST=1 -DNOEGL=1 -DNOX11=1 -DDEFAULT_ES=2 -DUSE_CLOCK=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
````

**Comment by ptitSeb** [comment]
I don't think the shaders are the issue here. There are very simple and I'm quite sure the syntax of the converted shaders is correct. I think the issue here is that you don't have a correct GLES2 context in place (also note that the link error is an epty string). You built without X11 and without EGL (and with BCMHOST? I really don't think you need that), so you have to provide everything. Can't you build with EGL at least?

**Comment by mvyskoc** [comment]
Hi, afraid you are right. The problem is not with shaders at all, but finally I am at least partial successful. 
I must update the graphic initialization, see following patch file: [prboom-gl.patch.txt](https://github.com/ptitSeb/gl4es/files/7149885/prboom-gl.patch.txt)

But the most important parts are:
````
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
````
Set SDL_GL_BUFFER_SIZE and SDL_GL_DEPTH_SIZE to 24 bits. If the value is 32 or original 16 the opengles2 renderer fail to initialize.
````
SDL_GL_SetAttribute( SDL_GL_BUFFER_SIZE, 24 );
SDL_GL_SetAttribute( SDL_GL_DEPTH_SIZE, 24 );
````
What is working, the game starts and it is playable, it presents the opengl is used. The shaders and most of the game settings relating with opengl is locked. The reason is `SDL_GL_GetProcAddress` function return 0 (null pointer) for most of the functions. Most but not all, for example SDL_GL_GetProcAddress("glGetString") works. But the others such as: `glDeleteObjectARB`, `glGetHandleARB`, `glDetachObjectARB`, `glCreateShaderObjectARB`, `glShaderSourceARB`, `glCompileShaderARB` ... not

I have feeling I am in the similar situation which was already described  by @mittorn in #151

Back to gl4es library. I compiled it with EGL support and without X11. In such case the game is running, I hear the audio but I see only black screen. The game responds to keyboard, but nothing is see. I remind, that I do not use X server, only SDL library directly from terminal. I do not know if SDL_GL_GetProcAddress is working.

I try if I will able to get it working in X11.  The problem is why I do not use X server are some driver limitation / support for Mali Rockchip RK3326.  I am able start X-Server but only with `modesetting` driver.

**Comment by ptitSeb** [comment]
Well, `SDL_GL_GetProcAddress` will be the GLES version of it. You need to make sure you use the gl4es version if you want to use gl4es.

**Comment by mvyskoc** [comment]
Hi, I am sorry for so late response. My daughter is sick and wife begin be too. Go to the work, make homeworks, ...
But yes you are right again. `SDL_GL_GetProcAddress` probably returns GL4ES lib version. Afraid there is not possible to simply call you gl_GetProcAddress function, because the GL4ES library is not correctly initialized and I got segmentation fault.

But I was finally to get working solution. Patch the game where gles driver is enabled:
[prboom-plus_gl4es.patch.txt](https://github.com/ptitSeb/gl4es/files/7190452/prboom-plus_gl4es.patch.txt)

Run the game with following command:
````
SDL_VIDEO_GL_DRIVER=./libGL.so LD_LIBRARY_PATH=/. LD_PRELOAD=./libGL.so ./prboom-plus
````
where `libGL.so` must be `gl4es` version of library.

Hey, thank you very much for your support. You push me forward. Without your help I would stuck on the place. You can close this issue ticket. If you will visit Czech Republic, let me know I invite you and your family to the lunch. 

Bye Martin

**Comment by ptitSeb** [comment]
Ah yes ok, use libGL as a replacement for GLES2 driver in SDL. Yes, that works too :D !

(I've been to Prague one time, for a long weekend, in vacation with my wife. Nice city :) )
