### ISSUE TITLE
does gl4es support armhf?

### ISSUE THREAD

**Issue by NoNameMan1231** [ptitSeb/gl4es#342]
my friend try to coplie it on armhf device but when he tried to run `glxgears` he  get "segmentation fault" error

WHY?

**Comment by ptitSeb** [comment]
Because you have no access to GLES hardware?

Difficult to know without any info.

**Comment by Yisus7u7** [comment]
> Because you have no access to GLES hardware?
> 
> Difficult to know without any info.

Works well on aarch64 devices, error is only on arm32

**Comment by ptitSeb** [comment]
Well, then, probably because you have no acces GLES hardware, because of no 32bits drivers are present or accessible?

**Comment by Yisus7u7** [comment]
> Well, then, probably because you have no acces GLES hardware, because of no 32bits drivers are present or accessible?

So what should be done to solve it?

**Comment by Yisus7u7** [comment]
Does mesa have an end to this?

**Comment by ptitSeb** [comment]
I'm not sure. I'm not an expert in Android/termux.

**Comment by ptitSeb** [comment]
mesa will give you only software rendering at this point I suppose.

**Comment by Yisus7u7** [comment]
Is there any way to get the debug of the execution of a program?, the "segmentation fault" message does not help at all

**Comment by Yisus7u7** [comment]
![Screenshot_20211017-170626](https://user-images.githubusercontent.com/64093255/137651586-56a8596c-408e-4131-8bf0-113fbd6677d4.png)
![Screenshot_20211017-193336](https://user-images.githubusercontent.com/64093255/137651589-fce96afe-b0d2-45d5-8907-3acbdb067877.png)

@ptitSeb

I compiled table with support for OpenGL and using wayland. 

Works properly

https://youtu.be/hsO-Os9jr8g

**Comment by NoNameMan1231** [comment]
So now I can close it
