### ISSUE TITLE
Glsl transpose work wrongly?

### ISSUE THREAD

**Issue by Sisah2** [ptitSeb/gl4es#346]
This is more like a question, but there are new openmw shaders available and there is mat3 transpose function that seems to work differently on desktop opengl and gl4es, on desktop it work fine, with gl4es things that was dependant on it was moving with camera, it was fixed replacing build-in transpose function with 

highp mat3 transpose2(in highp mat3 inMatrix) 
{ 
 highp vec3 i0 = inMatrix[0];
 highp vec3 i1 = inMatrix[1]; 
 highp vec3 i2 = inMatrix[2];

 highp mat3 outMatrix = mat3( vec3(i0.x, i1.x, i2.x), vec3(i0.y, i1.y, i2.y), vec3(i0.z, i1.z, i2.z) );
 return outMatrix;
}

I think those functions in shaderconv dont do any reorder, input = output;

**Comment by ptitSeb** [comment]
yes, shaderconv doesn't reordor things.
What transpose function was used, the internal one?

**Comment by AbduSharif** [comment]
Those modded PBR shaders for OpenMW, they only qirk with a development build or commit from Oct 8 2021:
https://usaupload.com/6eQP/openmwPBRalphav05.7z
https://usaupload.com/6eQO/openmwPBRalphav05hotfix.7z

You need a mid with Parallax Maps, I think this one does:
https://www.nexusmods.com/morrowind/mods/44536

(Remember to enable the needed settings).

This too but it's a bug download for the file wuth parallax:
https://www.nexusmods.com/morrowind/mods/42575?tab=files

**Comment by ptitSeb** [comment]
@AbduSharif is your comment for me or for @Sisah2 (because if it's for me, I don't understand the point)

**Comment by AbduSharif** [comment]
It was for you as I thought you wanted to test if the change works:
> What transpose function was used, the internal one?

I could be misunderstanding I guess.

**Comment by ptitSeb** [comment]
But openmw use an internal copy of gl4es IIRC. Also, I don't have a setup an android developpement environment.

Anyway, the internal transpose function of gl4es were indeed doing nothing. It should be fixed now.

**Comment by AbduSharif** [comment]
Thanks.
