### ISSUE TITLE
add SRGB support pls

### ISSUE THREAD

**Issue by defolity** [ptitSeb/gl4es#349]
sRGB needed for new Half-Life 2 android port, without textures with sRGB they too very bright and some ones models too dark.
Thanks for your understanding.

**Comment by magisk666** [comment]
> 新的半条命 2 android 端口需要 sRGB，没有带有 sRGB 的纹理，它们太亮，有些模型太暗。 感谢你的理解。

The new port has been fixed.

**Comment by ptitSeb** [comment]
what do you mean, you implemented sRGB? create a workaround? used something else than gl4es?

**Comment by davie504** [comment]
> what do you mean, you implemented sRGB? create a workaround? used something else than gl4es?

It uses togles ( modification of https://github.com/ValveSoftware/ToGL by nillerusr)
It's has output opengles3 and completely different objections

**Comment by ptitSeb** [comment]
Ah ok, something else.
I think ToGL is what is currently used also for the official linux port of HL2 (well, it can use Vulkan with dxvk also)

**Comment by davie504** [comment]
> I think ToGL is what is currently used also for the official linux port of HL2 (well, it can use Vulkan with dxvk also)
Both. It uses togl or dxvk.
And migrate to togles is a good choice. No more freezes on adreno and srgb is supported
![Screenshot_2022-03-20-13-50-17-554_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299059-3e10b60c-e506-4527-9a3c-a0d52b5b109d.jpg)
![Screenshot_2022-03-20-12-41-50-313_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299195-f00cfa7a-b518-4ca9-88dc-23fc0bab747e.jpg)
![Screenshot_2022-03-20-12-39-04-663_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299258-c146ab7c-d577-4023-acd8-7e1c1c055099.jpg)
![Screenshot_2022-03-20-12-20-55-296_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299374-0f9a0aaa-9268-4482-8eca-897434188ef0.jpg)
![Screenshot_2022-03-20-11-15-33-209_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299592-edbb9636-a99e-4f59-a2e6-ecc037d38590.jpg)
![Screenshot_2022-03-20-12-41-09-307_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299447-5d3c9843-6cfc-4951-8f72-ebb6d8d4bf1b.jpg)
![Uploading Screenshot_2022-03-20-12-12-16-984_com.valvesoftware.source.jpg…]()
![Screenshot_2022-03-20-11-14-17-782_com valvesoftware source](https://user-images.githubusercontent.com/59658354/159299650-ef17dbc0-84de-45e2-97fc-da92f74ba7bd.jpg)

**Comment by ptitSeb** [comment]
Looks nice!
Is `togles` a fork of `togl`?

**Comment by davie504** [comment]
https://github.com/nillerusr/source-engine/tree/master/togles 
Yeah
