### ISSUE TITLE
No rule to compile versions.h?

### ISSUE THREAD

**Issue by b-aaz** [ptitSeb/gl4es#357]
Hi thanks for the grate project it's really awesome but I have a problem when building I get this error 

`make[2]: *** No rule to make target 'gl4es-master/src/../version.h', needed by 'src/CMakeFiles/GL.dir/gl/build_info.c.o'.  Stop.`

Iam in a arch proot in termux aarch64 android 11 .thanks😊

**Comment by ptitSeb** [comment]
I don't know, but this file is part of the git sources. It should be there https://github.com/ptitSeb/gl4es/blob/master/version.h
Try to do `git checkout version.h` maybe, in case it has been deleted by mistake.

**Comment by b-aaz** [comment]
Thanks I didn't notice that the file was missing I curled the file. it compiled and know iam watching some gears 😃. Keep up the good work 👍 .
BTW I downloaded the zip version of the repo maybe that caused  the problem
