### ISSUE TITLE
Texture shrink makes the OpenRA Tiberian Sun game image mess

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/gl4es#36]
![2017-10-25 15-20-58](https://user-images.githubusercontent.com/1916518/31985592-37a04e26-b998-11e7-833d-a4d1d3000561.png) Correct result
![2017-10-25 15-21-10](https://user-images.githubusercontent.com/1916518/31985608-4227cd2e-b998-11e7-9490-35c18500d041.png) LIBGL_SHRINK=10 result

**Comment by ptitSeb** [comment]
It should be fixed with 08fe79a56f04b73bf5af352718a202b305a2a58c

**Comment by Icenowy** [comment]
The problem seems to be not shrink mode error -- it seems that the shrinking destroyed the texture at all.
Maybe OpenRA uses some special rendering skill that is not so compatible with the texture shrinking algorithm.

**Comment by ptitSeb** [comment]
Well, OpenRA has some "pixel-art" textures (coming from the original game, so lowres 8bits textures). Shrinking them will certainly add a huge blur to the rendering. Shinking is more effective (and has a less visual impact) on 3D games, when you shrink wall textures, or distant sky / backdrop.

On the other hand, the rendering code use simple and fast shaders, so I don't expect it to not be compatible with shrinking.
I'll check the rendering later just in case I missed something.

**Comment by Icenowy** [comment]
Yes.

Currently the problem is that OpenRA uses too much VRAM on Mali-400 (On my system Linux currently reserves 192MiB VRAM for it, however it runs out even when the title screen is just loaded)

By analysing the apitrace result, it seems that they're wasting VRAM -- for example, for the font texture it allocates 2048*2048 space but only 2048*150 is used at all (all other pixels are transparent)

Maybe I should work on restricting this kind of waste in OpenRA instead.

For the rendering mess currently it seems to be "by design" so I close this issue -- the problem is that OpenRA is tend to create oversize textures.

**Comment by ptitSeb** [comment]
I have some git diff with some changes on the renderer for OpenRA, that gives me some boost on the Pandora (ImTec SGX based). I haven't checked about texture size, but yeah, 2048x2048 for a font seems a bit huge!

**Comment by Icenowy** [comment]
The default texture size seems to be a hidden setting in OpenRA, which can be manually changed in settings.yaml .

**Comment by ptitSeb** [comment]
@Icenowy about OpenRA performances, 44d1ded880b791b3e0b884534b1bd2235bf0d318 should help a lot.
I still have a diff on the OpenRA sources with some other tweaks if this commit is not enough.
