### ISSUE TITLE
Shield tablet shaders

### ISSUE THREAD

**Issue by Sisah2** [ptitSeb/gl4es#371]
Hello, just quick question, did you ever heard about shield tablet having big issue compiling shaders? (That othervise work on other devices) its mostly float -> int conversions but also things like "unable to find compatible overloaded function "clamp(float, float, float)" which dont make much sense.

**Comment by ptitSeb** [comment]
You mean when using gl4es? On a shield tablet, is gl4es really usefull, I would expect NVidia providing a full OpenGL driver already.
For gl4es, you can try to run with `LIBGL_NOINTOVLHACK=1` env. var. to disable the use of overloaded clamp function...

**Comment by Sisah2** [comment]
Yeah it helped it seems. (It was openmw build, which use gl4es for all androids, as shield/tegra is probably only device which support real opengl) thank you.
