### ISSUE TITLE
Problems with Rockchip Chromebook

### ISSUE THREAD

**Issue by duckdodger** [ptitSeb/gl4es#38]
Hello,
I'm using an Asus C201 Chromebook which is built around the Rockchip RK3288 SoC (specs [here](https://en.wikipedia.org/wiki/Rockchip_RK3288) which has the Mali T760 GPU. It's running Arch Linux ARM and according to the [installation instructions](https://archlinuxarm.org/platforms/armv7/rockchip/asus-chromebook-flip-c100p), I have two packages installed: `xf86-video-armsoc-rockchip` which provides the X.org video driver and `veyron-libgl` which provides the Mali EGL and GLES drivers (version r5p0-3).

I [recently opened an issue](https://github.com/OpenRA/OpenRA/issues/14126) on the OpenRA repository about getting very poor performance with the game and asking if there was a way to make it use GLES rendering so that I can get hardware acceleration and someone pointed me to this project. So I compiled the libraries here by choosing the ODROID platform since that seemed to be closest to my specs (both have Mali GPU), ran the tests and got the [logs here](https://gist.github.com/duckdodger/92d06d000a3d0b85711badded7303d11). The test finished successfully, but it didn't look like any of the samples ran smoothly (in fact, they ran just as they would without gl4es). Anyhow, something to note is the recurring error in the test log:
```
libGL error: unable to load driver: rockchip_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: rockchip
```
This is not specific to this test, I get this error everytime I run some software that uses OpenGL. I'm guessing it has to do with the fact that my GPU does not support OpenGL at all, so this is probably fine and doesn't have any effect on the test? I don't know. However, I still put lib/libGL.so.1 in `LD_LIBRARY_PATH` by running `export LD_LIBRARY_PATH="$HOME/gl4es/lib/libGL.so.1:$LD_LIBRARY_PATH"` from my terminal and running OpenRA afterwards:
```
$ openra-ra
Platform is Linux
Engine version is release-20171014
Using SDL 2 with OpenGL renderer
libGL error: unable to load driver: rockchip_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: rockchip
Desktop resolution: 1366x768
No custom resolution provided, using desktop resolution
Using resolution: 1366x768
Using window scale 1.00
OpenGL version: 3.0 Mesa 17.2.2
Using default sound device
shared memfd open() failed: Function not implemented
shared memfd open() failed: Function not implemented
Internal mods:
	cnc: Tiberian Dawn (release-20171014)
	d2k: Dune 2000 (release-20171014)
	modcontent: Mod Content Manager (release-20171014)
	ra: Red Alert (release-20171014)
External mods:
	ra-release-20171014: Red Alert (release-20171014)
Loading mod: ra
libpng warning: iCCP: known incorrect sRGB profile
```
I get the same libGL error saying it couldn't load my rockchip driver. The game still runs incredibly slow, with no performance difference compared to running without GL4ES. Please do tell me where I'm going wrong, or if GL4ES just isn't supported for my platform. I'm a total noob when it comes to this stuff.

**Comment by Icenowy** [comment]
I think the libGL.so.1 provided by gl4es is not loaded.

Try set the LD_LIBRARY_PATH environment variable to the lib directory inside where you built gl4es (and will have a libGL.so.1 in it)

**Comment by ptitSeb** [comment]
gl4es should work on any platform that is little-endian and with a GLES driver.
So it should work for you.

You seems to be missing some part of GLES driver. The ODROID has a Mali, but also the CHIP.
On the CHIP, it seems `sudo apt-get install chip-mali-userspace` is needed to have GLES driver installed. Maybe it's the same for you?

Anyway, in the wiki page you linked, it's written that "Remove the veyron-libgl and xf86-video-armsoc-rockchip packages. Mali is not supported in mainline.". Are you using mainline?

**Comment by Icenowy** [comment]
See `OpenGL version: 3.0 Mesa 17.2.2`, the wrapper is just not loaded at all.

**Comment by ptitSeb** [comment]
Ah yes, clearly, as @Icenowy mentionned, gl4es is not called. You need to use `LD_LIBRARY_PATH` to point to `gl4es/lib` before launching OpenRA.

**Comment by duckdodger** [comment]
@Icenowy @ptitSeb Yes, my bad. That was silly. OpenRA runs much smoother now.

@ptitSeb I forgot to mention, I'm indeed using the ChromeOS kernel:
```
$ uname -a
Linux deepthought 3.14.0-26-ARCH #1 SMP PREEMPT Sun Jul 2 04:08:36 UTC 2017 armv7l GNU/Linux
```
So I ran OpenRA after loading GL4ES, and the game starts up fine, the background in the menu renders properly but with a few hiccups in between (slight, but noticeable). The main problem, however, is that every time I start a game and play for a little while, the game completely crashes. The screen is stuck in the game and I'm unable to switch to a TTY, leaving me no choice but to reboot the computer. I did `export LIBGL_STACKTRACE=1`, but I have no clue where this is stored, if at all.

**Comment by ptitSeb** [comment]
Glad it start smoothly now.

About the crash, I don't have this on my side. But I did notice the game is, over all, quite Memory hungry. So you may run out of memory?

Also, as @Icenowy noticed, there is a hidden parameter in ~/.openra/settings.yaml to limit the size of sprite sheet texture. By default it's 2048x2048, but under `Graphics:` add `SheetSize: 1024` and it will limit to 1024x1024.

You can also try to create a swapfile, just in case.

If you need to reboot, then yeah, LIBGL_STACKTRACE will not help, as it just printf a backtrace in the console in case of segfault.

**Comment by duckdodger** [comment]
Changing SheetSize to 1024 has no effect on the crash. I have 4GB of RAM on this laptop, and I don't have anything significant running while I start OpenRA. Is even 4GB not sufficient?

**Comment by ptitSeb** [comment]
No, 4GB is more than enough.

I suggest you try some ohter software / games with gl4es, and try to see if there is a patern. It may be the GLES driver that didn't like something.

**Comment by duckdodger** [comment]
I just tried a couple of other games, Teeworlds and SuperTux. Before that, I tried playing OpenRA in windowed mode, and the game actuallly didn't crash although there were a _lot_ of rendering issues and screen tearing. The screen tearing is probably because I'm not using a compositor. SuperTux ran fine in windowed mode and there were no rendering problems either, but would crash in the same manner as OpenRA in fullscreen mode after playing for a while. Teeworlds crashes in fullscreen, but this crashed differently. It crashes in the menu itself, and also I'm able to switch to a TTY and successfully kill Teeworlds without having to reboot, so I'm not sure if the cause of this crash is the same as the other two games.

**Comment by ptitSeb** [comment]
Ok, so it seems the driver doesn't like fullscreen.

About the rendering issue of OpenRA, is it something similar to https://github.com/ptitSeb/gl4es/issues/37 or is it something else (and then, can you take a screenshot?).

For Teeworld and SuperTux, did you use GLES2 backend or GLES1?

For the fullscreen issue, you can also try the with LIBGL_FB=1 (it may not work, but if it does, it will force fullscreen rendering) and LIBGL_FB=3 (it may be slower).

**Comment by ptitSeb** [comment]
@duckdodger : can I close this issue?
The issue you have with the crash doesn't seems linked to gl4es, but with the interaction between your GLES driver and X11.
(Also, did you tried the tantitve workaround?)

**Comment by duckdodger** [comment]
Yes, you can close the issue. I'm sorry I didn't pursue this further, I kinda gave up and didn't have time to look into it.

**Comment by ptitSeb** [comment]
Ok, I close the issue then.

It's still accessible anyway. Feel free to re-open if necessary later.
