### ISSUE TITLE
"Failed to initialize OpenGL Loader!" on Rpi4 (Ubuntu MATE 22.04)

### ISSUE THREAD

**Issue by StrikerMan780** [ptitSeb/gl4es#398]
Been trying to use this with EDuke32 on a Raspberry Pi 4, but in the console I get "Failed to initialize OpenGL Loader!" when I make any attempt to launch the game. I've put `libGL.so.1` into the same folder as my compiled executable, and did `LD_LIBRARY_PATH=./`

Not sure what I've been doing wrong. I built the ODROID configuration as per the compiling instructions.

If you'd like to try it yourself, there's building instructions here: https://wiki.eduke32.com/wiki/Building_EDuke32_on_Linux#Compiling_From_Source

**Comment by ptitSeb** [comment]
Why would you want to use gl4es on a Pi4, mesa is working there?

**Comment by StrikerMan780** [comment]
It's not. No matter what distro I use, it fails. Ubuntu, Raspbian, etc.

**Comment by ptitSeb** [comment]
Mesa on Rpi4 with Raspbian works very well. But the default profile is only 2.1. eDuke3D, needs 3.+ to be able to use Plymer IIRC, so maybe try to use `MESA_GL_VERSION_OVERRIDE=3.3`
I need more logs if nothing works.

Also, what gives you `glxinfo -B` on your Pi4?

**Comment by StrikerMan780** [comment]
Not using Polymer, I'm using Polymost. Polymost only needs OpenGL v2.0 minimum, but it fails to run nonetheless.

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 4.2 (0xffffffff)
    Version: 22.2.0
    Accelerated: yes
    Video memory: 7807MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL version string: 2.1 Mesa 22.2.0 - kisak-mesa PPA
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 22.2.0 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by ptitSeb** [comment]
Well, you have mesa working according to glxinfo, so you don't need gl4es. is `glxgear` working fine? If yes, that you have an issue with your build of eDuke, and you should open a ticket in eDuke repo. If not, you have an issue on your system, and gl4es will not help because it would also use mesa (the GLES drivers).

In both cases, this is not a gl4es issue.

**Comment by StrikerMan780** [comment]
glxgears works fine. Just really strange, not sure what the hell is broken in eDuke if that's the case. It used to work when I was running a much older distro.

**Comment by ptitSeb** [comment]
I don't know. Maybe some wayland stuff? You better ask question on a RPi forum, you'll have bigger chance to get an answer there.

**Comment by StrikerMan780** [comment]
Thinking it's a Mesa issue, since forcing software with LIBGL_ALWAYS_SOFTWARE gets it loading, wile it's obviously slow, however.

**Comment by ptitSeb** [comment]
Did you tried to force the profile to 3.3 as I mentionned earlier?

**Comment by StrikerMan780** [comment]
Yeah, didn't help.
