### ISSUE TITLE
I want use the two funs:int glRenderMode(GLenum mode); void glSelectBuffer(GLsizei size, GLuint* buffer);  in android's GLES,i should to do?

### ISSUE THREAD

**Issue by lijiayan2015** [ptitSeb/gl4es#40]
hello 
I want use the two funs :int glRenderMode(GLenum mode); void glSelectBuffer(GLsizei size, GLuint* buffer); in android's GLES,the two funs no impl in GLES,i should to do?
please......

**Comment by ptitSeb** [comment]
I assume you want to use `glRenderMode(GL_SELECT)`

In that case, you need to link your Android program with gl4es, and use desktop OpenGL functions. There are a some Android program using gl4es already, so you can see how to do that.

There is Gish port to Android by EXL: https://github.com/EXL/Gish
Lubomyr has many Android port using gl4es, look there: https://github.com/lubomyr

I hope it help you start using gl4es.
