### ISSUE TITLE
How to call initialize_gl4es()?

### ISSUE THREAD

**Issue by lijiayan2015** [ptitSeb/gl4es#41]
Hello:
I want use your gl4es instead Android NDK's GLES in my android project for many functions that OpenGLES not supported.
I have compiled gl4es to a static lib by the [Android.mk](https://github.com/ptitSeb/gl4es/blob/master/Android.mk) ,But i dont't know how to init it in my Android environment. I think call the initialize_gl4es() can init but no any head file to declare this function.I try to declare it in [init.h](https://github.com/ptitSeb/gl4es/blob/master/src/gl/init.c) like:
![image](https://user-images.githubusercontent.com/16370666/33197637-a85f1070-d121-11e7-8682-e796ce4eb445.png)

then I compiled again, and use it like:
![image](https://user-images.githubusercontent.com/16370666/33197664-cbf53ab4-d121-11e7-828f-3ae2e0082f66.png)
but when run my project it occur error like:
![image](https://user-images.githubusercontent.com/16370666/33197728-20c60690-d122-11e7-858a-e92caf219c9a.png)
In the [Android.mk](https://github.com/ptitSeb/gl4es/blob/master/Android.mk) i try open or close the code:
```
LOCAL_CFLAGS += -DNO_INIT_CONSTRUCTOR
```
but it still useless.
I can't make sure you understand what I mean,I hope you can provide me with some useful solutions.
Thk.

**Comment by ptitSeb** [comment]
Because you are in a cpp program, I think you need to declare initialize_gl4es() as extern "C".
Don't include "GL/init.h" as it's an internal gl4es headr.
Instead, simply declare the function with
`extern "C" void initialize_gl4es();`

and that should be enough.

**Comment by lijiayan2015** [comment]
Follow your plan Then Compiled successful, though it was not able to draw my 3D correctly.
Thanks very much!

**Comment by ptitSeb** [comment]
Glad it worked :)

If you think your 3D drawing issues are related to gl4es, open a new ticket and I'll try to help.

I think this ticket can be closed.

**Comment by lijiayan2015** [comment]
Ok,Thanks.
