### ISSUE TITLE
GLX files cause issues with Android compilation

### ISSUE THREAD

**Issue by bwhaines** [ptitSeb/gl4es#42]
I'm trying to compile gl4es using ndk-build, but I'm getting the following error:

>[armeabi] Compile thumb  : GL <= glx.c
>/home/user/git/android-port/deps/gl4es/src/glx/glx.c: In function 'gl4es_glXSwapInterval':
>/home/user/git/android-port/deps/gl4es/src/glx/glx.c:1381:8: error: 'glxContext' undeclared (first use in this function)
>     if(glxContext) {
>        ^
>/home/user/git/android-port/deps/gl4es/src/glx/glx.c:1381:8: note: each undeclared identifier is reported only once for each function it appears in
>make: *** [/home/user/git/android-port/deps/gl4es/obj/local/armeabi/objs/GL/src/glx/glx.o] Error 1

I've noticed the glxContext is defined toward the beginning of the file, but it's wrapped in an 'ifndef ANDROID' directive.  The command I'm using to build is this:

>$ANDROID_NDK/ndk-build \
>  NDK_PROJECT_PATH=${BASEDIR}/gl4es \
>  APP_BUILD_SCRIPT=${BASEDIR}/gl4es/Android.mk \
>  APP_PLATFORM=android-21

Not compiling the source files from the src/glx folder works, but I don't want that to cause issues down the line.

**Comment by ptitSeb** [comment]
Should be fixed with b00cd2a4c7647346c526953b892467c8e1e6052f

**Comment by bwhaines** [comment]
Works perfectly, thank you!
