### ISSUE TITLE
How to properly profile gl4es ?

### ISSUE THREAD

**Issue by Mathias-Boulay** [ptitSeb/gl4es#421]
Hey there, 

We've been hitting what I feel is a performance bottleneck on gl4es side on recent minecraft versions.
Therefore, I wondered, is there is a recommended way to handle benchmarking gl4es functions ?

A considered alternative is to profile minecraft and the lwjgl OGL calls themselves, but it would lessen the ability to profile functions calls from the implementation, leaving us a bit blind.

**Comment by ptitSeb** [comment]
There is no specific tooling inside gl4es for profiling. Usualy, I use `sudo perf top` to see if an obvious function is taking all cpu. Some grpof build also work. But I have no idea what's available on Android.

**Comment by Mathias-Boulay** [comment]
looking for the perf tool you mentionned conducted me to the [https://developer.android.com/ndk/guides/simpleperf](simpleperf) tool, which seems designed for this use case :smile: 

I'll give it a go in 2 - 3 weeks
