### ISSUE TITLE
glxgears wrong size and strange incorrect colors

### ISSUE THREAD

**Issue by kleovoulos** [ptitSeb/gl4es#425]
![Screenshot_2023-04-08-20-13-34](https://user-images.githubusercontent.com/128096512/230735490-a59fba21-5419-4598-9921-182ba10cc9b2.png)

Hello there, tested on a chroot enviroment with debian sid on android 5.1 and with XSDL

**Comment by ptitSeb** [comment]
GL4ES works only if GLES/GLES2 works. Did you try GLES/GLES2 program to see if they have the same behavior?

**Comment by kleovoulos** [comment]
I tried to launch Xephyr with -glamor_gles2 option and it has strange incorrect colors.

Attached glxinfo

On April 8, 2023 8:58:31 PM GMT+03:00, ptitSeb ***@***.***> wrote:
>GL4ES works only if GLES/GLES2 works. Did you try GLES/GLES2 program to see if they have the same behavior?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ptitSeb/gl4es/issues/425#issuecomment-1500944938
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
LIBGL: Initialising gl4es
LIBGL: v1.1.5 built on Apr  8 2023 18:38:23
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so.2
LIBGL: loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: No alpha channel in PBuffer context, disabling EGL Alpha channel...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Subtract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays  detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Extension GL_ARM_shader_framebuffer_fetch detected and used
LIBGL: Extension GL_OES_get_program_binary  detected and used
LIBGL: Number of supported Program Binary Format: 1
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Max Color Attachments: 8 / Draw buffers: 8
LIBGL: Hardware vendor is Mesa/X.org
LIBGL: sRGB surface supported
LIBGL: EGLImage to Texture2D supported
LIBGL: EGLImage to RenderBuffer supported
LIBGL: Targeting OpenGL 2.1
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/root
LIBGL: Loaded a PSA with 2 Precompiled Programs
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: ptitSeb
server glx version string: 1.4 GL4ES
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_swap_control, GLX_MESA_swap_control, GLX_SGIX_pbuffer, 
    GLX_SGI_swap_control
client glx vendor string: ptitSeb
client glx version string: 1.4 GL4ES
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_swap_control, GLX_MESA_swap_control, GLX_SGIX_pbuffer, 
    GLX_SGI_swap_control
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_swap_control, GLX_MESA_swap_control, GLX_SGIX_pbuffer, 
    GLX_SGI_swap_control
OpenGL vendor string: ptitSeb
OpenGL renderer string: GL4ES wrapper
OpenGL core profile version string: 2.1 gl4es wrapper 1.1.5
OpenGL core profile shading language version string: 1.20 via gl4es
OpenGL core profile extensions:
    GL_APPLE_texture_2D_limited_npot, GL_ARB_ES2_compatibility, 
    GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_instanced, 
    GL_ARB_fragment_program, GL_ARB_fragment_shader, 
    GL_ARB_framebuffer_object, GL_ARB_get_program_binary, 
    GL_ARB_instanced_arrays, GL_ARB_map_buffer_range, GL_ARB_multisample, 
    GL_ARB_multitexture, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_shader_objects, GL_ARB_shading_language_100, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_vertex_array_object, 
    GL_ARB_vertex_buffer, GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, 
    GL_ARB_vertex_shader, GL_ATIX_texture_env_route, 
    GL_ATI_texture_env_combine3, GL_EXT_abgr, GL_EXT_bgra, 
    GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_color_buffer_float, GL_EXT_color_buffer_half_float, 
    GL_EXT_compiled_vertex_array, GL_EXT_compiled_vertex_arrays, 
    GL_EXT_depth_texture, GL_EXT_direct_state_access, GL_EXT_draw_buffers2, 
    GL_EXT_draw_elements_base_vertex, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
    GL_EXT_multi_draw_arrays, GL_EXT_packed_depth_stencil, 
    GL_EXT_packed_pixels, GL_EXT_point_parameters, GL_EXT_polygon_offset, 
    GL_EXT_program_parameters, GL_EXT_rescale_normal, GL_EXT_secondary_color, 
    GL_EXT_separate_specular_color, GL_EXT_stencil_wrap, 
    GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_dxt3, 
    GL_EXT_texture_compression_dxt5, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_crossbar, GL_EXT_texture_env_dot3, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_float, 
    GL_EXT_texture_half_float, GL_EXT_texture_object, GL_EXT_texture_rg, 
    GL_EXT_vertex_array, GL_GL4ES_hint, GL_NV_blend_square, 
    GL_NV_fog_distance, GL_NV_texture_env_combine4, 
    GL_OES_texture_compression_S3TC, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_edge_clamp, GL_SUN_multi_draw_arrays

OpenGL version string: 2.1 gl4es wrapper 1.1.5
OpenGL shading language version string: 1.20 via gl4es
OpenGL extensions:
    GL_APPLE_texture_2D_limited_npot, GL_ARB_ES2_compatibility, 
    GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_instanced, 
    GL_ARB_fragment_program, GL_ARB_fragment_shader, 
    GL_ARB_framebuffer_object, GL_ARB_get_program_binary, 
    GL_ARB_instanced_arrays, GL_ARB_map_buffer_range, GL_ARB_multisample, 
    GL_ARB_multitexture, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_shader_objects, GL_ARB_shading_language_100, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_vertex_array_object, 
    GL_ARB_vertex_buffer, GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, 
    GL_ARB_vertex_shader, GL_ATIX_texture_env_route, 
    GL_ATI_texture_env_combine3, GL_EXT_abgr, GL_EXT_bgra, 
    GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_color_buffer_float, GL_EXT_color_buffer_half_float, 
    GL_EXT_compiled_vertex_array, GL_EXT_compiled_vertex_arrays, 
    GL_EXT_depth_texture, GL_EXT_direct_state_access, GL_EXT_draw_buffers2, 
    GL_EXT_draw_elements_base_vertex, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
    GL_EXT_multi_draw_arrays, GL_EXT_packed_depth_stencil, 
    GL_EXT_packed_pixels, GL_EXT_point_parameters, GL_EXT_polygon_offset, 
    GL_EXT_program_parameters, GL_EXT_rescale_normal, GL_EXT_secondary_color, 
    GL_EXT_separate_specular_color, GL_EXT_stencil_wrap, 
    GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_dxt3, 
    GL_EXT_texture_compression_dxt5, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_crossbar, GL_EXT_texture_env_dot3, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_float, 
    GL_EXT_texture_half_float, GL_EXT_texture_object, GL_EXT_texture_rg, 
    GL_EXT_vertex_array, GL_GL4ES_hint, GL_NV_blend_square, 
    GL_NV_fog_distance, GL_NV_texture_env_combine4, 
    GL_OES_texture_compression_S3TC, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_edge_clamp, GL_SUN_multi_draw_arrays

OpenGL ES profile version string: 2.1 gl4es wrapper 1.1.5
OpenGL ES profile shading language version string: 1.20 via gl4es
OpenGL ES profile extensions:
    GL_APPLE_texture_2D_limited_npot, GL_ARB_ES2_compatibility, 
    GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_instanced, 
    GL_ARB_fragment_program, GL_ARB_fragment_shader, 
    GL_ARB_framebuffer_object, GL_ARB_get_program_binary, 
    GL_ARB_instanced_arrays, GL_ARB_map_buffer_range, GL_ARB_multisample, 
    GL_ARB_multitexture, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_shader_objects, GL_ARB_shading_language_100, 
    GL_ARB_texture_border_clamp, GL_ARB_texture_compression, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_float, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_vertex_array_object, 
    GL_ARB_vertex_buffer, GL_ARB_vertex_buffer_object, GL_ARB_vertex_program, 
    GL_ARB_vertex_shader, GL_ATIX_texture_env_route, 
    GL_ATI_texture_env_combine3, GL_EXT_abgr, GL_EXT_bgra, 
    GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_color_buffer_float, GL_EXT_color_buffer_half_float, 
    GL_EXT_compiled_vertex_array, GL_EXT_compiled_vertex_arrays, 
    GL_EXT_depth_texture, GL_EXT_direct_state_access, GL_EXT_draw_buffers2, 
    GL_EXT_draw_elements_base_vertex, GL_EXT_draw_range_elements, 
    GL_EXT_fog_coord, GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
    GL_EXT_multi_draw_arrays, GL_EXT_packed_depth_stencil, 
    GL_EXT_packed_pixels, GL_EXT_point_parameters, GL_EXT_polygon_offset, 
    GL_EXT_program_parameters, GL_EXT_rescale_normal, GL_EXT_secondary_color, 
    GL_EXT_separate_specular_color, GL_EXT_stencil_wrap, 
    GL_EXT_texture_compression_dxt1, GL_EXT_texture_compression_dxt3, 
    GL_EXT_texture_compression_dxt5, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_cube_map, GL_EXT_texture_edge_clamp, 
    GL_EXT_texture_env_add, GL_EXT_texture_env_combine, 
    GL_EXT_texture_env_crossbar, GL_EXT_texture_env_dot3, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_float, 
    GL_EXT_texture_half_float, GL_EXT_texture_object, GL_EXT_texture_rg, 
    GL_EXT_vertex_array, GL_GL4ES_hint, GL_NV_blend_square, 
    GL_NV_fog_distance, GL_NV_texture_env_combine4, 
    GL_OES_texture_compression_S3TC, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_edge_clamp, GL_SUN_multi_draw_arrays

2 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  sw cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b ap eat
----------------------------------------------------------------------------
0x021 16 tc  0  16  0 r  y .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 .  None
0x041 32 tc  0  16  0 r  y .   8  8  8  8 .  s  0 24  8  0  0  0  0  0 0 .  None

40 GLXFBConfigs:
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  sw cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b ap eat
----------------------------------------------------------------------------
0xb7125188 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0  0  0  0  0  0  0  0 0 .  None
0xb7125188 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0  0  0  0  0  0  0  0 0 .  None
0xb7125238 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 16  0  0  0  0  0  0 0 .  None
0xb7125238 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 16  0  0  0  0  0  0 0 .  None
0xb71252e8 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 24  0  0  0  0  0  0 0 .  None
0xb71252e8 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 24  0  0  0  0  0  0 0 .  None
0xb7125398 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 24  8  0  0  0  0  0 0 .  None
0xb7125398 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 24  8  0  0  0  0  0 0 .  None
0xb71259a0 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 32  0  0  0  0  0  0 0 .  None
0xb71259a0 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 32  0  0  0  0  0  0 0 .  None
0xb7125a50 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0  0  0  0  0  0  0  4 1 .  None
0xb7125a50 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0  0  0  0  0  0  0  4 1 .  None
0xb7125b00 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 16  0  0  0  0  0  4 1 .  None
0xb7125b00 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 16  0  0  0  0  0  4 1 .  None
0xb7125bb0 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 24  0  0  0  0  0  4 1 .  None
0xb7125bb0 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 24  0  0  0  0  0  4 1 .  None
0xb7125c60 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 24  8  0  0  0  0  4 1 .  None
0xb7125c60 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 24  8  0  0  0  0  4 1 .  None
0xb7125d10 16 sg  0  16  0 r  . .   5  6  5  0 .  s  0 32  0  0  0  0  0  4 1 .  None
0xb7125d10 16 sg  0  16  0 r  y .   5  6  5  0 .  s  0 32  0  0  0  0  0  4 1 .  None
0xb7125dc0 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0  0  0  0  0  0  0  0 0 .  None
0xb7125dc0 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0  0  0  0  0  0  0  0 0 .  None
0xb7125e70 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 16  0  0  0  0  0  0 0 .  None
0xb7125e70 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 16  0  0  0  0  0  0 0 .  None
0xb71a5910 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 24  0  0  0  0  0  0 0 .  None
0xb71a5910 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 24  0  0  0  0  0  0 0 .  None
0xb71a59c0 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 24  8  0  0  0  0  0 0 .  None
0xb71a59c0 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 24  8  0  0  0  0  0 0 .  None
0xb71a5a70 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 32  0  0  0  0  0  0 0 .  None
0xb71a5a70 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 32  0  0  0  0  0  0 0 .  None
0xb71a5b20 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0  0  0  0  0  0  0  4 1 .  None
0xb71a5b20 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0  0  0  0  0  0  0  4 1 .  None
0xb71a5bd0 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 16  0  0  0  0  0  4 1 .  None
0xb71a5bd0 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 16  0  0  0  0  0  4 1 .  None
0xb71a5d08 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 24  0  0  0  0  0  4 1 .  None
0xb71a5d08 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 24  0  0  0  0  0  4 1 .  None
0xb71a5db8 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 24  8  0  0  0  0  4 1 .  None
0xb71a5db8 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 24  8  0  0  0  0  4 1 .  None
0xb71a5e68 16 sg  0  16  0 r  . .   8  8  8  0 .  s  0 32  0  0  0  0  0  4 1 .  None
0xb71a5e68 16 sg  0  16  0 r  y .   8  8  8  0 .  s  0 32  0  0  0  0  0  4 1 .  None

LIBGL: Shuting down

**Comment by kleovoulos** [comment]
I think I have found the problem and it's unrelated with the gl4es: the
XSDL program doesn't support 24 bpp color depth on android 5.1. I tested
gl4es on another device with chroot environment and android 10 and it's
working great. Thank you so much for your work, you can close this issue.
