### ISSUE TITLE
Question about skips.h and #define guards

### ISSUE THREAD

**Issue by Mathias-Boulay** [ptitSeb/gl4es#434]
Hello there, something has been troubling me with the file `src/gl/wrap/skips.h`. 
It allows to redefine functions by versions that call directly the underlying OGLES implementation.
However, enabling the direct pass-through results in the `gl4es_` version being redefined.

Is this an oversight ?  I have a feeling enabling the direct pass-through should disable (read undefine) the normal `gl4es_` implementation

**Comment by ptitSeb** [comment]
`gl4es_XXX` implementation are needed for the `glXGetProcAddress(...)` function.
For all the new function, I usualy don't use direct mapping anyway. It's a legacy mecanism, and skipping all the state tracking is usualy not a good idea.

**Comment by Mathias-Boulay** [comment]
That's fair.
