### ISSUE TITLE
crash with gl 2.0 backdend on SDL 2.0 Android app

### ISSUE THREAD

**Issue by sandstranger** [ptitSeb/gl4es#44]
GL 2.0 backend crashing on Android with using sdl 2.0
https://pastebin.com/wrCiA4Wd
On SDL is used ES2 context

**Comment by ptitSeb** [comment]
Strange, it seems to crash with a call to gles_glLoadIdentity(), wich of course is NULL on GLES2 backend.

I have made a few changes but I'm not sure they will be enough.
If it's still crash, can you confirm (or not) if the crash occur in `src/gl/matrix.c` line 284?

**Comment by ptitSeb** [comment]
Also, I tried an old build of OpenMW on the Pandora (so Linux, not Android) using GLES2, and it started for me. I have fixed a bug in the fpe_shader, but nothing serious.
I'll try to update my build of OpenMW to see if I can reproduce the crash (but I think it's Android specific, I haven't tried anything yet on Android with GLES2 backend).

**Comment by sandstranger** [comment]
yes , it works
