### ISSUE TITLE
[Question]: NEON Intrisics

### ISSUE THREAD

**Issue by Mathias-Boulay** [ptitSeb/gl4es#441]
I noticed that ARMv7 NEON Intrisics are present in the codebase, particulary inside `mathvec.c` file.

Do you remember how much of an impact this made on performance ?  I'm considering creating ARMv8 NEON Intrisics if the time spent is worth it.

**Comment by ptitSeb** [comment]
Unfortunatly, I don't remember any number. It would be nice to have ARMv8 support too, for sure.

**Comment by Mathias-Boulay** [comment]
Argh, not even an order of magnitude ?
Well, I guess I can create some tests for my use case, it will take a slight while

**Comment by ptitSeb** [comment]
yeah, nope, sorry.it's too old, I don't remember. I did that as a time were I was putting NEON optim everywhere :)

**Comment by Mathias-Boulay** [comment]
Well, I'll see later and find out if I did well

**Comment by Mathias-Boulay** [comment]
Chances are that I better rely on this project: https://github.com/ARM-software/optimized-routines a way or another.

**Comment by Mathias-Boulay** [comment]
Side note: The android ndk does not allow neon-less compilation since a while now. I assume it now makes extensive use of the extended instructions set
