### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by micwoj92** [ptitSeb/gl4es#452]
Hello,

It has been almost 4 years and 300+ commits since latest release. Is there a plan to release new version? Maybe some release blockers?

Thanks in advance for answer.

**Comment by ptitSeb** [comment]
Ah yeah, you are right. Time flyes! I'll do a test campaign on my devices that use it and will plan a release soon!

**Comment by ptitSeb** [comment]
Finaly, the 1.1.6 has been tagged!
