### ISSUE TITLE
OpenGL 2.0 (not ES 2.0) shaders

### ISSUE THREAD

**Issue by cl9x** [ptitSeb/gl4es#46]
Is it currently possible to use custom OpenGL 2.0 shaders (i.e. shaders with fixed pipeline uniforms and attributes)?

**Comment by ptitSeb** [comment]
You can use some (most) fixed pipeline uniforms and attributes in the shaders yes.

What is not supported (yet) is to define only 1 shader (fragment or vertex) and rely on the fixed pipeline one to link the program.

**Comment by cd256** [comment]
So to achieve bump-mapping for example, I would need to supply both the vertex and fragment shaders? Should the following shader work if I rename the "gl_" prefixes are renamed as "gl4es_"?
 
```
// Vertex Shader

void main() {  
gl_TexCoord[0] = gl_MultiTexCoord0;  
  
// Set the position of the current vertex  
gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;  
}  
```

```
// Fragment shader

uniform sampler2D color_texture;  
uniform sampler2D normal_texture;  
  
void main() {  
  
// Extract the normal from the normal map  
vec3 normal = normalize(texture2D(normal_texture, gl_TexCoord[0].st).rgb * 2.0 - 1.0);  
  
// Determine where the light is positioned (this can be set however you like)  
vec3 light_pos = normalize(vec3(1.0, 1.0, 1.5));  
  
// Calculate the lighting diffuse value  
float diffuse = max(dot(normal, light_pos), 0.0);  
  
vec3 color = diffuse * texture2D(color_texture, gl_TexCoord[0].st).rgb;  
  
// Set the output color of our current pixel  
gl_FragColor = vec4(color, 1.0);  
}  
```

**Comment by ptitSeb** [comment]
It should work as-is. The "ShaderConv" (that is the module that take care of GLSL 1.20 -> GLSL ES conversion, should take care of all the conversion), don't bother with gl4es_ attributes.

If you have compile error, don't hesistate to open a ticket and I'll try to fix ShaderConv.

**Comment by ptitSeb** [comment]
@cl9x : did your GL shader worked? Can I close the issue or is there something to fix?

**Comment by cl9x** [comment]
Yes, everything is working. Thank you!

**Comment by ptitSeb** [comment]
Great!
