### ISSUE TITLE
Black blood in Arx Libertatis with gl4es

### ISSUE THREAD

**Issue by sandstranger** [ptitSeb/gl4es#468]
On Android with GLES 2.0 in Arx Libertatis blood is rendered as black squares. 
What cause this problem?

![Screenshot_2024-08-13-11-10-14-502_com arxlibertatis](https://github.com/user-attachments/assets/62a485a3-bfab-441c-ba80-c619aa9d706e)

**Comment by ptitSeb** [comment]
Probably a texture format unsupported by the hardware (and that gl4es didn't convert), or some issue with mipmaps. I you can, play with some if the env. var. to force/disable mipmap or shrik texture (unlikely to solve this one), or enable/disable some of the specials formats (look at USAGE.md)

**Comment by sandstranger** [comment]
Ok, I will try it.

**Comment by sandstranger** [comment]
ok, I fixed it, thanks for support

**Comment by ptitSeb** [comment]
Great! May I ask how?

**Comment by sandstranger** [comment]
engine supports I8 to L8A8 texture conversion
https://github.com/arx/ArxLibertatis/blob/master/src/graphics/opengl/GLTexture.cpp#L68

**Comment by ptitSeb** [comment]
Ah ok. Thanks for the details.
