### ISSUE TITLE
glMultiDrawElementsBaseVertex causes crash

### ISSUE THREAD

**Issue by Tungstend** [ptitSeb/gl4es#474]
[latest.log](https://github.com/user-attachments/files/17450259/latest.log)

**Comment by Tungstend** [comment]
Hi, pititSeb, I discovered a bug while testing Minecraft with sodium installed where the game crashed when calling glMultiDrawElementsBaseVertex. It seems that the call to copy_gl_array in glMultiDrawElementsBaseVertex encountered a bad pointer.

**Comment by Tungstend** [comment]
looks like [arrays_to_renderlist] also have the same problem

**Comment by Tungstend** [comment]
Btw, what does glDrawElementsCommon do? When I use glDrawElementsBaseVertex to implement glMultiDrawElementsBaseVertex, I find that glDrawElementsBaseVertex also causes a crash, but I don't know what glDrawElementsCommon does.

**Comment by Tungstend** [comment]
Solved, sorry for wasting your time

**Comment by ptitSeb** [comment]
What was the issue?

**Comment by Tungstend** [comment]
Of course there are other problems, but it seems that they are basically caused by calling gl3.x or gl4.x functions or using glsl150 and 330.

**Comment by Tungstend** [comment]
I know, I integrated shaderconverter from other project, but even though shaderconverter is more advanced, gl4es can't handle this shader correctly due to missing functions for gl3.x and 4.x
