### ISSUE TITLE
test-case: general or amigaos4 specific #5

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#54]
While trying to find roots of those quakes3's problems, give a go for some other test cases  and found some differences.

There is test-case: http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_5/warp_gl4es.c
(note it have "data" directory, with files flare.ppm and stars.ppm, they are need it for that example)

With legacy minigl i have that after running:
http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_5/warp_mgl.jpg

With gl4es version i have that:
http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_5/warp_gl4es.jpg

Probably can be again, amigaos4 only issues, but worth to note, as maybe it gl4es diffs as well.

**Comment by ptitSeb** [comment]
I see that in `drawFlare` you replaced `glBegin(MGL_FLATFAN);` with `glBegin(GL_TRIANGLES);`. But I assume it should be `glBegin(GL_TRIANGLE_FAN);` (because of the name, and also because there is 4 vertices).

**Comment by kas1e** [comment]
Yeah, but the point is that it replaced like this in both versions and give different visuals

**Comment by ptitSeb** [comment]
The issue is that the extra Vertex is then merged with the QUADS that comme after. If you don't use the glBegin(...)/glEnd() merger, it wont happens (use the ev. variable `LIBGLBEGINEND=0`)

I guess I can add some check in `glEnd()`, it wont be too expensive, but really, the bug is in the test program here.

**Comment by kas1e** [comment]
Basically that part whete mgl_flatten was, are about some texture drawing, which can be sikpped. 

I can made anothet one a bit later

**Comment by ptitSeb** [comment]
Commit 5829d6367d43d66e2082752e5e46b2d6b5562c1d added some check, that should fixes your sample.

**Comment by kas1e** [comment]
Tried that commit: fail to builds:

src/gl/gl.c: In function 'glDrawElementsCommon':
src/gl/gl.c:1088: warning: implicit declaration of function 'tex_setup_needchange'
src/gl/gl.c:1090: error: too many arguments to function 'tex_setup_texcoord'
src/gl/gl.c:1098: error: too many arguments to function 'tex_setup_texcoord'
src/gl/gl.c: In function 'gl4es_glDrawArrays':
src/gl/gl.c:1420: error: too many arguments to function 'tex_setup_texcoord'
src/gl/gl.c:1427: error: too many arguments to function 'tex_setup_texcoord'

**Comment by ptitSeb** [comment]
Are you sure you updated all the files? Travis seems to have no issues building it (and there is no warning in the build).
You can anyway use latest commit if you prefer.

**Comment by kas1e** [comment]
Yes, rebuilds latest commit fine.
But issues still here, so you can remove that additional check.

Probably you mix just part of code, which for now doing nothing , i will remove non-used one, and make another test case where everything right, to show the problem.

But in meantime you can remove that additional check for sure (as every bit cost :) )

**Comment by ptitSeb** [comment]
I don't think I have mixed commit. If you go to the "Commits" list of gl4es, you'll see that each commit today built on travis (the little green check, and you can probably click on it to see the travis log built).

The addition check, I'll not remove it, I have a done a function of it and added it to glDrawElements, glDrawArrays, and glBegin/glEnd loops, to be sure.

I'll test your sample on my VM to see if I can reproduce the issue.

**Comment by kas1e** [comment]
No no, i dont mean mixed commit, i mean probably you watch on that part of test-case which is not in work. I.e. that part about MGL_FLATTEN, etc,etc, its all about some texture drawing in center , which is part we don't see , i can remove it all together. Problem is with differen look of "starts". I.e. in minilg version they "fly", in the gl4es version they just rotates or something.

As for additional check : i checked glBegin/glEnd code-path with quake3 builded with latest commits: that make no differences for fps, so probably it not hurt indeed.

**Comment by ptitSeb** [comment]
Ok, I reproduce the issue on my VM, I'll debug now.

One thing I notice, it that it works first, then after a few loops, stop working...

**Comment by ptitSeb** [comment]
Ok, I know what the issue is: Texture WARP mode is set to GL_CLAMP were it should be left as GL_REPEAT.

I'll fix that, because I see no reason why to force it for those textures.

**Comment by ptitSeb** [comment]
Commit c1d51fbb89ee12989ded9ea59c5f67024d802c75 fixed the issue for me.

**Comment by kas1e** [comment]
> One thing I notice, it that it works first, then after a few loops, stop working...

Yeah ! its from time to time. One time you can after reboot run it all the time and it always the same. Anoher time, it work  first time, other times not. Another time, it didn't works first time, but others times are :)

**Comment by kas1e** [comment]
Yes it is! Awesome, thanks !
We can close that ticket for now probably :)
