### ISSUE TITLE
Characters broken on Zyn-Fusion

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/gl4es#55]
Zyn-Fusion is a audio synthesizer which uses OpenGL 2 to render its UI.

When running with GL4ES, the characters are broken.

![image](https://user-images.githubusercontent.com/1916518/37499181-50c3e8e8-28fd-11e8-8d68-38f8e8d644c2.png)

A apitrace is attached here.

[zyn-fusion.trace.gz](https://github.com/ptitSeb/gl4es/files/1817649/zyn-fusion.trace.gz)

**Comment by Icenowy** [comment]
BTW the broken character is rendered with GL4ES v1.0.4. With newest master it fails to compiler shader with the error `0:101(27): preprocessor error: syntax error, unexpected HASH_TOKEN`

**Comment by ptitSeb** [comment]
For the broken shader in latest version, can you uncomment line 9 of `sr/gl/preproc.c` to activate debug and paste here the console result.

The broken font are, I assume, an issue of NPOT texture, and `LIBGL_FORCENPOT=1` may fix it, but it will work better on latest version.

**Comment by Icenowy** [comment]
For shader debugging, see https://gist.github.com/Icenowy/91adf6af3c59864aecd7d63ce18c1556

NPOT will be tested by the original tester, @liushuyu , he discovered this issue at first.

**Comment by liushuyu** [comment]
Hi there,

There's another screen shot showing Zyn-Fusion running using `gl4es` (Environment variables: `LIBGL_ES=2 LIBGL_FORCENPOT=1`)

![2018-03-15 22-39-01 screenshot](https://user-images.githubusercontent.com/6829345/37504285-f8ae4e00-28a2-11e8-836a-daa761bf124b.png)

**Comment by ptitSeb** [comment]
It should be fixed now, with edac74daa5ec55c9ed663357c346084ee3e4d917

**Comment by liushuyu** [comment]
>It should be fixed now, with edac74d

Fix confirmed, the UI now rendered properly. Thanks.
