### ISSUE TITLE
Crash when playing PARSEC47

### ISSUE THREAD

**Issue by M-HT** [ptitSeb/gl4es#59]
Using the latest gl4es with [PARSEC47](https://github.com/M-HT/parsec47) crashes the game (when loosing a life) with the following error (tested on Raspberry Pi 3):
> *** Error in `./PARSEC47': realloc(): invalid next size: 0x0133aa18 ***

I tracked it to commit f3f784b8a008edeb24c6594a84f3836f1f12679a - more precisely to this line
`            || (l->stage==STAGE_POSTDRAW && l->open /*&& l->use_glstate*/))` in function NewDrawStage in file src/gl/list.c (in latest gl4es it's in file src/gl/listrl.c).
`&& l->use_glstate` was commented out in the commit. If I uncomment it (in the commit or in the latest gl4es), the crash is gone.

**Comment by ptitSeb** [comment]
Should be fixed with fe365fabde79be3ffeee2296b350e779651cf66c

**Comment by M-HT** [comment]
I tested the fix (on Raspberry Pi 3) and the crash is gone. Good job.
