### ISSUE TITLE
Flipped textures in gles2 mode after 36bc4b3c3308e29c6cb6df5fa363f6cd96d02e77

### ISSUE THREAD

**Issue by xyzz** [ptitSeb/gl4es#60]
Hi, I've been updating openmw for android and noticed that textures are flipped vertically in GLES2 mode now. I've bisected it to the following commit

36bc4b3c3308e29c6cb6df5fa363f6cd96d02e77:
![](https://i.imgur.com/X1Gel6g.jpg)

7e3e9f14e0ad7dc2b69124fd3c2c8c69f932adaf:
![](https://i.imgur.com/te1ShEC.jpg)

It seems that only GLES2 mode is affected, using GLES1 the textures appear normally.

Device: LG Nexus 5x

**Comment by ptitSeb** [comment]
Ah, oops.
Should be fixed with 509d3843b2fe273eec85a8242a7ddab62be8bad0

**Comment by xyzz** [comment]
Yep it works, thank you.
