### ISSUE TITLE
gl4es Seem to work, but for some reason runs as slow as a software rasterizer after installing RetroPie on orange pi

### ISSUE THREAD

**Issue by prenex** [ptitSeb/gl4es#65]
This is kind of a weird issue and I do not know what is the root cause and where to fix this.
Also contacted armbian and retrorangepi forums for information:

https://forum.armbian.com/topic/7662-gl4es-maybe-hw-gl-not-working-after-retropie-setupsh/?tab=comments#comment-57721
http://orangepi.club/showthread.php?tid=2536&pid=5146#pid5146

In short: gl4es was already working on my orangepi pc-plus and I had good frame rate with extreme-tux-racer. Earlier my only problem was supertuxkart showing a blue-only screen and music but nothing from the game but I could live with that... Then I installed a retrorangepi-version of Retropie on my armbian and now somehow it seems that gl4es still logs out itself as before, it seems to work as before except it is now as slow as the software renderer. I tried and the frame-rate is so much the same that I guess it is really the very same....

Below is the log of starting extreme tux racer (etr) with doing an export LD_LIBRARY_PATH="$HOME/install/gl4es/lib" and export LIBGL_ES=2

```
LIBGL:loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
MESA-LOADER: failed to retrieve device information
libEGL warning: DRI2: failed to open mali_drm (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
LIBGL: Hardware Limited NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer detected
LIBGL: Extension GL_OES_element_index_uint detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected and used
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Extension GL_EXT_texture_rg detected and used
LIBGL: Extension GL_OES_texture_float detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 8(8), Max lights: 8, Max planes: 6
LIBGL: Hardware vendor is VMware, Inc.
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.0
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Current folder is:/home/p/install/gl4es
MESA-LOADER: failed to retrieve device information
libEGL warning: DRI2: failed to open mali_drm (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
```

Sadly I do not remember if the libegl warnings were there even while it worked well.

I do not think too much this is a problem with gl4es itself (as it worked before), but it would be nice to know what could go wrong and how it is possible to have gl4es running and seeing only the very same frame rate as in the software rendered case. I tried to test if my GLES is also running in software mode and I got 77 points on `glmark2-es2` for which armbian people quessed that I have non-software rendering. Also when run es2gears I get 80% CPU usage and when I run glxgears I get 220% which seem to indicate ES2 is ok, but for some reason even though I start the app with gl4es I somehow get software rendering.

PS.: Now glshim does not seem to work at all and it is just segfaulting, but that is an other case. Maybe I see the gl4es startup logged but it just not doing any work because there is an issue? Or is it maybe possible that it finds some random software renderer that es2gears otherwise is not using?

**Comment by ptitSeb** [comment]
I don't think you are using MALI hardware here.
Look at this line:
```
LIBGL: Hardware vendor is VMware, Inc.
```
For MALI, Hardware vendor should be ARM.
There is something wrong with wich EGL/GLES2 driver is loaded (MESA/Software instead of MALI one).

**Comment by ptitSeb** [comment]
Also,  note that with `LIBGL_EGL` and `LIBGL_GLES` you can specify custom name for libEGL and libGLES in case it's different (or with a specific location) for you.

**Comment by prenex** [comment]
Nice spotting!!! I will try to find out what causes vmware to be printed there...

Earlier it was "Hardware vendor is ARM"
Is it possible to know where is the driver that we are using?

**Comment by ptitSeb** [comment]
to see what lib are loaded, the easier way is to use lsof in another terminal while glxgears is running:
`lsof | grep glxgear`
should help.

**Comment by ptitSeb** [comment]
So, any news on this? Did you got back 3D hardware acceleration?

**Comment by ptitSeb** [comment]
Ah sure! Have a nice holiday ;)

**Comment by prenex** [comment]
Thank you very much :-)

Indeed now I can see that es2gears is using /dev/mali while just running glxgears with your shared object somehow is not doing so the reason is still a bit unknown to me, but I am looking too...

See attached files...
[ldd_es2gears.txt](https://github.com/ptitSeb/gl4es/files/2215401/ldd_es2gears.txt)
[ldd_gl4es_so.txt](https://github.com/ptitSeb/gl4es/files/2215402/ldd_gl4es_so.txt)
[es2gears_out.txt](https://github.com/ptitSeb/gl4es/files/2215403/es2gears_out.txt)
[glxgears_gl4es_out.txt](https://github.com/ptitSeb/gl4es/files/2215404/glxgears_gl4es_out.txt)

From these there is one interesting point to me: I also checked es2gears with "ldd" to see what *.so files it uses and it seems to refer to libGLESv2.so.2 in a subdirectory called "mali-egl" while everywhere else I see "mesa-egl" subdirectory in the other listings. Also when I "ldd" your shared object, it does not seem to refer to libGLESv2.so.2 at all - but maybe that is normal I guess for some reason.

These two directories are seemingly having different files for libGLESv2.so.2 as you can see:

```
p@orangepipcplus:~$ ls -lat /usr/lib/arm-linux-gnueabihf/mali-egl/
total 1748
drwxr-xr-x 77 root root   69632 Jul  8 10:02 ..
drwxr-xr-x  2 root root    4096 Jan 27 18:07 .
lrwxrwxrwx  1 root root      10 Jan 24 20:08 libEGL.so.1.0.0 -> libMali.so
lrwxrwxrwx  1 root root      17 Jan 24 20:08 libGLESv1_CM.so -> libGLESv1_CM.so.1
lrwxrwxrwx  1 root root      21 Jan 24 20:08 libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.1.0
lrwxrwxrwx  1 root root      10 Jan 24 20:08 libGLESv1_CM.so.1.1.0 -> libMali.so
lrwxrwxrwx  1 root root      14 Jan 24 20:08 libGLESv2.so -> libGLESv2.so.2
lrwxrwxrwx  1 root root      18 Jan 24 20:08 libGLESv2.so.2 -> libGLESv2.so.2.0.0
lrwxrwxrwx  1 root root      10 Jan 24 20:08 libGLESv2.so.2.0.0 -> libMali.so
lrwxrwxrwx  1 root root      11 Jan 24 20:08 libEGL.so -> libEGL.so.1
lrwxrwxrwx  1 root root      15 Jan 24 20:08 libEGL.so.1 -> libEGL.so.1.0.0
-rw-r--r--  1 root root      38 Jan 24 20:08 ld.so.conf
-rw-r--r--  1 root root 1706364 Jan 24 20:08 libMali.so
p@orangepipcplus:~$ ls -lat /usr/lib/arm-linux-gnueabihf/mesa-egl/
total 256
drwxr-xr-x 77 root root  69632 Jul  8 10:02 ..
drwxr-xr-x  2 root root   4096 Jul  6 21:06 .
-rw-r--r--  1 root root 142532 Jun 14 17:52 libEGL.so.1.0.0
-rw-r--r--  1 root root  34092 Jun 14 17:52 libGLESv2.so.2.0.0
lrwxrwxrwx  1 root root     15 Jun 14 17:51 libEGL.so -> libEGL.so.1.0.0
lrwxrwxrwx  1 root root     15 Jun 14 17:51 libEGL.so.1 -> libEGL.so.1.0.0
lrwxrwxrwx  1 root root     18 Jun 14 17:51 libGLESv2.so -> libGLESv2.so.2.0.0
lrwxrwxrwx  1 root root     18 Jun 14 17:51 libGLESv2.so.2 -> libGLESv2.so.2.0.0
-rw-r--r--  1 root root     38 Jun 14 17:51 ld.so.conf
p@orangepipcplus:~$ 
```

I kind of have the impression that this is the problem and es2gears can find the mali one as I can see from its "ldd", but what bugs me is that in the lsof result of es2gears I do not see this "mali-egl" directory stuff at all... That kind of bugs me a bit :-)

I am not sure if it is safe to either remove the "mesa-egl" subdir or relink that to the other shared object or if I will have any problem with other software I might build later, but I will try to add these locations using LIBGL_EGL and LIBGL_GLES and tell the result.

**Comment by prenex** [comment]
I used the found locations by adding the LIBGL_EGL and LIBGL_GLES environment variables.

Now I see: `LIBGL: Hardware vendor is ARM`

Things seem to work well now as before. I close the issue ;-)
Btw it could be good to document these two env wars in the USAGE.md as they seem quite useful.

http://linux-sunxi.org/Mali_binary_driver#Verifying_the_EGL.2FGLES_driver_stack

^^Here they say that it is ok to move away the whole directory, in which case I guess I would not need to mess with env wars, but I am happy as it is now. If other GLES programs will complain I will possibly rename the whole directory to somewhere, but I will try to keep it in mind that I have that dir here so I can always choose what I use...

Thank you for your help.

**Comment by ptitSeb** [comment]
Glad it works now.

So I forgot to document LIBGL_EGL and LIBGL_GLES in USAGE.md? Ouch, I'll document that tomorrow, thanks for the heads up!
