### ISSUE TITLE
Error while gathering supported extension

### ISSUE THREAD

**Issue by RootLUG** [ptitSeb/gl4es#68]
Hello,
I'm trying to get gl4es working on Android. To be more specific, I'm running UserLAnd (https://github.com/CypherpunkArmory/UserLAnd) which is like a chroot and inside is ubuntu filesystem where I installed gl4es. Since android GUI is very different from linux one, I use XSDL as virtual Xorg server (https://github.com/pelya/xserver-xsdl) where I redirect GUI apps from the userland chroot via DISPLAY env. Everything works fine (like LXDE, GIMP etc...) except OpenGL apps which I'm trying to patch via gl4es.

I compiled gl4es inside the chroot multiple times, using every device option found in docs but all throw a segfault when trying to run glxgears such as this:
```
user@localhost:~$ glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep  8 2018 19:04:06
LIBGL: Using GLES 1.1 backend
LIBGL: warning, gles is NULL
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 1.1 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: warning, gles_glGetIntegerv is NULL
Segmentation fault
```
Same result also when I tried to change LIBGL_FB to 1, 2, or 3 and ES backend to 2.
I found this issue at XSDL repo: https://github.com/pelya/xserver-xsdl/issues/45  so I'm not even sure if it's possible to get gl4es running the way I'm trying to do?
Is it possible to enable more debug options? When trying to run it in gdb it immediately exit with error code 128 without any stdout/stderr and gdb says the backtrace is empty so I wasn't able to extract more info about the error.

On the technical side, the Android version is 7.1.1. Hardware is Yoga book (https://www.lenovo.com/us/en/tablets/android-tablets/yoga-book-series/Lenovo-Yoga-Book/p/ZZITZTOYB1F) which has Intel® Atom™ x5-Z8550 Processor (2.40GHz 2MB) 64bit

Thanks for help!

**Comment by ptitSeb** [comment]
GLEs extension are null because "gles is NULL", that mean gl4es cannot load libGLES_CM.so. Maybe it's not there is not that lib. Do you know the name of the libs and were to find them (eithr ES1 or ES2)? If yes, you can force to load it using LIBGL_GLES=/path/to/libGLESXXX.so

**Comment by ptitSeb** [comment]
Also, to add some technical detail: the loading of EGl and GLES library is done in https://github.com/ptitSeb/gl4es/blob/master/src/gl/loader.c

You can see that, for ES1, the lib names `libbrcmGLESv1_CM`, `libGLESv1_CM` and `libGLES_CM` with extensions  `so`, `so.1`, `so.2`, `dylib` and `dll` in folders   `/opt/vc/lib/`, `/usr/local/lib/`, `/usr/lib/` and no folder (meaning system reachable) are tested. But somehow, it doesn't found the lib.

**Comment by RootLUG** [comment]
I've done some testing now. the GLESv2 is loaded fine but also fails with same error pasted below. Ubuntu 18.04 removed the GLESv1 and the only one I could fine is provided by nvidia driver so I installed it just to get the so library in system. After that the gles is found but still fails with this error:
```
user@localhost:~/gl4es/gl4es-master$ LIBGL_ES=1 glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep  9 2018 11:08:06
LIBGL: Using GLES 1.1 backend
LIBGL:loaded: libGLESv1_CM.so
LIBGL:loaded: libEGL.so
LIBGL: Using GLES 1.1 backend
LIBGL: Error while gathering supported extension (eglInitialize: EGL_BAD_DISPLAY), default to none
Segmentation fault
```
Same error is for GLESv2 backend. I can also try it under debian if that would help as I assume the glesv1 should be still there in the official repository. Not sure if this is related to origin from nvidia driver as the cpu has a bultin GPU that is intel based

**Comment by ptitSeb** [comment]
If ES1 is deprecated, use ES2. It's more powerfull and works fine now.

Now, that EGL_BAD_DISPLAY sounds bad. At this moment (the gathering supported extension), the EGL context should work, no mater what, so that sound bad. Do you have the exact same output with ES2?

**Comment by RootLUG** [comment]
Sorry, it's not the same one, I haven't noticed that nvidia overwritten the gl4s shim library.
The precise error for ES2 is:
```
user@localhost:~$ glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep  9 2018 11:08:06
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: Current folder is:/home/user
Segmentation fault
```

**Comment by ptitSeb** [comment]
Why do you have NVidia libs when you use intel atom? Shouldn't that be Intel libs?
Also, Atom should have a full libGL available, no?

Anyway, the issue here is that GL4ES can't create a pbuffer context. Everything is there, all libs are present and initialize correctly, but  the pbuffer creation faiL. That still doesn't sounds good. For testing, you can try `LIBGL_NOTEST=1` to avoid thta pbuffer creation, but I don't think it will be abble to create regular X11 context if it cannot create a pbuffer one...

**Comment by RootLUG** [comment]
I installed the nvidia one as they were the only deb package that had .so lib for GLESv1 (searched whole ubuntu repository). I also tried the intel ones but same result. when running with LIBGL_NOTEST=1, this is the output produced:
```
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep  9 2018 11:08:06
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Hardware test disabled, nothing activated...
LIBGL: Targeting OpenGL 2.0
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Current folder is:/home/user
Segmentation fault
```
Sadly, I have no idea why it's behaving differently in gdb to track the segfault as this is what gdb outputs (I verified that env variables are correct to point the DISPLAY to XSDL one):
```
(gdb) r
Starting program: /usr/bin/glxgears 
During startup program exited with code 182.
(gdb) backtrace
No stack.
```
Might that be the limitation that I use XSDL as xorg emulation/rendering?

**Comment by ptitSeb** [comment]
Unccoment line 37 of src/glx/glx.c https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L37 to have more debug output. I assume something bad happens during context creation, but it's difficult to say.

**Comment by RootLUG** [comment]
Here's the output:
```
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep  9 2018 11:08:06
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Hardware test disabled, nothing activated...
LIBGL: Targeting OpenGL 2.0
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Current folder is:/home/user
glXChooseVisual(0x500000210ec0, 0, 0x7fff9dae1f00)
glXChooseFBConfig(0x500000210ec0, 0, 0x7fff9dae1f00, 0x7fff9dae1ddc)
FBConfig rgba=1
FBConfig doubleBufferMode=1
FBConfig redBits=5
FBConfig greenBits=6
FBConfig blueBits=5
FBConfig depthBits=1
glXCreateContext(0x500000210ec0, 0x5000002121c0, (nil), 1), latest_visual=0x5000002121c0, fbcontext_count=0Creating R:5 G:6 B:5 A:0 Depth:1 Stencil:8 Multisample:0/0
blah.sh: line 1: 28167 Segmentation fault      LIBGL_NOTEST=1 glxgears
```

**Comment by ptitSeb** [comment]
So, last line printf'd is https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L459

But at this stage, no EGL call has been done yet (because LIBGL_NOTEST=1 is used). Can you try putting some printf https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L516 and https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L530 to see if it goes that far?

**Comment by RootLUG** [comment]
It does not, I jsut played with printf and found out it's the call to `bcm_host_init();` that fails (function body as pointer looks legit, e.g. not NULL). after commenting it, the glxgears runs but with corrupted output:
![screenshot_2018-09-10-14-05-15-779](https://user-images.githubusercontent.com/3605898/45296551-afdf2900-b502-11e8-844d-da685e5300ec.jpeg)

when passing LIBGL_FB=1 , 2 or 3 the output is just plain black.

**Comment by RootLUG** [comment]
To be more specific, the exact line that I'm referring to is https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L687 . Just verified with a bunch of prints around that this is the spot. 
Note: the gl4es is compiled with BCMHOST profile, I thought that would be the closest to my hardware.

**Comment by ptitSeb** [comment]
Oh, ok.
BCMHOST is for RasperyPI, or other hardware with Broadcom Video Hardware (if that exist). You sould not use that. Also, I'm surprise it find the bcm libs to initalize `bcm_host_init()`, that is a function pointer, dependaing on `bcm_host` that is a library pointer initiazed here: https://github.com/ptitSeb/gl4es/blob/master/src/gl/loader.c#L90

Can you recompile without BCMHOST and try again?

**Comment by RootLUG** [comment]
I recompiled it from freshly cloned repo as the BCMHOST part was still executed even when I disabled it in cmake. Anyway, the visual output is same as the one described when I commented out bcm_host_init: e.g. distorted picture on default settings, plain black when setting LIBGL_FB to any value (1-3). This is the cli output:
```
user@localhost:~/gl4es-master$ glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep 10 2018 13:07:44
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: Current folder is:/home/user/gl4es-master
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
285 frames in 5.0 seconds = 56.999 FPS
300 frames in 5.0 seconds = 59.980 FPS
^C
user@localhost:~/gl4es-master$ LIBGL_FB=1 glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep 10 2018 13:07:44
LIBGL: framebuffer output enabled
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: glXMakeCurrent FBO workaround enabled
LIBGL: Current folder is:/home/user/gl4es-master
LIBGL: ERROR: EGL Error detected: EGL_BAD_NATIVE_WINDOW (0x0)
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
129105 frames in 5.0 seconds = 25820.938 FPS
129264 frames in 5.0 seconds = 25852.623 FPS
^C
user@localhost:~/gl4es-master$ LIBGL_FB=2 glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep 10 2018 13:07:44
LIBGL: using framebuffer + fbo
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: glXMakeCurrent FBO workaround enabled
LIBGL: Current folder is:/home/user/gl4es-master
LIBGL: ERROR: EGL Error detected: EGL_BAD_NATIVE_WINDOW (0x0)
LIBGL: Error while creating main fbo (0x8CD6)
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
13448 frames in 5.0 seconds = 2689.571 FPS
^C
user@localhost:~/gl4es-master$ LIBGL_FB=3 glxgears
LIBGL: Initialising gl4es
LIBGL: v1.0.9 built on Sep 10 2018 13:07:44
LIBGL: using pbuffer
LIBGL: Using GLES 2.0 backend
LIBGL:loaded: libGLESv2.so.2
LIBGL:loaded: libEGL.so.1
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglChooseConfig: EGL_SUCCESS), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: Current folder is:/home/user/gl4es-master
```

**Comment by RootLUG** [comment]
This is the output of eglinfo:
```
user@localhost:~$ LIBGL_FB=3 eglinfo            
EGL client extensions string:
    EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses
    EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_wayland
    EGL_EXT_platform_x11 EGL_MESA_platform_gbm
    EGL_MESA_platform_surfaceless

GBM platform:
eglinfo: eglInitialize failed

Wayland platform:
error: XDG_RUNTIME_DIR not set in the environment.
eglinfo: eglInitialize failed

X11 platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4 (DRI2)
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_KHR_cl_event2 EGL_KHR_config_attribs
    EGL_KHR_context_flush_control EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 16  0  5  6  5  0  0  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x02 16  0  5  6  5  0 16  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x03 16  0  5  6  5  0 24  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x04 16  0  5  6  5  0 24  8  0 0 0x21TC      y  y  y  y     win,pb,pix
0x05 16  0  5  6  5  0 32  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x06 24  0  8  8  8  0  0  0  0 0 0x41TC      y  y  y  y     win,pb,pix
0x07 24  0  8  8  8  0 16  0  0 0 0x41TC      y  y  y  y     win,pb,pix
0x08 24  0  8  8  8  0 24  0  0 0 0x41TC      y  y  y  y     win,pb,pix
0x09 24  0  8  8  8  0 24  8  0 0 0x41TC      y  y  y  y     win,pb,pix
0x0a 24  0  8  8  8  0 32  0  0 0 0x41TC      y  y  y  y     win,pb,pix
```

**Comment by ptitSeb** [comment]
Ah thanks. Intersting, it seems the EGL part has no config with alpha channel.

Just to try, can you change at https://github.com/ptitSeb/gl4es/blob/master/src/glx/hardext.c#L92 to `EGL_ALPHA_SIZE, 0,` (to change alpha from 8 to 0). I think this will allow the hardware testing to run.

**Comment by RootLUG** [comment]
This is fantastic, thank you very much for the help. Glxgears is now running fine with LIBGL_FB=3. (other modes 1/2 gives black square).

**Comment by ptitSeb** [comment]
Ok, with commit 77334f06afd19586b2b67196837099e87ce360dc I have added an autodetection of this. Can you test it (so we can close this issue if it works) ?

**Comment by RootLUG** [comment]
Just tested it and it works great. Is there a way of setting LIBGL_FB to 3 by default on compile time like the DEFAULT_ES option? Haven't found it when searching.

From testing perspective I've been meanwhile trying to run other opengl apps to see what works and what not. Should I create a separate issue for "LIBGL: unknown attrib 32786" ? (docs: https://doc.servo.org/x11_dl/glx/constant.GLX_X_RENDERABLE.html, https://www.khronos.org/opengl/wiki/Multisampling#X_Windows_.28using_GLX.29). I see it defined in the header files but not in the case switch here: https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L189 to handle it

**Comment by ptitSeb** [comment]
I haven't put a default "FB" settings, so you need to stick to `export LIBGL_FB=3` for now. I'll see what I can do in the future for this.

For the other bug, yeah, i think a seperate bug report is better. Anyway, the analyse is already done, I'll add the switch in the case.

**Comment by RootLUG** [comment]
Great, thanks again. I will close the issue as this one is resolved and create a new one for the other. I could take a look at making the default FB settings for compile option during the weekend as I know a little bit of C and this sounds easy enough so I can at least contribute back :)

**Comment by ptitSeb** [comment]
Thanks.
Contributions are welcomed :) !

**Comment by mittorn** [comment]
You need to run renderer ln android side or use libhybris to load native drivers.
glshim proxy mode maybe useful (i do not know if it exist in gl4es)
Also, i have some success with virglrenderer on tegra k1, but it  is slow and incompatible with most mobile GPUs (but gles2 is still in roadmaps)

**Comment by ptitSeb** [comment]
There is no proxy mode in gl4es.

**Comment by mittorn** [comment]
Need just proxy gles calls. It is simplier and will require less ipc sends

**Comment by mittorn** [comment]
https://github.com/shodruky-rhyammer/gl-streaming
this should be useful (seems to support gles2), but need rewrite context creation to pass attribs and client part to work in main thread

**Comment by seisdr** [comment]
Is this fixed
Still facing segfault here

**Comment by ptitSeb** [comment]
@seisdr : you have a segfault at what moment?

**Comment by seisdr** [comment]
```
root@localhost:~/gl4es/build# glxgears
LIBGL: Initialising gl4es
LIBGL: v1.1.3 built on Feb  3 2020 19:32:43
LIBGL: Using GLES 2.0 backend
LIBGL: warning, gles is NULL
LIBGL: warning, egl is NULL
LIBGL: Float and Half-Float texture support disabled
LIBGL: warning, egl_eglBindAPI is NULL
LIBGL: warning, egl_eglInitialize is NULL
LIBGL: warning, egl_eglGetDisplay is NULL
LIBGL: warning, egl_eglCreatePbufferSurface is NULL
LIBGL: warning, egl_eglDestroySurface is NULL
LIBGL: warning, egl_eglDestroyContext is NULL
LIBGL: warning, egl_eglMakeCurrent is NULL
LIBGL: warning, egl_eglChooseConfig is NULL
LIBGL: warning, egl_eglCreateContext is NULL
LIBGL: warning, egl_eglQueryString is NULL
LIBGL: warning, egl_eglTerminate is NULL
LIBGL: Using GLES 2.0 backend
Segmentation fault
```

**Comment by ptitSeb** [comment]
Yeah, no EGL driver, no GLESv2 driver. No surprise you have a segfault here.

I'm unsure, what is the situation here? There is no EGL/GLES support on your system?

**Comment by seisdr** [comment]
Maybe I need to build it on termux not proot

**Comment by mittorn** [comment]
To use it on android, you need to port server to android. It is not very hard because it already uses egl. Termux does not support any graphics and termux libraries even may conflict with android libraries preventing driver to work
Second, gl-streaming does not implement all needed calls for gl4es. I added some stubs to https://github.com/mittorn/gl-streaming, but it does still cannot compile shaders. To fix it, need to extend gl-streaming protocol with missing functions, implement all glGet, attrib location queries, etc...
And maybe do something with client arrays, i not sure that it works correctly

**Comment by seisdr** [comment]
@RootLUG may I ask you if your phone rooted or not

**Comment by RootLUG** [comment]
@seisdr no it wasn't.

**Comment by seisdr** [comment]
Maybe there's something special with Yoga book phone it look like an pc , anyway thanks

**Comment by RootLUG** [comment]
Yeah, could be, it has intel CPU & GPU which is very unusual for an Android device as most are ARM-based.

**Comment by mittorn** [comment]
This does not matter, you could not get gles support in linux chroot because it does not support hardware GLES in chroot. You only may use gl4es in android app, not in console application. If device using drm, maybe it is possible to use gbm and mesa intel driver, but you will need to kill android before
maybe it is possible to use libhybris, but there is no way to create context now.

**Comment by seisdr** [comment]
mittorn he's the best 😍

**Comment by khanhduytran0** [comment]
> need to extend gl-streaming protocol with missing functions, implement all glGet, attrib location queries, etc...

With my fork, I implemented a lot, but not all, the maximum reach of GL4ES at the moment is `glx*` worked but no texture and color (confirmed in `glxdemo` and `glxheads`, maybe with `glxgears` but because same black background so didn't see gears), some other crashes with `glBufferData`.
![Screenshot_2020-07-03-15-56-06](https://user-images.githubusercontent.com/40482367/87150568-877e0c80-c2dc-11ea-8333-642fe4871a5b.png)
