### ISSUE TITLE
Add handling for GLX_X_RENDERABLE attribute

### ISSUE THREAD

**Issue by RootLUG** [ptitSeb/gl4es#69]
A switch case for GLX_X_RENDERABLE attribute is missing in the https://github.com/ptitSeb/gl4es/blob/master/src/glx/glx.c#L189 to set the correct value which could cause some apps to crash with the following error: `LIBGL: unknown attrib 32786`

References:
https://doc.servo.org/x11_dl/glx/constant.GLX_X_RENDERABLE.html
https://www.khronos.org/opengl/wiki/Multisampling#X_Windows_.28using_GLX.29

**Comment by ptitSeb** [comment]
Should be fixed with commit da9e57f06677e6205a6ea0d8993b6536a38e6026

**Comment by RootLUG** [comment]
Confirmed it works
