### ISSUE TITLE
glx.c cause error: glxContext undeclared (first use in this function)

### ISSUE THREAD

**Issue by khanhduytran0** [ptitSeb/gl4es#71]
https://github.com/ptitSeb/gl4es/blob/68b5880a913199c87ffbe83e3ede20e8b551a79e/src/glx/glx.c#L102

Build by AIDE (because i don't have any computers😋)

`target=android-19`

Application.mk:
`NDK_TOOLCHAIN_VERSION := 4.9`
`APP_STL := gnustl_static`
`APP_ABI := armeabi-v7a x86`

![img_20180921_095708](https://user-images.githubusercontent.com/40482367/45857826-d021aa00-bd84-11e8-8500-f7ae067f8b79.jpg)

**Comment by ptitSeb** [comment]
Should be fixed with commit 9c8933f0d83f0b701cf71e3a8c4c456735cec056

**Comment by khanhduytran0** [comment]
Compiled, thanks!

**Comment by Malaska678** [comment]
@khanhduytran0 Actually its kdt before making any launcher :P

**Comment by khanhduytran0** [comment]
Well you even go there ?(move to another place to talk)
