### ISSUE TITLE
Retroarch not rendering OSD messages and overlays

### ISSUE THREAD

**Issue by eadmaster** [ptitSeb/gl4es#74]
I am trying GL4ES v1.1.0 on my OrangePI-PC running vanilla armbian with kernel v3.4.113-sun8i.

With [EmulationStation](https://github.com/Aloshi/EmulationStation) it is working pretty well, while with Retroarch (v1.3.6, compiled myself) i am having some rendering issues:
 - missing OSD messages (maybe related to [this old one](https://github.com/ptitSeb/gl4es/issues/35)?)
 - overlays are not shown

As RA video_driver i am using "sdl2", "gl" does not work at all.

**Comment by ptitSeb** [comment]
Can you try with latest sources, I've fixed some potentials FBO issues lately (yesterday in fact) that may help.

**Comment by ptitSeb** [comment]
I'm not reproducing the issue on my VM.
If you run retroarch with `-v` to have more verbose output, do you see something relevent?

(also, just to be sure, you just download some overlay, then forcing some overlay in menu, like a "gb border" or is this something else)

**Comment by eadmaster** [comment]
I've checked the overlays were enabled and also tried changing them in the menu, but nothing changed.
I'll try again this weekend to check the RA verbose log, thank you for the tip.

**Comment by eadmaster** [comment]
I've found this error in the RA verbose log:
```
[ERROR] Overlay interface is not present in video driver, or not enabled.
[ERROR] Overlay interface is not present in video driver, or not enabled.
```

The RA build i am currently using is [here](http://eadmaster.altervista.org/pub/prj/builds/retroarch_1.7.5-1_armhf.deb).

**Comment by ptitSeb** [comment]
Are you sure it's gl4es issue? If you try with mesa instead of gl4es, do you get Overlays?

**Comment by eadmaster** [comment]
i've tried running without GL4ES in `LD_LIBRARY_PATH` and there is still no overlay, so probably this is not related to gl4es at all...

**Comment by ptitSeb** [comment]
Yeah, sorry, that's what I thought. And I don't really know the build system of Retroarch, so I cannot really help you here.
