### ISSUE TITLE
GLES1 doesn't work

### ISSUE THREAD

**Issue by xyzz** [ptitSeb/gl4es#78]
So I'm updating my openmw android port to latest gl4es and it seems at some point GLES1 got broken. The output is just a blue-ish rectangle and the logcat is spammed with

```
12-22 23:17:35.959 18015 18083 I Adreno-UNKNOWN: <glDrawArrays:4895>: glDrawArrays is called with VERTEX_ARRAY client state disabled!
12-22 23:17:35.970 18015 18083 I Adreno-UNKNOWN: <glDrawArrays:4895>: glDrawArrays is called with VERTEX_ARRAY client state disabled!
12-22 23:17:35.970 18015 18083 E Adreno-UNKNOWN: <glTexParameteriv:151>: GL_INVALID_ENUM
```

and later on

```
12-22 23:17:45.403 18015 18083 I Adreno-UNKNOWN: <glDrawArrays:4895>: glDrawArrays is called with VERTEX_ARRAY client state disabled!
12-22 23:17:45.407 18015 18083 I Adreno-UNKNOWN: <glDrawElements:4976>: glDrawElements is called with VERTEX_ARRAY client state disabled!
12-22 23:17:45.407 18015 18083 I Adreno-UNKNOWN: <glDrawArrays:4895>: glDrawArrays is called with VERTEX_ARRAY client state disabled!
```

I'll try bisecting it tomorrow, reporting the issue now just in case you have an idea about the problem. The last commit I used that's working fine is 509d3843b2fe273eec85a8242a7ddab62be8bad0

**Comment by ptitSeb** [comment]
Wow, sounds bad. I'll try to reproduce on my side, using Linux/ARM.

**Comment by ptitSeb** [comment]
I tested on my side, and it's working (at least visually).
![openmw13](https://user-images.githubusercontent.com/3250792/50382012-8901c880-0695-11e9-90b8-d31e29efee75.png)

I used `--skip-menu --start="Sadrith Mora"` command line argument to quick start. Do you get the bad behavour all the time, even on loading screen?

**Comment by xyzz** [comment]
Yeah, both menu and in-game.

**Comment by xyzz** [comment]
Okay, the issue seems to be the `LOCAL_CFLAGS += -DDEFAULT_ES=2` in Android.mk. Not sure if it's a bug or I'm just misunderstanding how it's supposed to work. But when commenting it out, both gles1 and gles2 work again, switching between done with an environment variable.

**Comment by ptitSeb** [comment]
Oh really, that's odd?! I'll try to understand that later. Glad it work now.
If you have some graphical issue remaining on OpenMW, don't hesitate to create a new issue (it seems clean on my side, but I'm not a MW player...).

**Comment by xyzz** [comment]
Fwiw, since d53be24773bbe0085d9e9e75ede5c2c7de509099 I have to patch Android.mk and set DEFAULT_ES=1, then both gles1 and gles2 work, otherwise, it's the same issue with context failing to initialize when using gles1 and library compiled with DEFAULT_ES=2.

**Comment by ptitSeb** [comment]
Is it ok now with 18a59fac0403ad3a79d0445f62eeefe166674808 ?

**Comment by xyzz** [comment]
Yeah, it works as expected
