### ISSUE TITLE
gl4es/src/glx/gbm.c:171:19: error: unknown type name ‘EGLConfig’

### ISSUE THREAD

**Issue by dsx724** [ptitSeb/gl4es#84]
Compile error on Ubuntu 18.04 arm64
                                                                              
~/gl4es$ cmake . -DNOEGL=1 -DDEFAULT_ES=2                                                                                                                                              
-- Configuring done
-- Generating done
-- Build files have been written to: ~/gl4es
~/gl4es$ make
[  1%] Building C object src/CMakeFiles/GL.dir/gl/array.c.o
[  3%] Building C object src/CMakeFiles/GL.dir/gl/blit.c.o
[  5%] Building C object src/CMakeFiles/GL.dir/gl/blend.c.o
[  6%] Building C object src/CMakeFiles/GL.dir/gl/buffers.c.o
[  8%] Building C object src/CMakeFiles/GL.dir/gl/debug.c.o
[ 10%] Building C object src/CMakeFiles/GL.dir/gl/decompress.c.o
[ 11%] Building C object src/CMakeFiles/GL.dir/gl/depth.c.o
[ 13%] Building C object src/CMakeFiles/GL.dir/gl/directstate.c.o
[ 15%] Building C object src/CMakeFiles/GL.dir/gl/drawing.c.o
[ 16%] Building C object src/CMakeFiles/GL.dir/gl/enable.c.o
[ 18%] Building C object src/CMakeFiles/GL.dir/gl/eval.c.o
[ 20%] Building C object src/CMakeFiles/GL.dir/gl/face.c.o
[ 21%] Building C object src/CMakeFiles/GL.dir/gl/fog.c.o
[ 23%] Building C object src/CMakeFiles/GL.dir/gl/fpe.c.o
[ 25%] Building C object src/CMakeFiles/GL.dir/gl/fpe_shader.c.o
[ 26%] Building C object src/CMakeFiles/GL.dir/gl/framebuffers.c.o
[ 28%] Building C object src/CMakeFiles/GL.dir/gl/getter.c.o
[ 30%] Building C object src/CMakeFiles/GL.dir/gl/gl.c.o
[ 31%] Building C object src/CMakeFiles/GL.dir/gl/glstate.c.o
[ 33%] Building C object src/CMakeFiles/GL.dir/gl/hint.c.o
[ 35%] Building C object src/CMakeFiles/GL.dir/gl/init.c.o
[ 36%] Building C object src/CMakeFiles/GL.dir/gl/light.c.o
[ 38%] Building C object src/CMakeFiles/GL.dir/gl/line.c.o
[ 40%] Building C object src/CMakeFiles/GL.dir/gl/list.c.o
[ 41%] Building C object src/CMakeFiles/GL.dir/gl/listdraw.c.o
[ 43%] Building C object src/CMakeFiles/GL.dir/gl/listrl.c.o
[ 45%] Building C object src/CMakeFiles/GL.dir/gl/loader.c.o
[ 46%] Building C object src/CMakeFiles/GL.dir/gl/matrix.c.o
[ 48%] Building C object src/CMakeFiles/GL.dir/gl/matvec.c.o
[ 50%] Building C object src/CMakeFiles/GL.dir/gl/pixel.c.o
[ 51%] Building C object src/CMakeFiles/GL.dir/gl/planes.c.o
[ 53%] Building C object src/CMakeFiles/GL.dir/gl/pointsprite.c.o
[ 55%] Building C object src/CMakeFiles/GL.dir/gl/preproc.c.o
[ 56%] Building C object src/CMakeFiles/GL.dir/gl/program.c.o
[ 58%] Building C object src/CMakeFiles/GL.dir/gl/queries.c.o
[ 60%] Building C object src/CMakeFiles/GL.dir/gl/raster.c.o
[ 61%] Building C object src/CMakeFiles/GL.dir/gl/render.c.o
[ 63%] Building C object src/CMakeFiles/GL.dir/gl/shader.c.o
[ 65%] Building C object src/CMakeFiles/GL.dir/gl/shaderconv.c.o
[ 66%] Building C object src/CMakeFiles/GL.dir/gl/stack.c.o
[ 68%] Building C object src/CMakeFiles/GL.dir/gl/stencil.c.o
[ 70%] Building C object src/CMakeFiles/GL.dir/gl/string_utils.c.o
[ 71%] Building C object src/CMakeFiles/GL.dir/gl/stubs.c.o
[ 73%] Building C object src/CMakeFiles/GL.dir/gl/texenv.c.o
[ 75%] Building C object src/CMakeFiles/GL.dir/gl/texgen.c.o
[ 76%] Building C object src/CMakeFiles/GL.dir/gl/texture.c.o
[ 78%] Building C object src/CMakeFiles/GL.dir/gl/uniform.c.o
[ 80%] Building C object src/CMakeFiles/GL.dir/gl/vertexattrib.c.o
[ 81%] Building C object src/CMakeFiles/GL.dir/gl/wrap/gl.c.o
[ 83%] Building C object src/CMakeFiles/GL.dir/gl/wrap/gles.c.o
[ 85%] Building C object src/CMakeFiles/GL.dir/gl/wrap/glstub.c.o
[ 86%] Building C object src/CMakeFiles/GL.dir/gl/math/eval.c.o
[ 88%] Building C object src/CMakeFiles/GL.dir/glx/hardext.c.o
[ 90%] Building C object src/CMakeFiles/GL.dir/glx/gbm.c.o
~/gl4es/src/glx/gbm.c:171:19: error: unknown type name ‘EGLConfig’
 int FindGBMConfig(EGLConfig *configs, int numFounds)
                   ^~~~~~~~~
src/CMakeFiles/GL.dir/build.make:1334: recipe for target 'src/CMakeFiles/GL.dir/glx/gbm.c.o' failed
make[2]: *** [src/CMakeFiles/GL.dir/glx/gbm.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/GL.dir/all' failed
make[1]: *** [src/CMakeFiles/GL.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ptitSeb** [comment]
Ok, commit 648de29347492b2b70ea6c87aea3d2912ae1c5bf should have fixed that.

**Comment by dsx724** [comment]
@ptitSeb Thanks a lot.

cmake . -DNOEGL=1 -DDEFAULT_ES=2
make
DISPLAY=:0 glmark2
LIBGL: Initialising gl4es
LIBGL: v1.1.1 built on Jan 10 2019 19:59:36
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: Hardware test disabled, nothing activated...
LIBGL: Targeting OpenGL 2.0
LIBGL: Forcing NPOT support by disabling MIPMAP support for NPOT textures 
LIBGL: Current folder is:/home/ubuntu
glmark2: symbol lookup error: glmark2: undefined symbol: glXQueryVersion

DISPLAY=:0 glxgears 
glxgears: symbol lookup error: glxgears: undefined symbol: glXMakeCurrent

DISPLAY=:0 strace glxgears 2>&1 | grep /                                                                                                                                             
execve("/usr/bin/glxgears", ["glxgears"], 0xffffd7bca6b0 /* 25 vars */) = 0
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/aarch64-linux-gnu/mali/libGL.so.1", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libX11.so.6", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/gl4es/lib/tls/aarch64/cpuid/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/tls/aarch64/cpuid", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/tls/aarch64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/tls/aarch64", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/tls/cpuid/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/tls/cpuid", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/tls/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/tls", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/aarch64/cpuid/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/aarch64/cpuid", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/aarch64/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/aarch64", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/cpuid/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib/cpuid", 0xffffda936920, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/gl4es/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/gl4es/lib", {st_mode=S_IFDIR|0755, st_size=20, ...}, 0) = 0
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libxcb.so.1", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libXau.so.6", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libXdmcp.so.6", O_RDONLY|O_CLOEXEC) = 3
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libbsd.so.0", O_RDONLY|O_CLOEXEC) = 3

It seems to be looking for libdl.so.2 in the wrong place.

**Comment by ptitSeb** [comment]
You build with `NOEGL=1`, that means `glX...` functions cannot be built, so glxgears will not run. Either build with EGL (if you can), or use something like SDLgears (if SDL can provide an GLES context, like on android).

**Comment by dsx724** [comment]
Thanks!
